home-assistant/iOS

README.md
add pod install command as otherwise  **bundle exec pod install** did not work
=> add pod install command

HomeAssistant/Views/AboutViewController.swift
After the change from gitter.im to discord the link needed to be updated.
=> Changing from gitter to discord link (resolves #48)

HomeAssistant/Views/WebViewController.swift
Fixes #38 
There were a few different ways to get the layout messed up but the easiest was to open settings, save, and the hit done.
=> Use one webview with auto layout to avoid clipping

HomeAssistant/Views/EurekaLocationRow.swift, Podfile, Podfile.lock
This needs a fix to EurekaLocationRow.swift. See commented out code: https://github.com/mnoorenberghe/home-assistant-iOS/commit/5ba14aeec537c828f4784dec5186cb0d2898a9d7
=> Lock Eureka pod to 4.0.1

HomeAssistant/Resources/Info.plist, HomeAssistant/Views/WebViewController.swift
This change depends on #54 or else the webview won't be using auto-layout. I can rebase it on top of that once it's merged.
=>  Support landscape orientation

HomeAssistant/ClientEvents/ViewControllers/ClientEventTableViewController.swift, HomeAssistant/HAAPI.swift, HomeAssistant/Resources/SwiftGen/Strings.swift, HomeAssistant/Resources/en.lproj/Localizable.strings, Shared/ClientEvents/Model/ClientEvent.swift
Added better display text for Event types.
Added better logging for location updates.
=> Added Improvements to Event Logging

HomeAssistant/ClientEvents/ViewControllers/ClientEventTableViewController.swift, HomeAssistant/HAAPI.swift, HomeAssistant/Resources/SwiftGen/Strings.swift, HomeAssistant/Resources/en.lproj/Localizable.strings, Shared/ClientEvents/Model/ClientEvent.swift, Shared/ClientEvents/Model/ClientEventStore.swift, SharedTests/ClientEventTests.swift
Add the ability to clear your local client events log.
This PR Depends on the Improved Logging PR going in first.
=> Add Delete events button

HomeAssistant/Views/DevicesMapViewController.swift, Shared/API/HAAPI.swift
Not sure WHY it made travis mad. But it did. Reverting that bit.
=> Reverting compactMap that made travis mad.

HomeAssistant/Views/SettingsViewController.swift, Shared/API/HAAPI+RequestHelpers.swift
Try to validate connection settings without the browser first. Only if that fails should we pop open the browser.
=> Smoother connection validation flow

HomeAssistant/Views/SettingsViewController.swift
Updating useInternalURL bool when switch is changed.
=> Fix internal API setting not sticking

HomeAssistant/ClientEvents/ViewControllers/ClientEventTableViewController.swift, HomeAssistant/Resources/SwiftGen/Strings.swift, HomeAssistant/Resources/en.lproj/Localizable.strings, HomeAssistant/Views/SettingsViewController.swift, HomeAssistant/Views/WebViewController.swift, Shared/API/HAAPI.swift, Shared/Authentication/AuthenticationAPI.swift, Shared/Authentication/TokenInfo.swift, Shared/Authentication/TokenManager.swift, Shared/ClientEvents/Model/ClientEvent.swift
1) Added logging of network requests with SSID to debug internal/external network calls.
2) Came up with a new strategy for token management. We now should never send a request with an expired token.
3)  Stubbed out the interface for supplying a token to the webview. Still needs backend work.
=> Added network logging (Temporary), changed token refresh behavior, token exchange stub

HomeAssistant/Views/WebViewController.swift
until we get the token passing, this has the side effect of signing you out of the internal webview.
=> Clear cache on refresh

HomeAssistant/Views/WebViewController.swift
=> Fix not using correct URL on refresh

README.md
I had to do this additional step to get a working development setup.
=> Add pod repo update step to install instructions

HomeAssistant/Classes/RegionManager.swift
Seems like this was missed during some heavy refactoring.
=> End background task before early exit

Shared/API/HAAPI.swift
Fix update prompt if minimumRequiredVersion = currentVersion
=> Fix upgrade version check

HomeAssistant/Views/WebViewController.swift
=> Use app's user agent for web view requests

.github/ISSUE_TEMPLATE/bug_report.md
Fix typo in HTML comment used for instruction
=> [ci skip] Update issue template

HomeAssistant/Utilities/Bonjour.swift
Amusingly enough, this is actually a bug in Foundation. When we retrieve the  `txtRecordData` dictionary representation, we're supposed to get back a `[String: Data]`. However, Foundation is more than happy to return an `NSNull` instead of the `NSData` which causes the bridging of the dictionary into Swift to crash.
Works around this problem by not allowing the bridge into Swift to type the value and instead filters out the invalid ones. I can confirm that I can still connect to a 0.110 instance after this filtering.
Fixes (iOS-side) #590.
=> Fix crash on discovery from 0.110

TodayWidget/TodayViewController.swift
Calculates the height of the Today Widget based on the number of items, rather than just display mode.
iOS currently forces the maximum height for display modes to be:
- compact, 110pt
- expanded, 660pt
This means there _is_ a maximum number of items which could be displayed at once.
Minimum size:
Full without expanded:
Compact with more:
Expanded:
Fixes #507.
=> Today Widget: Dynamic Height

HomeAssistant.xcodeproj/project.pbxproj, HomeAssistant/Resources/en.lproj/Localizable.strings, HomeAssistant/Views/Settings/Sensors/SensorDetailViewController.swift, HomeAssistant/Views/Settings/Sensors/SensorListViewController.swift, HomeAssistant/Views/SettingsViewController.swift, Shared/API/Models/WebhookSensor.swift, Shared/API/Webhook/WebhookSensors.swift, Shared/Resources/Swiftgen/Strings.swift
- Shows the device sensors and information about them, but doesn't let you turn off individual sensors yet.
- Only refreshes on appearance or when pulling to refresh the list of sensors.
Refs #358.
=> Sensors in Settings

HomeAssistant/Views/WebViewController.swift
=> Append User-Agent rather than resetting it

HomeAssistant/AppDelegate.swift, HomeAssistant/Resources/en.lproj/Localizable.strings, Shared/API/HAAPI.swift, Shared/Location/LocationTrigger.swift, Shared/Resources/Swiftgen/Strings.swift
Wires through the connect reason to the sensor update so we always have a valid trigger reason.
=> Use "Launch" and "Periodic" as update trigger reasons instead of "Initial"

HomeAssistant/Resources/en.lproj/Localizable.strings, HomeAssistant/Views/SettingsDetailViewController.swift, Shared/API/HAAPI.swift, Shared/Resources/Swiftgen/Strings.swift, Shared/Settings/SettingsStore.swift
=> Add "Device Name" to Settings for overriding the default

HomeAssistant.xcodeproj/project.pbxproj, Shared/API/Webhook/Sensors/WebhookSensor+Pedometer.swift, Shared/Common/Extensions/Version+HA.swift, Shared/Common/Structs/Environment.swift, Shared/Settings/SettingsStore.swift, SharedTests/Version+HA.test.swift, SharedTests/WebhookSensor/WebhookSensor+Pedometer.test.swift
=> Pedometer Sensor: Floors Up/Down Icon Updates

HomeAssistant/ClientEvents/Resources/ClientEvents.storyboard, HomeAssistant/ClientEvents/ViewControllers/ClientEventTableViewController.swift
- Shows a disclosure indicator when there's a payload that can be viewed, disabling selection on those which lack it.
- Fixes the Dark Mode and some inset handling on the list and the payload screen.
Fixes #626.
=> Event Log visual improvements

HomeAssistant/Resources/Base.lproj/Onboarding.storyboard
=> Fix hard-to-see cursor during manual onboarding

HomeAssistant.xcodeproj/project.pbxproj, HomeAssistant/Resources/Info.plist, HomeAssistant/Resources/en.lproj/Localizable.strings, HomeAssistant/Utilities/OpenInFirefoxControllerSwift.swift, HomeAssistant/Utilities/Utils.swift, HomeAssistant/Views/AboutViewController.swift, HomeAssistant/Views/NotificationCategoryConfigurator.swift, HomeAssistant/Views/Onboarding/ConnectionErrorViewController.swift, HomeAssistant/Views/SettingsDetailViewController.swift, HomeAssistant/Views/WatchComplicationConfigurator.swift, HomeAssistant/Views/WebViewController.swift, Podfile.lock, Shared/Resources/Swiftgen/Strings.swift
=> Add support for opening links in different browsers

HomeAssistant/Views/Settings/Sensors/SensorListViewController.swift
=> Fix sensor list jumping to top on update

Shared/Location/CLLocationManager+OneShotLocation.swift
I have no idea if this makes a difference.
=> One Shot Location: Remove Distance Filter, Fix Log

HomeAssistant.xcodeproj/project.pbxproj, HomeAssistant/Resources/en.lproj/Localizable.strings, HomeAssistant/Views/Settings/NotificationRateLimitsAPI.swift, HomeAssistant/Views/Settings/NotificationSettingsViewController.swift, Podfile, Podfile.lock, Shared/Resources/Swiftgen/Strings.swift
- Adds a 'retry' button for if the API call fails.
- Updates the footer to be variable based on the API response for maximum.
=> Remove Firestore dependency; use rate limit API

HomeAssistant/AppDelegate.swift, HomeAssistant/Utilities/Utils.swift
=> Use "Open Links In" for notification URLs

Shared/API/Webhook/Sensors/BatterySensor.swift, SharedTests/Sensors/BatterySensor.test.swift
=> Fix battery sensor icon when unplugged at 100%

Shared/API/Webhook/Sensors/GeocoderSensor.swift
Reverts incorrect change introduced at https://github.com/home-assistant/iOS/commit/87d859eae5a1572b16b1b2d7c7810b26f52ab733#diff-dfa96c04df76a3aa3ddb21dd76f512dbL91-L109
=> Revert geocoder change

Shared/API/Webhook/Request&Response/WebhookManager.swift
By default, background networking requests will stick around and continually retry for 7 days. However, if the user's configuration for some reason has requests point to a URL that will always time out, this means we'll have a bunch of requests sitting around doing nothing. This sets the maximum time we're wiling to have background retries to 2 hours.
Adds a log on startup to see how many tasks are currently in the queue for the session, in case we have a backup. Mostly helpful for forensic investigation.
=> Webhooks: expire requests after 2 hours, add logging

Shared/API/Webhook/Request&Response/WebhookManager.swift, SharedTests/Webhook/WebhookManager.test.swift
- Stops using file uploads for non-background uploads. Background uploads copy the file out of our container, but non-background do not; this causes a race condition where we may be removing the file during or before the request begins and sends the data to the server, causing partial uploads and otherwise invalid requests. However, these invalid requests end up being a timeout -- likely because the server's waiting for the data that we're not quite sending. Refs #777.
- Moves the session info into the same mutex queue as other data, since it's accessed basically in parallel, and this is a lot easier to read.
=> Fix, again, sending network requests in background in beta

HomeAssistant.xcodeproj/project.pbxproj, HomeAssistant/Views/ActionConfigurator.swift, HomeAssistant/Views/VoiceShortcutRow.swift
- Restores the cancel button for Action editing.
- Adds the Add to Shortcuts button in the "Name" section.
=> "Add to Shortcuts" button in Action configurator

HomeAssistant/Resources/Info.plist
Adds whitelisted Bonjour services and permission string. Fixes #743.
=> iOS 14: local networking Info.plist changes

.github/ISSUE_TEMPLATE/bug_report.md
* Removes reference to "In-Development Location" from Issue Template
* Also comment's out a tip that should have been commented originally
=> Remove reference to "In-Development Location" from Issue Template

HomeAssistant/AppDelegate.swift, HomeAssistant/Views/Settings/NotificationSettingsViewController.swift, HomeAssistant/Views/SettingsDetailViewController.swift, HomeAssistant/Views/SettingsViewController.swift
I'm not sure why these started erroring suddenly, but no amount of cleaning would make the build work either.
=> Fix compiling (?)

HomeAssistant/AppDelegate.swift
We know we don't write to the Realm database in extensions, so I at least feel confident that the risk is low here. Still gross though.
=> Allow TestFlight users to work around iOS 14 crasher

Shared/API/Models/RealmScene.swift
When we were persisting the Action created by the Scene, if the Scene wasn't already added to Realm then we'd drop the Action instead of persisting it. This is because we're not directly referencing the Action in the persisted Scene -- we rely on the automatic inverse relationship list for accessing it. Resolves the crash by making sure we always use an active Realm (rather than an optional one) when persisting the Action.
Fixes #885.
=> Fix crash customizing a just-created Scene Action

Shared/Common/Extensions/Realm+Initialization.swift
I have no idea how it's possible to get the database in this state. I believe it's going to boil down to an older version of Realm allowing it to happen, and a newer version of Realm finding it to be a problem.
The UI currently allows you to create a second instance of the same identifier (but Realm will collapse them into the same object, confusingly enough) so that's possibly one of the causes, and the other could be old import code for the categories.
Either way: this will delete one of the categories on disk that has the same identifier as another.
=> Fix database error for duplicate notification categories

HomeAssistant.xcodeproj/project.pbxproj, Shared/Common/Extensions/INImage+MaterialDesignIcons.swift, Shared/Common/SiriIntents+ConvenienceInits.swift
New iOS 14 API lets us assign an image to show up along with the actions.
=> Add icons to Actions when choosing for widget/shortcuts

HomeAssistant/AppDelegate.swift
- Marks the `window` property as deprecated so it's obvious when it's used.
- Fixes the Updater, Notification Settings opener, and iOS 14 Workaround prompts to use the web view controller's stack for presentation.
=> Fix a few non-multi-window-supporting AppDelegate hooks

Shared/Common/Structs/DeviceWrapper.swift
For example, my laptop now reports as `MacBookPro15,2` instead of `x86_64` and (Big Sur) `11.0.0` instead of `14.0`.
Fixes #939.
=> Fix Mac device model and operating system values

HomeAssistant/Views/SettingsViewController.swift
=> Clean up log exports when sharing

HomeAssistant/AppDelegate.swift, HomeAssistant/Resources/en.lproj/Localizable.strings, HomeAssistant/Utilities/MenuManager.swift, Shared/Networking/Updater.swift, Shared/Resources/Swiftgen/Strings.swift
Shows an alert if the user initiates the update check informing them if they're on the latest version; otherwise, behaves the same as the on-startup check.
=> Add "Check for updates…" to Application menu

Shared/API/Webhook/Sensors/LastUpdateSensor.swift, SharedTests/Sensors/LastUpdateSensor.test.swift
=> Use Mac-specific icons for Last Update Trigger Sensor

.github/ISSUE_TEMPLATE/bug_report_mac.md, .github/ISSUE_TEMPLATE/feature_request_mac.md
Fix copy and paste error (non-unique names)
=> Fix issue templates

HomeAssistant/Resources/en.lproj/Localizable.strings, Shared/Resources/Swiftgen/Strings.swift, Widgets/Actions/WidgetActions.swift, Widgets/Actions/WidgetActionsProvider.swift
- Provide default Actions to unconfigured widget. This applies to both previews (in the gallery) and added but default ones. This means no more "Redacted Text" in previews. Fixes #995.
- Add description to Action Widget. Fixes #943.
=> Improvements to Action Widget Previews

HomeAssistant.xcodeproj/project.pbxproj, HomeAssistant/AppDelegate.swift, HomeAssistant/Classes/LifecycleManager.swift
=> Fix lifecycle handling on iOS 13+

HomeAssistant/Resources/Base.lproj/InfoPlist.strings, HomeAssistant/Resources/Info.plist, HomeAssistant/Resources/en.lproj/InfoPlist.strings
=> Fix crash when using Camera to upload profile photo

HomeAssistant/Scenes/WebViewSceneDelegate.swift
=> Set smaller minimum size on webview windows

HomeAssistant/Classes/LifecycleManager.swift, HomeAssistant/Resources/en.lproj/Localizable.strings, HomeAssistant/Views/Settings/Sensors/SensorListViewController.swift, Shared/Resources/Swiftgen/Strings.swift
=> Update periodic description on Mac

HomeAssistant/Views/ActionConfigurator.swift
Server-defined actions are not meant to be editable, and the 'save' button ends up crashing because that flow is untested. This hides the button, since it doesn't do anything, and moves the disabled text field up a section for visual sake.
This also fixes the 'this action is defined…' text not showing up, because the 'visuals' included the disabled text, and we considered it not fully-uneditable.
=> Fix 'save' on server-defined Actions

HomeAssistant/Views/WebViewController.swift
=> Fix some CodeMirror issues caused by User-Agent sniffing

Shared/Networking/ConnectionInfo.swift
=> Strip trailing / in URL, since // will cause errors

.github/workflows/bump_build.yml, .github/workflows/download_localized_strings.yml, .github/workflows/set_version.yml
There has _got_ to be a way to write macros or functions or something for these workflows besides actions that cannot call other actions?
=> Create PRs for GitHub actions that need to make changes

Sources/Shared/API/Models/NotificationCategory.swift
=> Fix example for notification category dictionary-based URL

HomeAssistant.xcodeproj/project.pbxproj, Sources/WatchApp/Base.lproj/Interface.storyboard
Watch may be the most frustrating platform to build to.
=> Fix crash on launch in WatchApp due to module name change

Sources/Shared/API/Models/NotificationCategory.swift
=> Really fix the example notification category YAML

Sources/Shared/API/Models/WatchComplication.swift
In HA versions prior to 0.117, the template rendering returns strings for floats using `.` as the decimal separator. If the user's current locale uses `,` as the separator, our string to number parsing here fails to understand what the number is. Since it's freeform text, this also needs to fall back to using the locale-aware formatter in case they typed manually something like `0,33`.
Fixes #1188.
=> Fix Complication Ring/Gauge values in locales using `,` as decimal separator

Sources/Extensions/Watch/ExtensionDelegate.swift
Apple's docs say:
> Background data may be received before, after, or during your `handle(_:)` method. The `handle(_:)` may also receive multiple background watch connectivity tasks at once, may be called while you’re currently processing another set of background watch connectivity tasks, or may even be called while your app is in the foreground. You must check for and handle all of these cases.
Although we check if there's more data before terminating existing tasks, we don't check if we've already handled the data being requested. This means we could get in a situation where we process the data before we're told to handle the background task.
This is, in other words, the WatchConnectivity version of #1202.
=> Handle ending the WatchConnectivity background task when no data is left

Sources/App/Settings/SettingsViewController.swift, Sources/App/WebView/WebViewController.swift
=> Don't open settings on iPad in separate scene

Sources/Shared/API/Webhook/Sensors/ConnectivitySensor.swift, Sources/Shared/Common/Extensions/Reachability+NetworkType.swift
=> Add 5G to Connectivity Sensor

Sources/App/WebView/WebViewController.swift
=> Fix crash when URL is configured to non-http/https scheme

Podfile.lock, Sources/App/AppDelegate.swift, Sources/App/Onboarding/AuthenticationViewController.swift, Sources/App/Settings/AppleWatch/ComplicationEditViewController.swift, Sources/App/Settings/Notifications/NotificationCategoryConfigurator.swift, Sources/App/Settings/Notifications/NotificationSettingsViewController.swift, Sources/App/Settings/SettingsDetailViewController.swift, Sources/App/Utilities/DNSResolver.swift, Sources/App/WebView/IncomingURLHandler.swift, Sources/Shared/API/MJPEGStreamer.swift, Sources/Shared/Environment/DeviceWrapperBatteryObserver.swift
Worth noting that this resolves a crash on Watch in Realm related to the iOS 14 file lock changes that Apple reverted. Looks like the watchOS version wasn't disabled, so it was crashing and they fixed that.
=> Update dependencies, correct SwiftLint changes

Sources/Extensions/Watch/ComplicationController.swift
Shows a preview image rather than "--" for everything, when we don't provide it.
=> Provide example template for placeholder complications

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/AppDelegate.swift, Sources/App/Notifications/NotificationManager.swift
=> Move UNNotification & FirebaseMessaging into its own manager

CONTRIBUTING.md
Based on Discord conversation with @zacwest, expanding CONTRIBUTING.md to give newcomers some pointers to how to learn Swift. This could be useful coming off the heels of the Home Assistant Conference 2020, in which attendees were invited to learn Swift and contribute back.
=> add Swift language resources to CONTRIBUTING.md

Sources/Extensions/NotificationContent/MapViewController.swift, Sources/Extensions/Watch/MapNotificationController.swift, Sources/Shared/Common/Extensions/CLLocation+Extensions.swift
Watch side equivalent of #1307.
=> Fix latitude/longitude handling on Watch, too

Sources/Shared/API/Webhook/Sensors/InputDeviceSensor.swift
Breaking change. Fixes #1261.
Collapses all Camera and Microphone sensors from one-sensor-per-device to two camera and two microphone sensors:
- `binary_sensor.[device]_microphone_in_use` and `binary_sensor.[device]_camera_in_use` (value: true/false)
- `sensor.[device]_active_microphone` and `sensor.[device]_active_camera` (value: name or "Inactive")
This is unfortunately required because both the the `kCMIODevicePropertyDeviceUID`/`kAudioDevicePropertyDeviceUID` and the `kCMIOObjectPropertyName`/`kAudioObjectPropertyName` are not stable; the IDs change and names gain `#2`, `#3`, etc., suffixes. This is despite the documentation reading:
> A CMIODevice's UID is persistent across boots.
and
> An AudioDevice's UID is persistent across boots.
Were this the case, we wouldn't need to worry -- …
=> Collapse microphones and cameras into singular sensors

Sources/App/Resources/Info.plist, Sources/App/Resources/en.lproj/InfoPlist.strings
=> Add microphone usage string to Info.plist

Sources/App/Resources/Base.lproj/Onboarding.storyboard
This is the only one in the storyboard which requires editing locally. Fixes #1322.
=> Remove 'iOS' mentions

HomeAssistant.xcodeproj/project.pbxproj
Requirement to submit to App Store Connect.
=> Bump Intents extension minimum to macOS 11.0

Sources/App/Utilities/MenuManager.swift, Sources/Shared/Environment/Updater.swift
Forgot to hide the item in #1321. Fixes #1338.
Before: 
After:
=> Hide "Check for Updates…" menu item in App Store build

Sources/App/WebView/WebViewController.swift
When encountering a 404 or 503 or whatnot on the main WebView, instead redirect to the main dashboard when pulling to refresh afterwards. Since these error pages likely do not show the frontend, this avoids a state where it's not possible to use the app without force-quitting.
Fixes #1172.
=> Redirect to main dashboard when pull-to-refresh after a 4xx/5xx error

Sources/App/Settings/Notifications/NotificationCategoryConfigurator.swift
Fixes #1256.
When the category isn't persisted yet, we were still persisting the action into Realm. This means the action was deleted successfully, but the delete didn't cascade because the category wasn't yet persisted. The final result of this was that the category could refer to deleted objects, which crash when accessed.
n/a
n/a
=> Fix crash deleting action in a new notification category

Podfile.lock, Tools/BuildMaterialDesignIconsFont.sh
```
$ bundle exec pod outdated
MaterialDesignIcons up to date at version 5.8.55
Updating spec repo `trunk`
No pod updates are available.
```
First time I've seen this in this project. 😆
=> Update all dependencies

.github/workflows/download_localized_strings.yml
If there are changes, it creates or updates a PR for the strings. If there aren't any changes, it does nothing.
=> Trigger localized string action automatically

Sources/MacBridge/MacBridgeStatusItem.swift
=> Only hide/show via status item on mouse click up, not down

.github/workflows/distribute.yml
(necessary to work in another branch)
=> Add placeholder workflow for distribute

.github/workflows/ci.yml, .github/workflows/distribute.yml, .github/workflows/download_localized_strings.yml, .github/workflows/set_version.yml
CI differs in built Podfiles, so this ends up generating changes at all times. Scopes to only commit the localized strings themselves.
=> Fix GitHub action for updating localized strings

Sources/Shared/API/Webhook/Networking/WebhookManager.swift
Maybe fixes a few crashes happening on watchOS that look like the iOS 14-era background crashes around file locks.
I'm pretty sure Realm is working around the watchOS crashes by doing some kind of different file lock, so it's possible that we're entering the background and being killed for being in a write at the same time. All of these crashes have the infamous 0xdead10cc code.
This may address crashes which look like:
```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace RUNNINGBOARD, Code 0xdead10cc
Triggered by Thread:  0
```
As well as ones that are crashing deep in Realm during a write:
```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, …
```
=> Wrap webhook response parsing in background task

.github/workflows/ci.yml, .github/workflows/distribute.yml, .github/workflows/download_localized_strings.yml, .gitignore, Brewfile, README.md, fastlane/Fastfile
Rather than coding in `brew install` in random places, this unifies it all into the one file.
I'm ignoring the lock file because it's not actually a lock file; it does not control which versions are installed in any way, it's just notes about what was installed.
=> Switch to using Brew Bundle for deps

Sources/Extensions/Watch/ExtensionDelegate.swift
Potentially fixes an issue where we do not cancel a watch connectivity request in time and get killed by the system.
I cannot find any code paths that may be causing this issue, and I can't get it to happen in debugging (not that debugging with the watchOS simulator is, you know, usable -- wow it's so bad) but I can at least validate that we are calling it within the watchdog timeout from the system, which is 15.0s.
There's probably an issue somewhere in the path between using HA talking to Communicator talking to WatchConnectivity. I don't feel super confident in the Communicator code paths -- there's cases where e.g. failing to decide or something may not trigger handlers.
For a little bit I was distracted by the complication updating, but I already took that into account and made those …
=> Add backup timer for watch connectivity background task completion

Sources/Shared/API/Webhook/Sensors/SensorContainer.swift, Tests/Shared/Sensors/SensorContainer.test.swift
Fixes #1460.
Fixes our internal cache being out of sync with the sensor values on the server.
This issue occurs when, for example, we transition from value1 -> value2 -> value1. If the value2 update fails from our perspective, but successfully hits the server, we may not realize that we need to send value1 up again in the future.
=> Fix not updating sensors when prior update fails for transient value change

Sources/Shared/API/Webhook/Sensors/SensorContainer.swift, Tests/Shared/Sensors/SensorContainer.test.swift
Fixes #1473.
Refs #1460/#1467.
When an earlier request gets applied later than we expect, we also need to assume it has replaced values similar to the transient update case fixed before.
I am going to keep telling myself that the long-term benefit of the sensor caching outweighs having to figure out all of these real-world edge cases the hard way. In this case, I already expected it, I just did not fully think through the ramifications of the edge case and how it would look from the server perspective.
=> Fix an out-of-order sensor caching issue

Sources/Shared/Common/ObjectMapperTransformers.swift
This PR improves performance of parsing API requests by refactoring Date Formatter into `static var` so it is not recreated many times again.
=> Improve performance of date formatter used for parsing API responses

HomeAssistant.xcodeproj/project.pbxproj, Podfile, Podfile.lock, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/Connection/ConnectionSettingsViewController.swift, Sources/App/Utilities/WebSocketStatusRow.swift, Sources/Shared/API/HAAPI.swift, Sources/Shared/Environment/Environment.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
Adds [HAKit](https://github.com/home-assistant/HAKit) to connect to the WebSocket API.
Currently not used for anything other than showing the status of its connection.
=> Add WebSocket API connecting and status

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/ClientEvents/LocationHistoryDetailViewController.swift, Sources/App/ClientEvents/LocationHistoryListViewController.swift, Sources/App/Settings/Notifications/NotificationCategoryConfigurator.swift, Sources/Shared/API/Models/LocationHistory.swift, Sources/Shared/Common/Extensions/UIBarButtonItem+Additions.swift, Sources/Shared/Environment/Constants.swift
Adds more detail to the list and reshuffles detail to include up/down buttons to move through entries.
This also adds more information to the debug file shared and improves the selected state handling in the list.
=> Improve the location history screens

Podfile.lock
Hopefully fixes home-assistant/HAKit#17 (background crash) and odd connected-but-not state.
=> Bump HAKit

Sources/App/Settings/SettingsDetailViewController.swift
Fixes #837.
Resets to no customized icon when changing to debug in debug, release in release or beta in beta. 
The default icons are more fine-tuned; for example, at smaller sizes, release shows the less-branchy home icon.
=> Reset to default icon when choosing e.g. release in release

Sources/App/AppDelegate.swift, Sources/App/Onboarding/AuthenticationViewController.swift, Sources/App/Onboarding/ConnectInstanceViewController.swift, Sources/App/Onboarding/PermissionsViewController.swift, Sources/App/Settings/SettingsViewController.swift, Sources/App/WebView/WebViewController.swift, Sources/Extensions/Intents/IntentHandler.swift, Sources/Extensions/Share/ShareViewController.swift, Sources/Extensions/Today/TodayViewController.swift, Sources/Shared/API/HAAPI.swift, Sources/Shared/Environment/Environment.swift
Removes non-API-scoped getters for token information.
=> Remove global-ish token manager

Sources/App/Utilities/UIApplication+BackgroundTask.swift, Sources/Shared/API/Webhook/Sensors/ActivitySensor.swift, Sources/Shared/API/Webhook/Sensors/PedometerSensor.swift, Sources/Shared/Common/BackgroundTask.swift, Sources/Shared/Environment/CrashReporter.swift, Sources/Shared/Environment/Environment.swift, Sources/Shared/Environment/ServerAlerter.swift
=> Limit Sentry breadcrumbs to warning & reduce some logs

Sources/App/Settings/Eureka/AccountRow.swift
Fixes #1581.
Fixes logging every entity's state on every update if in preferences, which is so much logging that the date formatter effectively takes forever.
=> Reduce logging of account row

Sources/App/Settings/Observation/NotificationCategory+Observation.swift
Fixes not registering the DYNAMIC category, which is required to show the "drag to expose more" bar as well as the 'Loading actions…' quasi-action.
Whoops. Missed this when tidying up this area after deciding 'builtin' categories weren't a good idea.
=> Fix not registering 'DYNAMIC' category

.github/workflows/ci.yml, .github/workflows/distribute.yml, Configuration/Podspecs/Firebase.podspec.json, Configuration/Podspecs/Realm.podspec.json, Podfile, Podfile.lock, Sources/App/Onboarding/OnboardingAuthenticationController.swift, Sources/App/Settings/SettingsDetailViewController.swift, Sources/App/Utilities/NSURL+QueryDictionary.swift, Sources/App/Utilities/Permissions.swift, Sources/App/Utilities/VoiceShortcutsManager.swift, Sources/Extensions/Intents/CallService.swift, Sources/Extensions/Intents/FireEvent.swift, Sources/Extensions/Intents/SendLocation.swift, Sources/Extensions/NotificationContent/CameraViewController.swift, Sources/Shared/API/Authentication/AuthenticationAPI.swift, Sources/Shared/API/ConnectionInfo.swift, Sources/Shared/API/HAAPI.swift, Tests/Shared/BackgroundTask.test.swift, Tests/Shared/ModelManager.test.swift, Tests/UI/HomeAssistantUITests.swift
=> Bump dependencies, stop compiling Firebase in CI

Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentManager.swift, Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentParserCamera.swift, Tests/Shared/NotificationAttachment/NotificationAttachmentManager.test.swift, Tests/Shared/NotificationAttachment/NotificationAttachmentParserCamera.test.swift
=> Fix camera-by-entity-id attachments not working with dynamic

Podfile.lock, Sources/Shared/Environment/Environment.swift
=> Bump HAKit and set User-Agent

HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Debug.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Release.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Intents.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-NotificationContent.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-NotificationService.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Share.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Today.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Shared-iOS.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Tests-UI.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Tests-Unit.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp (Complication).xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp (Notification).xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
=> Add xcscheme changes from executable changes

.github/workflows/download_localized_strings.yml
Use the lokalise token that is stored at the org level.
=> Use org secret lokalise token

.github/workflows/ci.yml, .github/workflows/distribute.yml, .github/workflows/download_localized_strings.yml, Configuration/Podspecs/Firebase.podspec.json, Configuration/Podspecs/Realm.podspec.json, Podfile.lock, README.md, Sources/App/Settings/AppleWatch/ComplicationFamilySelectViewController.swift, Sources/App/Settings/Notifications/NotificationCategoryConfigurator.swift, Sources/Shared/API/Responses/StreamCameraResponse.swift, Sources/Shared/Environment/ActiveStateManager.swift
=> Bump Xcode and dependencies

Sources/Shared/Common/Extensions/CLKComplication+Strings.swift
Fixes #1668.
Went through the [table of values](https://developer.apple.com/design/human-interface-guidelines/watchos/overview/complications/) again.
=> Fix a few complication image sizes

Sources/Shared/Environment/Environment.swift
Hopefully this makes log files a bit easier to read when app extensions are also abound.
=> Segment log files by process name

Podfile.lock, Sources/App/Settings/SettingsDetailViewController.swift
Bumps HAKit to fix a crash if port specified is >max. Updates SwiftFormat while I'm in here.
=> Bump HAKit & SwiftFormat

Sources/App/WebView/WebViewController.swift, Sources/App/WebView/WebViewWindowController.swift
This should reduce memory and bandwidth usage when launching in the background for things like location changes.
=> Don't load WebView when launching in background

Sources/App/Onboarding/AuthenticationViewController.swift
Improves the error message display when running landing page, refs #1804. Might be better to make this show "not yet ready for setup" or something in the future.
Fixes the status code check (which needs to happen before checking for an underlying error) and includes part of the response to make it easier to diagnose by screenshot.
| -- | -- |
| ![image](https://user-images.githubusercontent.com/74188/126740127-5391aa57-4b98-4a26-bb0c-b9a9d4ec73f8.png) | ![image](https://user-images.githubusercontent.com/74188/126739835-e7eaa16d-c999-4105-ac2a-60bcbbe4cfe0.png) |
=> Improve some error messages when authentication fails

Podfile, Podfile.lock
=> Bump HAKit and fix podspec discovery issue

HomeAssistant.xcodeproj/project.pbxproj, HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Beta.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Debug.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Release.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Codegen.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Intents.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-NotificationContent.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-NotificationService.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Share.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Today.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Launcher.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Shared-iOS.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Tests-UI.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Tests-Unit.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp (Complication).xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp (Notification).xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
Xcode wants to do these, and I toggled on ccov on random schemes so switching schemes doesn't cause a full recompile.
=> Minor Xcode 13 version upgrade changes

Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift, Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift, Sources/Shared/Common/Extensions/Realm+Initialization.swift, Sources/Shared/Common/Extensions/UIImage+Icons.swift, Sources/Shared/Environment/Constants.swift, Sources/Shared/Iconic/MDIMigration.swift
Styles with a background and a decorator icon to differentiate it from actions.
| Small/Expanded | Normal | Full |
| <img width="200" src="https://user-images.githubusercontent.com/74188/135736388-e685feaa-d368-470b-b66d-38ca5ccd1415.png"> | <img width="200" src="https://user-images.githubusercontent.com/74188/135736392-ee55289b-8ff4-435c-93c7-98b5c0044e44.png"> | <img width="200" src="https://user-images.githubusercontent.com/74188/135736394-a331cb63-066b-4e48-bcd2-b3c859072377.png"> |
- Adds a small gradient on top of both widget kinds.
- Supports doing an on-the-fly MDI migration if we encounter an icon that was deleted/renamed.
=> Update appearance of widgets

Sources/Shared/API/Models/Action.swift, Sources/Shared/API/Models/ModelManager.swift, Sources/Shared/API/Models/NotificationCategory.swift, Sources/Shared/API/Models/RealmPersistable.swift, Sources/Shared/API/Models/RealmScene.swift, Sources/Shared/API/Models/RealmZone.swift, Tests/Shared/ModelManager.test.swift
=> Fix scene actions not setting the right server or sort order

Sources/Shared/API/ServerManager.swift, Sources/Shared/Environment/CrashReporter.swift, Sources/Shared/Environment/Environment.swift, Tests/Shared/ServerManager.test.swift
=> Fix crash by making Current reentrant during setup

Sources/App/Resources/Base.lproj/Intents.intentdefinition, Sources/App/Resources/en.lproj/Intents.strings
=> Remove ${server} from shortcuts summaries

Sources/App/Onboarding/API/OnboardingAuth.swift, Tests/App/Auth/OnboardingAuth.test.swift
A common case appears to be an internal we cannot connect to (outdated IP address or SSL to a local IP) and an external address we are able to connect to (like Nabu Casa). Detect this and switch to talking to just the external if the internal fails connectivity checks.
=> Try both internal and external URLs in onboarding

.github/workflows/download_localized_strings.yml
=> Fix localized string update not updating SwiftGen

Sources/Shared/API/ServerManager.swift, Tests/Shared/ServerManager.test.swift
Caching is the hardest problem in computer science.
=> Fix deleting and re-adding the same server getting old info

Podfile.lock, Sources/Shared/API/ServerManager.swift, Tests/Shared/ServerManager.test.swift
Fixes a handful of crashes in the beta as very little worked simultaneously on other threads.
Uses `HAProtected` from HAKit since I didn't feel like writing it again.
=> Make server access threadsafe

Sources/App/Servers/ServerSelectViewController.swift, Sources/App/WebView/WebViewWindowController.swift
=> Three finger swipe up to open select server list

Sources/App/WebView/WebViewController.swift
Watches for errors and logs info about them when they occur.
Because of crossorigin policies in the WebView, these all log like:
> WebView error: ["filename": "", "colno": 0, "lineno": 0, "message": "Script error."]
For now it's better to see that an error occurred than not, but it would be nice to make this not get the crossorigin-redacted version.
… or it does work, as on iOS 12 I'm seeing:
> WebView error: ["filename": "http://10.0.2.2:8123/frontend_es5/app.a0587d58.js", "message": "ReferenceError: Can't find variable: regeneratorRuntime", "lineno": 2, "colno": 514043]
which may indicate that the js served by the frontend is tagged in a way that this works.
=> Log JavaScript errors encountered by the WebView

Sources/PushServer/SharedPush/Sources/NotificationParserLegacy.swift, Sources/PushServer/Sources/App/Controllers/PushController.swift, Sources/PushServer/Tests/AppTests/PushControllerTests.swift, Sources/PushServer/Tests/AppTests/RateLimitsTests.swift, Sources/PushServer/Tests/SharedPushTests/notification_test_cases.bundle/command_request_location_update_webhook_id.json, Sources/PushServer/Tests/SharedPushTests/notification_test_cases.bundle/webhook_id.json
=> Move webhook_id into legacy parser, fix tests

HomeAssistant.xcodeproj/project.pbxproj, Podfile, Podfile.lock, Sources/App/AppDelegate.swift, Sources/App/Notifications/NotificationManager.swift, Sources/App/Resources/GoogleService-Info-Beta.plist, Sources/App/Resources/GoogleService-Info-Debug.plist, Sources/App/Resources/GoogleService-Info-Release.plist, Sources/App/Resources/Info.plist, Sources/App/Settings/DebugSettingsViewController.swift, Sources/App/Settings/Notifications/NotificationRateLimitViewController.swift, Sources/App/Settings/Notifications/NotificationRateLimitsAPI.swift, Sources/App/Settings/Notifications/NotificationSettingsViewController.swift, Sources/App/Settings/SettingsDetailViewController.swift, Sources/PushServer/Sources/App/Models/RateLimitsGetOutput.swift, Sources/PushServer/Sources/App/configure.swift, Sources/PushServer/Tests/AppTests/RateLimitsControllerTests.swift, Sources/Shared/API/HAAPI.swift, Sources/Shared/Settings/SettingsStore.swift
Reverts home-assistant/iOS#2028
=> Revert "Remove Firebase"

HomeAssistant.xcodeproj/project.pbxproj, HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Beta.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Debug.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Release.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Codegen.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Intents.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-NotificationContent.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-NotificationService.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-PushProvider.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Share.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Today.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Launcher.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Shared-iOS.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Tests-UI.xcscheme, HomeAssistant.xcodeproj/xcshareddata/xcschemes/Tests-Unit.xcscheme, Sources/App/Onboarding/API/OnboardingAuth.swift, Sources/App/WebView/WebViewWindowController.swift, Sources/Shared/API/HAAPI.swift, Sources/Shared/API/Webhook/Networking/WebhookManager.swift, Sources/Shared/Environment/ServerAlerter.swift
=> Fix warnings in Xcode 13.3

Sources/App/Settings/AboutViewController.swift
Refs #2070.
Makes it a little easier to reference the version number.
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2022-02-11 at 17 00 59](https://user-images.githubusercontent.com/74188/153689729-506f8c8b-298b-4f04-a46e-98bae0eb9bb3.png) | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2022-02-11 at 17 01 00](https://user-images.githubusercontent.com/74188/153689733-9df5bf96-1f17-4f9c-b567-67a48248ccb4.png) |
=> Add copy option when tapping version number

Sources/Shared/API/Webhook/Sensors/LastUpdateSensor.swift, Sources/Shared/Iconic/MDIMigration.swift, Sources/Shared/Iconic/MaterialDesignIcons.swift, Tests/Shared/Sensors/LastUpdateSensor.test.swift, Tools/BuildMaterialDesignIconsFont.sh
=> Bump MaterialDesignIcons to 7.0.96

Sources/Shared/API/SecurityExceptions.swift
=> Fix compiling under Xcode 14

CONTRIBUTING.md, Sources/App/ZoneManager/ZoneManagerProcessor.swift, Sources/Shared/API/Models/WebhookUpdateLocation.swift
This clarifies in the contributing docs which project is being contributed to and which repo to work against - previously it said just "Home Assistant" which could be confusing. 
This also updates the repo URL in the contributing docs and at the same time several code comments that also used the older repo URL.
=> Update repo name and URL in CONTRIBUTING docs

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/SettingsDetailViewController.swift, Sources/App/Utilities/OpenInFirefoxControllerSwift.swift, Sources/App/Utilities/Utils.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
Adds the option to open links from the companion app within a private browser tab, if the selected browser has this feature (via universal links). The new "Open in Private Tab" UI toggle in settings only shows up when a supported browser is selected.
This option currently only applies to Firefox as it is the only browser to support this (Focus/Klar are private by default and Safari/Chrome don't have a way to open a private or incognito tab at present). That said, the code is written to be extensible should this change later.
Note that if this new option isn't selected, we can't force Firefox to open a link in a "non-private" tab – Firefox iOS [intentionally uses](https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Application/NavigationRouter.swift#L216-L217) the last mode …
=> Add option to open links in Private browser tab

.github/workflows/ci.yml, Podfile, Podfile.lock
=> Combine lint into one command on Ubuntu

.github/workflows/ci.yml
=> Skip size on non-pull-requests

.github/workflows/ci.yml, .github/workflows/distribute.yml, Podfile.lock, README.md
=> Bump Xcode version to 14.1

HomeAssistant.xcodeproj/project.pbxproj
=> Weak link against MatterSupport

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Resources/Base.lproj/Intents.intentdefinition, Sources/App/Resources/Info.plist, Sources/Extensions/Intents/Resources/Info.plist, Sources/Shared/API/HAAPI.swift, Sources/Shared/Common/ServerProviding.swift, Sources/Shared/Environment/Constants.swift, Sources/Shared/Environment/LocalizedManager.swift, Sources/Shared/Intents/AssistIntentHandler.swift, Sources/Shared/Intents/IntentHandlerFactory.swift
Adds an intent handler for the conversation feature in core-2023.2.
=> Add intent handler for conversation

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Resources/Base.lproj/Intents.intentdefinition, Sources/Shared/Common/Locale+IntentLanguage.swift, Sources/Shared/Intents/AssistIntentHandler.swift
=> Add language as parameter to Assist intent

Sources/App/Resources/Base.lproj/Intents.intentdefinition, Sources/Shared/Intents/AssistIntentHandler.swift
=> Include Assist JSON value in Shortcuts result

Sources/Shared/Notifications/LocalPush/LocalPushManager.swift, Tests/Shared/LocalPushManager.test.swift
Fixes #2316, but not the underlying problem, by not confirming local pushes which fail to be added to the notification center.
The underlying problem is that we cannot attach anything to a notification in the Local Push extension as of iOS 16.4. This is clearly a regression, and it doesn't matter where we write it, it fails to locate it in locations vended by FileManager:
- The temporary directory
- The documents directory
- The shared container for our app group
All of these fail to attach, all in the same way, and all of them:
1. Are able to be read by the process using `Data(contentsOf: …)`
2. Work fine in the Notification Service Extension
This is definitely a regression on Apple's side and frustratingly my radar has gone ignored. Par for the course, I guess.
=> Fix incorrectly confirming a local notification even if it fails

Sources/App/WebView/WebViewController.swift, Sources/Shared/Environment/Constants.swift
Add edge swipe to show sidebar
=> Add edge swipe to show sidebar

Sources/Shared/Notifications/NotificationCommands/NotificationsCommandManager.swift
Fixes #2184 
This will have to be updated with the appropriate version number:
https://github.com/home-assistant/companion.home-assistant/blob/bdb4a2676ab9836c3aee509ef1f05502448ac127/docs/notifications/basic.md?plain=1#L156
=> Fix clear_notification only working with local push

.github/workflows/ci.yml, .github/workflows/distribute.yml, .github/workflows/download_localized_strings.yml, Tests/Shared/ServerManager.test.swift
=> Bump Xcode to 15.0.1

HomeAssistant.xcodeproj/project.pbxproj, Sources/Extensions/Widgets/Actions/WidgetActions.swift, Sources/Extensions/Widgets/Common/WidgetBackground.swift, Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift, Sources/Extensions/Widgets/Common/WidgetContentMargin.swift, Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
Fix padding and background issues.
=> Fix widget UI for iOS 17

fastlane/Fastfile
=> Download core strings to iOS proj

fastlane/Fastfile
=> Avoid Core strings upload back to lokalise

Sources/Shared/Environment/MatterWrapper.swift
=> Small improvement on matter logging

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/ActionConfigurator.swift, Sources/App/Settings/Eureka/YamlSection.swift, Sources/App/Settings/SettingsDetailViewController.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/API/WebSocket/WebSocketMessage.swift, Sources/Shared/Environment/Constants.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
Reorder sections in action configurator and added button to create automation directly from action configurator
=> Improve iOS Actions, facilitate automation creation

.github/workflows/ci.yml, .github/workflows/distribute.yml, .github/workflows/download_localized_strings.yml
Update xcode to 15.2 that will be used to build the app in the github actions. For fixes done in Xcode 15.2 see the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_2-release-notes);
NA
NA
NA
=> feat(ci): use xcode 15.2;

.github/workflows/ci.yml
=> Prevent "Size" running for forks

Sources/App/AppDelegate.swift, Sources/App/Notifications/NotificationManager.swift, Sources/App/Onboarding/API/OnboardingAuthDetails.swift, Sources/App/Onboarding/Screens/OnboardingScanningViewController.swift, Sources/App/Settings/AboutViewController.swift, Sources/App/Settings/DebugSettingsViewController.swift, Sources/App/Settings/Observation/NotificationCategory+Observation.swift, Sources/App/Settings/Sensors/SensorListViewController.swift, Sources/App/Settings/SettingsDetailViewController.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/API/Authentication/AuthenticationRoutes.swift, Sources/Shared/Environment/Environment.swift, Sources/Shared/Settings/SettingsStore.swift
As [lowerCamelCase came to Swift a long time ago](https://www.hackingwithswift.com/swift/3.0/lower-camel-case), this PR is changing the casing in `AppConfiguration`.
=> Lowercase enum `AppConfiguration`

Sources/Shared/Environment/Constants.swift
Change `static var` to `static let` to prevent inadvertent change from somewhere in the codebase.
=> Change `static var` to `static let` in `Version`

Sources/App/Utilities/Permissions.swift
=> General maintenance on Permissions.swift

Sources/App/Utilities/NSURL+QueryDictionary.swift
=> 🧹 Remove unused `queryDictionary`

Sources/App/Settings/Notifications/NotificationRateLimitsAPI.swift, Sources/App/Settings/Notifications/NotificationSoundsViewController.swift, Sources/App/Settings/Observation/NotificationCategory+Observation.swift, Sources/App/Utilities/MenuManager.swift, Sources/App/Utilities/UIColor+CSSRGB.swift, Sources/App/Utilities/Utils.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/API/Authentication/AuthenticationAPI.swift, Sources/Shared/API/Models/WatchComplication.swift, Sources/Shared/API/Webhook/Networking/WebhookManager.swift, Sources/Shared/Common/DiskCache.swift, Sources/Shared/Common/Extensions/NSItemProvider+Additions.swift, Sources/Shared/Common/Extensions/NSMutableAttributedString+Additions.swift, Sources/Shared/Common/Extensions/Realm+Initialization.swift, Sources/Shared/Common/Extensions/String+HA.swift, Sources/Shared/Common/Extensions/Version+HA.swift, Sources/Shared/Common/SiriIntents+ConvenienceInits.swift, Sources/Shared/Notifications/LocalPush/UserDefaultsValueSync.swift, Tests/App/LocalizedStrings.test.swift, Tests/Shared/Webhook/Promise+WebhookJson.test.swift, Tests/Shared/Webhook/WebhookManager.test.swift, Tests/UI/SnapshotHelper.swift
This PR removes the `options` parameters which use the default value.
=> Remove default `options` parameter

Sources/Shared/Environment/Constants.swift
=> Swiftier code for `groupDir` check

Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift, Sources/Extensions/Widgets/Actions/WidgetActions.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift
=> Improvement for actions widget

Sources/App/Settings/DebugSettingsViewController.swift, Sources/App/Settings/SettingsViewController.swift
=> Move thread credentials entry to debugging section

Podfile, Podfile.lock
=> Bump HAKit to 0.4

Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
=> Add vibration when running widget from home screen

Podfile, Podfile.lock
=> Use latest changes from HAKit instead fetching from tag

.github/workflows/ci.yml
A potential fix for https://github.com/home-assistant/iOS/issues/2656
=> Fix `size` job running for forked repos

Sources/Shared/Common/Extensions/String+HA.swift
=> 🧹 Remove unused `String` extension functions

Sources/Shared/Common/Extensions/UIColor+HA.swift
=> 🧹 Remove unused `UIColor`-s

Sources/Shared/Iconic/IconDrawable.swift
=> Avoid registering material design icons font several times

HomeAssistant.xcodeproj/project.pbxproj
=> Add BuildMaterialDesignIconsFont to codegen build phases

Sources/Shared/Iconic/IconDrawable.swift
=> Avoid register material design icons more than once

Podfile, Podfile.lock
=> Upgrade HAKit to 0.4.1 and remove extra StarScream reference

Sources/App/WebView/WebViewController.swift
=> Update barcode flag communicated to frontend

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/BarcodeScanner/Camera/BarcodeScannerCamera.swift, Sources/App/BarcodeScanner/Camera/BarcodeScannerDataModel.swift, Sources/App/BarcodeScanner/Camera/BarcodeScannerView.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/Extensions/UIViewController+Extensions.swift
=> Improvements for barcode scanner

Sources/App/Assist/AssistView.swift
=> Fix Assist animation spacing

Sources/App/Scenes/SettingsSceneDelegate.swift, Sources/App/Settings/Eureka/SettingsButtonRow.swift, Sources/App/Settings/SettingsRootDataSource.swift
=> Remove "Thread" management for macOS

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Assist/WidgetAssist.swift, Sources/Extensions/Widgets/Assist/WidgetAssistView.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve Assist widget UI

README.md
=> Update README.md Xcode version

Podfile
Depending on HAKit PR and tag: https://github.com/home-assistant/HAKit/pull/65
=> Upgrade HAKit to 0.4.2

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/DebugSettingsViewController.swift, Sources/App/Settings/SettingsRootDataSource.swift, Sources/App/Settings/SettingsViewController.swift, Sources/App/Settings/Widgets/WidgetsSettingsView+build.swift, Sources/App/Settings/Widgets/WidgetsSettingsView.swift, Sources/App/Settings/Widgets/WidgetsSettingsViewModel.swift, Sources/Shared/Extensions/View+ConditionalModifier.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add widgets reload button to settings

Sources/App/Settings/SettingsRootDataSource.swift, Sources/Extensions/Widgets/Assist/WidgetAssistView.swift, Sources/Shared/Extensions/UIImage+SharedAssets.swift
=> Fix lock screen widget based on designer feedback

Sources/Extensions/Widgets/Widgets.swift
=> Show Assist widget before other widgets

Sources/Extensions/Watch/Home/WatchHomeViewModel.swift
=> Fix Apple Watch display text for actions

Sources/Shared/API/Models/RealmScene.swift
=> Avoid auto enabling scenes

Sources/App/Resources/WebSocketBridge.js, Sources/App/Utilities/ThemeColors.swift, Sources/App/WebView/WebViewController.swift
Reverts home-assistant/iOS#2757
=> Revert "Use same variable for status bar color as frontend"

Sources/App/Assist/AssistView.swift
=> Improve pipeline picker on mac UI

Sources/App/Assist/AssistView.swift, Sources/App/Assist/AssistViewModel.swift, Sources/App/Assist/Audio/AudioRecorder.swift, Sources/App/Assist/Tests/AssistViewModel.test.swift, Sources/App/Assist/Tests/Mocks/MockAudioRecorder.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve Assist logic to make sure it has the correct sample rate

Sources/App/Assist/Audio/AudioPlayer.swift
=> Fix Assist audio player audio session setup

Sources/App/Assist/AssistView.swift, Sources/App/Assist/AssistViewModel.swift, Sources/App/Assist/Tests/AssistViewModel.test.swift, Sources/App/Assist/Tests/Mocks/MockAssistService.swift, Sources/App/WebView/IncomingURLHandler.swift, Sources/Shared/Intents/AssistInApp/AssistModel.swift
=> Use first server available for Assist when server is not defined

Sources/Shared/Intents/AssistInApp/AssistModel.swift, Sources/Shared/Intents/AssistInApp/AssistRequests.swift, Sources/Shared/Intents/AssistInApp/AssistService.swift
=> Add conversation id to Assist interaction to keep context

Sources/Shared/API/HAAPI.swift, Sources/Shared/API/Responses/ConfigResponse.swift, Sources/Shared/API/Server.swift, Sources/Shared/Intents/AssistInApp/AssistRequests.swift, Sources/Shared/Intents/AssistInApp/AssistService.swift
Integration PR: https://github.com/home-assistant/core/pull/121496#event-13420408451
=> Add device registry id to assist call

Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift, Sources/Shared/Assets/Assets.swift, Sources/Shared/Assets/Colors.xcassets/Background/Contents.json, Sources/Shared/Assets/Colors.xcassets/Background/primaryBackground.colorset/Contents.json, Sources/Shared/Assets/Colors.xcassets/Background/tileBackground.colorset/Contents.json, Sources/Shared/Assets/Colors.xcassets/Border/Contents.json, Sources/Shared/Assets/Colors.xcassets/Border/tileBorder.colorset/Contents.json
=> Update widget UI to align with frontend

Podfile, Podfile.lock
=> Bump Improv 0.0.6

HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme, Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift, Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift
=> Allow 2 items in systemSmall widget + update Apple Watch item style

HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme, Sources/App/Resources/Base.lproj/Intents.intentdefinition, Sources/App/Settings/ActionConfigurator.swift, Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift, Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift, Sources/Extensions/Widgets/Actions/WidgetActions.swift, Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicSizeStyle.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift, Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift, Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift, Sources/Shared/DesignSystem/Constants/Spaces.swift
=> Simplify widgets and small UI tweaks

HomeAssistant.xcodeproj/project.pbxproj, Sources/Extensions/Watch/Home/Mocks/MockWatchHomeViewModel.swift, Sources/Extensions/Watch/Home/WatchHomeView.swift, Sources/Extensions/Watch/Home/WatchHomeViewModel.swift, Sources/Shared/Environment/ConnectivityWrapper.swift, Sources/Shared/Environment/WatchUserDefaults.swift
=> Detect SSID on watch to decide which endpoint to use to run actions

Sources/App/Scenes/SceneManager.swift
=> Fix issue where notification URL closes app right away

Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntentTimelineProvider.swift, Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift, Sources/Extensions/Widgets/Details/WidgetDetails.swift, Sources/Extensions/Widgets/Gauge/WidgetGauge.swift
=> Scout - Remove lock screen widgets force unwrap

Sources/Shared/Environment/DeviceWrapper.swift
=> Use Apple Vision Pro and visionOS instead of iPad as name

Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift
=> Remove unused environment key in WidgetOpenPage

HomeAssistant.xcodeproj/project.pbxproj, Sources/Shared/API/Webhook/Sensors/LocationPermissionSensor.swift, Sources/Shared/Environment/Environment.swift
So you can finally know if that family member is not having their phone tracked correctly because of the current location permission settings and messing up with automations :D
=> Add location permission sensor

Sources/Shared/API/Models/WebhookSensor.swift, Sources/Shared/API/Webhook/Sensors/AppVersionSensor.swift
=> Use entity category "diagnostic" for App Version

Sources/Shared/API/Webhook/Networking/WebhookManager.swift
=> Log event when retrying 503 webhook error

Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift, Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
=> Add scripts widget suggestions and avoid requiring confirmation when running several scripts at once

Sources/App/Utilities/ThemeColors.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/Environment/Constants.swift
=> Use app header color for older HA core versions

Sources/Extensions/AppIntents/Action/PerformAction.swift
=> Fix Action widget haptics

Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntentTimelineProvider.swift, Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift
=> Fix gauge and details widget checked continuation

Sources/App/Resources/en.lproj/Intents.strings
=> Add missing localization keys for AssistInApp intent definition

Sources/Extensions/Widgets/Widgets.swift
=> Fix variable WidgetBundle, fix iOS 15 and 16 widgets

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/WatchCommunicatorService.swift, Sources/Extensions/Watch/Home/WatchHomeCoordinatorView.swift, Sources/Extensions/Watch/Home/WatchHomeCoordinatorViewModel.swift, Sources/Extensions/Watch/Home/WatchHomeView.swift
=> Fix watch empty state and reposition reload button for watchOS 10

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/WatchCommunicatorService.swift, Sources/Extensions/Watch/Assist/WatchAssistView.swift, Sources/Extensions/Watch/Assist/WatchAssistViewModel.swift, Sources/Extensions/Watch/Home/WatchHomeCoordinatorView.swift, Sources/Extensions/Watch/Home/WatchHomeCoordinatorViewModel.swift, Sources/Extensions/Watch/Home/WatchHomeView.swift, Sources/Shared/Watch/InteractiveImmediateMessages.swift
Pending: https://github.com/home-assistant/iOS/pull/2950
=> Add ping/pong to keep iPhone activity while processist Assist from watch

HomeAssistant.xcodeproj/project.pbxproj, Sources/SharedPush/Package.swift, Sources/SharedPush/Sources/NotificationParserLegacy.swift
=> Remove import SharedPush from SPM and import it manually

Sources/Extensions/Watch/Assist/WatchAssistView.swift, Sources/Extensions/Watch/Assist/WatchAssistViewModel.swift
=> Add assist volume control back to watch

.github/workflows/ci.yml, .github/workflows/distribute.yml
=> Update CI to use Xcode 16 instead of 16.1

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Script/Control/ControlScript.swift, Sources/Extensions/Widgets/Script/Control/SFSymbolEntity.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve symbols search and add name to script control widget

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift, Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift, Sources/App/Settings/MagicItem/Add/MagicItemAddView.swift, Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift, Sources/Shared/MagicItem/MagicItem.swift, Sources/Shared/MagicItem/MagicItemProvider.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Watch configuration improvements

Sources/App/Settings/Observation/Action+Observation.swift, Sources/App/WatchCommunicatorService.swift, Sources/Shared/API/WatchHelpers.swift, Sources/Shared/API/Webhook/Sensors/WatchBatterySensor.swift
=> Fix watch sensors sync

Sources/Extensions/Widgets/Scene/Control/ControlScene.swift, Sources/Extensions/Widgets/Scene/Control/ControlScenesValueProvider.swift, Sources/Extensions/Widgets/Script/Control/ControlScript.swift, Sources/Extensions/Widgets/Script/Control/ControlScriptsValueProvider.swift
=> Fix iOS 18 controls notification when run

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/OpenPage/Control/ControlOpenPage.swift, Sources/Extensions/Widgets/OpenPage/Control/ControlOpenPageValueProvider.swift, Sources/Extensions/Widgets/OpenPage/OpenPageAppIntent.swift, Sources/Extensions/Widgets/OpenPage/PageAppEntity.swift, Sources/Extensions/Widgets/Widgets.swift, Sources/Shared/API/WebSocket/HAPanel.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Sources/Shared/Widget/WidgetsKind.swift, Tests/App/Widgets/WidgetsKindTests.swift
=> Add iOS 18 Open Page Control

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Assist/Control/ControlAssist.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Update Control Assist copy

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Assist/AssistAppIntent.swift, Sources/Extensions/Widgets/Scene/SceneAppIntent.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Update text from iOS 18 controls

Sources/App/WebView/IncomingURLHandler.swift, Sources/App/WebView/WebViewController.swift, Sources/App/WebView/WebViewExternalMessageHandler.swift, Sources/Extensions/Widgets/Assist/AssistAppIntent.swift, Sources/Extensions/Widgets/Assist/Control/ControlAssist.swift, Tests/App/WebView/Mocks/MockWebViewController.swift
=> Present Assist UI faster when it comes from app extensions

Podfile, Podfile.lock
=> Update GRDB to avoid intermitent crash

Sources/App/AppEntitiesObserver.swift
=> Avoid updating database in background

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Settings/ActionConfigurator.swift, Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift, Sources/Extensions/Widgets/Common/WidgetBasicViewTintedWrapper.swift
=> Fix tinted widgets in iOS 18

Sources/Extensions/Watch/Home/WatchHomeCoordinatorView.swift, Sources/Extensions/Watch/Home/WatchHomeView.swift
=> Display Assist for older watchOS

Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift, Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift, Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift, Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift, Sources/Extensions/Widgets/Scene/Control/ControlScene.swift, Sources/Extensions/Widgets/Scene/Control/ControlScenesValueProvider.swift, Sources/Extensions/Widgets/Scene/Control/IntentSceneEntity.swift, Sources/Extensions/Widgets/Scene/SceneAppIntent.swift, Sources/Extensions/Widgets/Script/Control/ControlScript.swift, Sources/Extensions/Widgets/Script/Control/ControlScriptsValueProvider.swift, Sources/Extensions/Widgets/Script/WidgetScripts.swift
=> Fix control scene id when calling to activate scene

Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRow.swift
=> Fix Apple Watch text color and dynamic type

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Thread/CredentialsManagement/ThreadCredentialsManagementView.swift, Sources/App/Thread/CredentialsManagement/ThreadCredentialsManagementViewModel.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Sources/Shared/Services/Thread/ThreadClientProtocol.swift, Sources/Shared/Services/ThreadClientService.swift, Tests/App/Thread/CredentialsSharing/SimulatorThreadClientService.swift
=> Add option to delete thread network credential from Apple Keychain

Sources/Extensions/Widgets/Assist/Control/ControlAssistValueProvider.swift
=> Add "Preferred" pipeline to Control Assist

Sources/Extensions/Watch/Assist/WatchAssistView.swift, Sources/Extensions/Watch/Home/WatchHomeCoordinatorView.swift
=> Add double tap watch gesture to launch Assist

Sources/App/Assist/AssistViewModel.swift, Sources/Shared/Common/Extensions/GRDB+Initialization.swift, Tests/App/Assist/AssistViewModel.test.swift
=> Use cached assist pipelines to speed up starting command

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift, Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift, Sources/Extensions/Widgets/OpenPage/Control/ControlOpenPageValueProvider.swift, Sources/Extensions/Widgets/Scene/Control/ControlScenesValueProvider.swift, Sources/Extensions/Widgets/Scene/SceneAppIntent.swift, Sources/Extensions/Widgets/Script/Control/ControlScriptsValueProvider.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Update 'confirmation notification' copy

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift, Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift, Sources/Shared/MagicItem/MagicItemProvider.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Fix scene icons not showing on Apple Watch

HomeAssistant.xcodeproj/project.pbxproj, Sources/Extensions/Widgets/Assist/WidgetAssist.swift, Sources/Extensions/Widgets/Assist/WidgetAssistView.swift, Sources/Extensions/Widgets/Assist/WidgetAssistViewTintedWrapper.swift, Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
=> Fix remaining tinted widgets

Sources/App/WebView/WebViewController.swift
=> Always present controllers in main thread (fix Matter issue)

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/WebViewExternalMessageHandler.swift, Sources/Extensions/Matter/MatterRequestHandler.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve matter over thread error message

Sources/Extensions/Widgets/Switch/ControlSwitchValueProvider.swift
=> Fix copy for iOS18 control switch

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift, Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRow.swift, Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift, Sources/Shared/Common/Extensions/Color+hex.swift, Sources/Shared/MagicItem/MagicItem.swift
=> Fix watch configuration values selection

Sources/App/WebView/WebViewExternalMessageHandler.swift, Sources/Extensions/Matter/MatterRequestHandler.swift, Sources/Shared/Settings/SettingsStore.swift
=> Use extended PAN ID instead of mac extended addres to select thread network

Sources/App/WebView/WebViewExternalMessageHandler.swift
=> Clear thread credentials before comissioning new matter device

Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift
=> Avoid nil icon color in watch config

README.md
Adds the OHF badge to the README
=> Add OHF logo to README

Sources/App/Onboarding/Screens/OnboardingScanningViewController.swift
=> Fix iPad onboarding where "manual address" is not presented

Sources/App/Resources/Base.lproj/Intents.intentdefinition, Sources/App/Resources/Info.plist, Sources/Extensions/Intents/Resources/Info.plist, Sources/Shared/DataWidgetsUpdater.swift
=> Mark some intents as legacy

Podfile, Podfile.lock, Sources/App/Notifications/NotificationManager.swift, Sources/App/WebView/WebViewExternalMessageHandler.swift, Sources/Shared/Notifications/NotificationIdentifier.swift
=> Use in app improv message

Sources/App/WebView/WebViewExternalMessageHandler.swift
=> Respect frontend "start_listening" value when launching Assist

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Onboarding/Screens/Bluetooth/BluetoothPermissionView.swift, Sources/App/Onboarding/Screens/Bluetooth/BluetoothPermissionViewModel.swift, Sources/App/Onboarding/Screens/BluetoothPermissionView.swift, Sources/App/Onboarding/Screens/PermissionRequestView.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/WebViewExternalMessageHandler.swift, Sources/Shared/DesignSystem/Styles/HAButtonStyles.swift, Sources/Shared/Environment/Environment.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Sources/Shared/Settings/SettingsStore.swift
=> Add bluetooth permission screen

Sources/App/Assist/AssistViewModel.swift
=> Fix Assist trigger from lovelace

HomeAssistant.xcodeproj/project.pbxproj, Sources/Extensions/Widgets/ControlRefreshDelay.swift, Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift, Sources/Extensions/Widgets/Switch/ControlSwitchValueProvider.swift
=> Fix iOS controls state

Sources/App/Resources/Info.plist
=> Allow arbitrary load for web content and media

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Scenes/CarPlaySceneDelegate.swift, Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift, Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift, Sources/App/Settings/CarPlay/CarPlayConfig.swift, Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift, Sources/App/Settings/CarPlay/CarPlayConfigurationViewModel.swift, Sources/App/WatchCommunicatorService.swift, Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift, Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessViewModel.swift, Sources/Shared/Common/Extensions/GRDB+Initialization.swift, Sources/Shared/Environment/Environment.swift, Sources/Shared/MagicItem/MagicItem+Migration.swift, Sources/Shared/MagicItem/MagicItemProvider.swift, Sources/Shared/Watch/WatchConfig.swift, Tests/App/MagicItem/MagicItemProviderTests.swift
=> Migrate watch and carplay config when serverID from items is unavailable

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/AppEntitiesObserver.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Cover/ControlCover.swift, Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift, Sources/Extensions/Widgets/Cover/CoverIntent.swift, Sources/Extensions/Widgets/Cover/IntentCoverEntity.swift, Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift, Sources/Extensions/Widgets/Light/LightIntent.swift, Sources/Extensions/Widgets/Switch/ControlSwitchValueProvider.swift, Sources/Extensions/Widgets/Switch/SwitchIntent.swift, Sources/Extensions/Widgets/Widgets.swift, Sources/Shared/Common/Extensions/GRDB+Initialization.swift, Sources/Shared/ControlEntityProvider.swift, Sources/Shared/HAServices.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Sources/Shared/Widget/WidgetsKind.swift, Tests/App/Widgets/WidgetsKindTests.swift
=> Add cover control to iOS

Sources/Extensions/Watch/ExtensionDelegate.swift
=> Remove actions from watch sync context

Sources/Extensions/Widgets/Cover/ControlCover.swift, Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift, Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift, Sources/Shared/ControlEntityProvider.swift
=> Fix cover control state

Sources/App/AppEntitiesObserver.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/CarPlay/Templates/CarPlayPaginatedListTemplate.swift, Sources/CarPlay/Templates/Servers/CarPlayServerListTemplate.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve CarPlay areas load and add option to restart CarPlay

Sources/App/AppEntitiesObserver.swift, Sources/App/Assist/AssistViewModel.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Scenes/CarPlaySceneDelegate.swift, Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift, Sources/App/Settings/CarPlay/CarPlayConfig.swift, Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift, Sources/App/Settings/CarPlay/CarPlayConfigurationViewModel.swift, Sources/App/Settings/DebugSettingsViewController.swift, Sources/App/WatchCommunicatorService.swift, Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift, Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift, Sources/Extensions/Widgets/Assist/Control/ControlAssistValueProvider.swift, Sources/Shared/Common/Extensions/GRDB+Initialization.swift, Sources/Shared/ControlEntityProvider.swift, Sources/Shared/Environment/Environment.swift, Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift, Sources/Shared/MagicItem/MagicItemProvider.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Sources/Shared/Watch/WatchConfig.swift, Tests/App/MagicItem/MagicItemProviderTests.swift
=> Reflect CarPlay config changes in realtime

Sources/App/WebView/WebViewController.swift
=> Make webview inspectable for all builds

Sources/App/Scenes/CarPlaySceneDelegate.swift, Sources/CarPlay/Templates/Servers/CarPlayServerListTemplate.swift, Sources/CarPlay/Templates/Servers/CarPlayServerListViewModel.swift
=> Fixes for CarPlay lag

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/DownloadManager/DownloadManagerView.swift, Sources/App/WebView/DownloadManager/DownloadManagerViewModel.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add download manager for WKWebView

.github/workflows/ci.yml, .github/workflows/distribute.yml, .github/workflows/download_localized_strings.yml, fastlane/Fastfile
=> Update ci.yml - macOS-15 image

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Cover/ControlCover.swift, Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift, Sources/Extensions/Widgets/Script/Control/SFSymbolEntity.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Fix cover control tint color and add option to define icon per state

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift, Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift
=> Add icon specific for light control state

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/AppDelegate.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/WebViewController.swift, Sources/App/WebView/WebViewWindowController.swift, Sources/Shared/API/Authentication/TokenManager.swift, Sources/Shared/API/Models/AppEntitiesModel.swift, Sources/Shared/API/Models/ModelManager.swift, Sources/Shared/Environment/OnboardingStateObservation.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Tests/Shared/ModelManager.test.swift
=> Prevent server deletion and inform user it is unauthenticated

Sources/App/Improv/ImprovDiscoverView.swift, Sources/App/WebView/WebViewExternalBusMessage.swift, Tests/App/WebView/WebViewExternalBusMessageTests.swift
Pending: https://github.com/home-assistant/frontend/pull/22878
=> Notify frontend when improv device setup is done

Sources/App/WebView/DownloadManager/DownloadManagerView.swift
=> Clean up download file on dismissing download manager

Sources/Shared/API/Models/ModelManager.swift
=> Fix entities database sync

Sources/App/WebView/WebViewExternalMessageHandler.swift
=> Only notify frontend known improv devices

Sources/Shared/API/Models/AppEntitiesModel.swift
=> Add extra logging for database updates

Sources/Shared/API/Models/AppEntitiesModel.swift
=> Separate entities model cache per server

Sources/App/ClientEvents/ClientEventTableViewController.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/SettingsDetailViewController.swift, Sources/Shared/API/ConnectionInfo.swift, Sources/Shared/ClientEvents/Model/ClientEvent.swift, Sources/Shared/ClientEvents/Model/ClientEventStore.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Log when user requires internal URL setup

Sources/App/Assist/AssistViewModel.swift
=> Remove code not in use

Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
=> Avoid executing watch item twice

Sources/Shared/API/Models/AppEntitiesModel.swift
=> Reduce database updates throttling

Sources/App/Resources/Info.plist
Reverts home-assistant/iOS#3124
=> Revert "Allow arbitrary load for web content and media"

HomeAssistant.xcodeproj/project.pbxproj, Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift, Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift, Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift, Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntent.swift, Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift, Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift, Sources/Extensions/Widgets/Actions/WidgetActionsProvider.swift, Sources/Extensions/Widgets/Common/WidgetBasicButtonView.swift, Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicSensorView.swift, Sources/Extensions/Widgets/Common/WidgetBasicSizeStyle.swift, Sources/Extensions/Widgets/Common/WidgetFamilySizes.swift, Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift, Tests/App/Widgets/WidgetsSizeTests.swift
=> Bump number of widgets allowed and refactor UI creation logic

HomeAssistant.xcodeproj/project.pbxproj, Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift, Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift, Sources/Extensions/Widgets/Common/TileCardStyleModifier.swift, Sources/Extensions/Widgets/Common/WidgetBasicButtonView.swift, Sources/Extensions/Widgets/Common/WidgetBasicSensorView.swift, Sources/Extensions/Widgets/Common/WidgetFamilySizes.swift, Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift
=> Fix widget corner radius when size style compressed and preview them as tile card

Sources/App/Settings/ClientEventsLogView/ClientEventsLogView.swift, Sources/App/Settings/ClientEventsLogView/ClientEventsLogViewModel.swift
=> Observe client events changes in event log view

Sources/Shared/API/ServerManager.swift
=> Replace precondition by log for deleted servers check

Sources/Shared/API/Models/AppEntitiesModel.swift, Sources/Shared/API/Models/ModelManager.swift, Sources/Shared/Environment/Environment.swift
=> Prevent AppEntities auto init in extensions

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/WebViewController.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add "no url available" warning

HomeAssistant.xcodeproj/project.pbxproj, Sources/Shared/API/Webhook/Sensors/AudioOutputSensor.swift, Sources/Shared/Environment/Environment.swift
=> iOS Audio output sensor

Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
Change placeholder because it is confusing (see [32](https://github.com/home-assistant/iOS/issues/3213)).
I chose question marks since that is also used in the gauge widget
=> Change sensor widget placeholder

Sources/Shared/Common/Extensions/GRDB+Initialization.swift
=> Remove fatal error for GRDB database creation

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/SettingsDetailViewController.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add missing strings for mac native features only mode

Sources/App/ZoneManager/ZoneManagerProcessor.swift, Tests/App/ZoneManager/ZoneManagerProcessor.test.swift
=> Increase "location too old" time

Sources/CarPlay/Templates/HAEntity+CarPlay.swift, Sources/Shared/API/Models/ModelManager.swift, Sources/Shared/Domain/Domain.swift
=> Add person domain to states subscription

Podfile, Podfile.lock, Sources/App/Scenes/CarPlaySceneDelegate.swift, Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift, Sources/CarPlay/Templates/Areas/CarPlayAreasZonesTemplate.swift
=> Improv CarPlay states subscription

Sources/App/Resources/Base.lproj/Intents.intentdefinition
=> Fix legacy intents names

Sources/App/Scenes/CarPlaySceneDelegate.swift, Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift, Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift, Sources/CarPlay/Templates/Areas/CarPlayAreasZonesTemplate.swift, Sources/CarPlay/Templates/CarPlayTemplateProvider.swift, Sources/CarPlay/Templates/Domains/CarPlayDomainsListTemplate.swift, Sources/CarPlay/Templates/Entities/CarPlayEntitiesListTemplate.swift, Sources/CarPlay/Templates/Entities/CarPlayEntitiesListViewModel.swift, Sources/CarPlay/Templates/Entities/CarPlayEntityListItem.swift, Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift, Sources/CarPlay/Templates/Servers/CarPlayServerListTemplate.swift, Sources/Shared/MagicItem/MagicItemProvider.swift
=> Subscribe to quick access entity changes on top of the standard CarPlay subscription

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Assist/AssistTypingIndicator.swift, Sources/App/Assist/AssistView.swift, Sources/App/Assist/AssistViewModel.swift, Sources/Extensions/Watch/Assist/Views/ChatBubbleView.swift, Sources/Shared/Assist/AssistChatItem.swift
=> Add Assist typing indicator

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/SettingsDetailViewController.swift, Sources/App/Settings/SettingsRootDataSource.swift, Sources/App/Settings/SettingsViewController.swift, Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Rename actions to "(Legacy) iOS Actions" and move it down on the list

Sources/App/Onboarding/Screens/OnboardingManualURLViewController.swift
=> Remove URL path in onboarding to avoid wrong redirect after login

Sources/Shared/Common/Extensions/GRDB+Initialization.swift
=> Improv database table creation logs

Sources/Shared/API/Models/AppEntitiesModel.swift
=> Add missing CarPlay-used domains to app database sync

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Onboarding/API/OnboardingAuth.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/Connection/ConnectionURLViewController.swift, Sources/App/WebView/NoActiveURLView.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/DesignSystem/Styles/HAButtonStyles.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
https://github.com/user-attachments/assets/3dcdf423-c302-4e30-84e3-433bba03bfa9
=> Warning when internal URL requires more permissions before it can be used

HomeAssistant.xcodeproj/project.pbxproj, Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift, Sources/Extensions/AppIntents/Sensor/IntentSensorsAppEntity.swift, Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift, Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsConfig.swift, Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift, Sources/Extensions/Widgets/Cover/IntentCoverEntity.swift, Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift, Sources/Extensions/Widgets/Light/IntentLightEntity.swift, Sources/Extensions/Widgets/Scene/Control/IntentSceneEntity.swift, Sources/Extensions/Widgets/Switch/ControlSwitchValueProvider.swift, Sources/Extensions/Widgets/Switch/IntentSwitchEntity.swift, Sources/Shared/API/Models/AppEntitiesModel.swift, Sources/Shared/ControlEntityProvider.swift
=> Add more domains for sensors widget

Sources/Shared/Panels/PanelsUpdater.swift
=> Delete old panels from database

Sources/App/Resources/Base.lproj/Intents.intentdefinition, Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
=> Update Open page widget items limit and sensor capitalized state

Sources/Shared/Environment/AppConstants.swift
=> Reduce minimum core version for subscription with filter

Sources/Shared/API/Models/AppEntitiesModel.swift, Sources/Shared/Environment/PeriodicAppEntitiesModelUpdater.swift
=> Improve logs for entities model updater

Sources/App/WebView/DownloadManager/DownloadManagerView.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Auto open share sheet after download

Sources/App/Scenes/SceneManager.swift
Fix for https://github.com/home-assistant/iOS/issues/3305#issuecomment-2592926013
=> Only activate scene when not active already

Sources/CarPlay/Templates/HAEntity+CarPlay.swift, Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift, Sources/Shared/API/HAAPI.swift
=> Fix "button" domain not working on CarPlay quick access

Sources/App/Utilities/Permissions.swift
=> Request location permission "always" during onboarding

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/AppleWatch/ComplicationListViewController.swift, Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntent.swift, Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntent.swift, Sources/Extensions/Widgets/Details/WidgetDetails.swift, Sources/Extensions/Widgets/Gauge/WidgetGauge.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add warning that templating only works for admin users

Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift, Sources/App/Settings/CarPlay/CarPlayConfigurationViewModel.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Sources/Shared/Watch/WatchConfig.swift
=> Simplify watch and carplay database insert

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/ConnectionErrorDetailsView.swift, Sources/Shared/DesignSystem/Components/ExternalLinkButton.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Remove option to report error in github and add option to copy error to clipboard

Sources/App/WebView/IncomingURLHandler.swift, Sources/Extensions/Widgets/Custom/WidgetCustom.swift, Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift
- Adds action for the widget empty state to open the app in the widget creation screen
- Auto select widget in case none is selected and there is at least one created
=> Widget builder fixes

Sources/App/WebView/WebViewController.swift
=> Move some code from WebViewController to separate functions and improve "moveToServer"

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Scenes/WebViewSceneDelegate.swift, Sources/App/Settings/SettingsRootDataSource.swift, Sources/App/Settings/SettingsViewController.swift, Sources/Shared/Environment/AppDatabaseUpdater.swift, Sources/Shared/Environment/Environment.swift, Sources/Shared/Panels/PanelsUpdater.swift
=> Improve database update and remove periodic timer

Podfile, Podfile.lock
=> Update GRDB to 7.0

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/ConnectionErrorDetailsView.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/DesignSystem/Components/CloseButton.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve connection error screen

Sources/App/WebView/WebViewExternalMessageHandler.swift
=> Remove bluetooth permission screen for Mac Catalyst

Sources/Extensions/Widgets/Common/WidgetBasicView.swift, Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift, Sources/Extensions/Widgets/Custom/WidgetCustom.swift, Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift
=> Avoid delay when reacting to widget require confirmation

Sources/Extensions/Widgets/Common/WidgetBasicSizeStyle.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift
=> Improvements for widget UI (Icon size and opacity)

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/Gestures/GesturesSetupView.swift, Sources/App/Settings/Gestures/GesturesSetupViewModel.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/AppGesture.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Sources/Shared/Settings/SettingsStore.swift
=> Making "shake to debug" gesture configurable and optional 

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift, Sources/Extensions/Widgets/Custom/WidgetCustom.swift, Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add last update date and beta option to show entity state in widget

Sources/App/WebView/WebViewController.swift
=> Open debug screen by default when shaking device

Sources/Extensions/Widgets/Common/WidgetBasicButtonView.swift, Sources/Extensions/Widgets/Common/WidgetBasicView.swift, Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift, Sources/Extensions/Widgets/Custom/AppIntents/CustomWidgetToggleAppIntent.swift, Sources/Extensions/Widgets/Custom/AppIntents/ResetAllCustomWidgetConfirmationAppIntent.swift, Sources/Extensions/Widgets/Custom/AppIntents/UpdateWidgetItemConfirmationStateAppIntent.swift, Sources/Extensions/Widgets/Custom/WidgetCustom.swift, Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift, Sources/Shared/Widget/CustomWidget.swift
=> Add visual feedback for widget progress

Sources/App/Utilities/Permissions.swift
=> Remove location permission method lagging the UI

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Custom/AppIntents/CustomWidgetActivateAppIntent.swift, Sources/Extensions/Widgets/Custom/AppIntents/CustomWidgetPressButtonAppIntent.swift, Sources/Extensions/Widgets/Custom/AppIntents/CustomWidgetToggleAppIntent.swift, Sources/Extensions/Widgets/Custom/WidgetCustom.swift, Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift, Sources/Shared/Notifications/NotificationIdentifier.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve custom widget execution error handling and UI

Sources/App/WebView/NoActiveURLView.swift, Sources/App/WebView/WebViewController.swift, Sources/App/WebView/WebViewExternalMessageHandler.swift, Sources/App/WebView/WebViewWindowController.swift, Sources/Shared/Extensions/UIViewController+Extensions.swift, Tests/App/WebView/Mocks/MockWebViewController.swift, Tests/App/WebView/WebViewExternalMessageHandlerTests.swift
=> Avoid holding overlayed controller reference in webviewcontroller

Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
=> Hide last updated datetime from widget when in empty state

Sources/App/Assist/AssistView.swift, Sources/App/Assist/AssistViewModel.swift
=> Add shortcut to trigger assist mic button on mac

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/Settings/DebugView.swift, Sources/App/Settings/Gestures/AppleLikeListTopRowHeader.swift, Sources/App/Settings/Gestures/GesturesSetupView.swift, Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift, Sources/App/Settings/Widgets/Builder/WidgetBuilderView.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add BETA label to custom widgets

Sources/App/WebView/ConnectionErrorDetailsView.swift
=> Fix error message for cloud user connection error screen

Sources/App/Resources/en.lproj/Localizable.strings
=> Fix copy typo for widgets

Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift, Sources/Extensions/Widgets/Sensor/WidgetSensors.swift, Sources/Shared/Domain/Domain.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add fallback icon to sensors widget

Sources/App/Onboarding/Screens/OnboardingManualURLViewController.swift
=> Remove trailing slash from manual inputed server URL in onboarding

Sources/App/Scenes/WebViewSceneDelegate.swift, Sources/App/Settings/SettingsViewController.swift, Sources/Shared/Environment/AppDatabaseUpdater.swift, Sources/Shared/Panels/PanelsUpdater.swift
=> Revert changes for database updater and move call to scene become active

Sources/Shared/Environment/ConnectivityWrapper.swift
=> Migrate from CNCopySupportedInternet to NEHotspotNetwork

Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift, Sources/Shared/MagicItem/MagicItem.swift
=> Change "Require confirmation" default value to false

Sources/Shared/Environment/ConnectivityWrapper.swift
Reverts home-assistant/iOS#3438
=> Revert "Migrate from CNCopySupportedInternet to NEHotspotNetwork"

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Settings/ClientEventsLogView/ClientEventsLogView.swift, Sources/App/Settings/MagicItem/Add/MagicItemAddView.swift, Sources/App/Settings/MagicItem/Add/MagicItemAddViewModel.swift, Sources/App/Settings/MagicItem/EntityPicker.swift, Sources/Shared/DesignSystem/Components/PillView.swift, Sources/Shared/DesignSystem/Components/ServersPickerPillList.swift
=> Add servers as filter to pick entities in the EntityPicker flow

Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/ConnectionErrorDetailsView.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add settings entry point from connection error screen

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift
=> Add missing localization for custom widgets picker

Sources/App/WebView/ConnectionErrorDetailsView.swift
=> Fix navigation view for connection error screen on macOS

Sources/Shared/Environment/AppDatabaseUpdater.swift, Sources/Shared/Panels/PanelsUpdater.swift
=> Cancel updater requests when app goes to background

Sources/Shared/Intents/AppIntent/AssistInApp/AssistModel.swift, Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift
=> Add fallback case enum for Assist events preventing crashes on newer event types

Sources/App/Settings/SettingsViewController.swift
Reverts home-assistant/iOS#3462
=> Revert "Remove custom widgets from release build"

Sources/App/Assist/AssistViewModel.swift, Sources/App/WatchCommunicatorService.swift, Sources/Shared/Intents/AppIntent/AssistInApp/AssistModel.swift, Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift, Sources/Shared/Intents/AssistIntentHandler.swift
=> Add support to Assist stream response

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Assist/AssistViewModel.swift, Sources/App/Assist/Audio/AudioPlayer.swift, Sources/Shared/Common/Extensions/Float+HA.swift, Sources/Shared/Intents/AppIntent/AssistInApp/AssistModel.swift, Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift, Tests/App/Assist/AssistViewModel.test.swift, Tests/App/Assist/Mocks/MockAssistService.swift, Tests/App/Extensions/OptionalsDefaultTests.swift
=> Assist continuous conversation listen directly after response if volume is 0

Sources/App/Settings/Gestures/GesturesSetupView.swift
=> Use navigation picker style for gestures picker to expand UI possibilities for more actions

Sources/App/WebView/WebViewController.swift, Sources/App/WebView/WebViewExternalMessageHandler.swift, Tests/App/WebView/Mocks/MockWebViewController.swift, Tests/App/WebView/WebViewExternalMessageHandlerTests.swift
=> Fix barcode scanner notify popup issue where it dismissed the scanner

Sources/Shared/API/HAAPI.swift
=> Remove extra service data from call service request

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Widgets/Controls/Light/LightIntent.swift, Sources/Extensions/Widgets/Controls/Switch/SwitchIntent.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve copy for control intents

Sources/App/AppDelegate.swift, Sources/App/Scenes/WebViewSceneDelegate.swift
=> Remove unecessary model updates from app lifecycle

Sources/App/Onboarding/Screens/OnboardingServersList/OnboardingServersListView.swift, Sources/App/Onboarding/Screens/OnboardingWelcomeView.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve onboarding copy

Sources/App/Onboarding/Screens/OnboardingServersList/OnboardingServersListView.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve manual URL input onboarding UI and copy

Sources/CarPlay/Templates/Entities/CarPlayEntityListItem.swift, Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift, Sources/Shared/MagicItem/MagicItem.swift
=> Use override information in CarPlay when specified in configuration

Sources/App/Onboarding/Screens/OnboardingPermissions/LocationPermissionView.swift, Sources/App/Onboarding/Screens/OnboardingPermissions/OnboardingPermissionsNavigationView.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/Shared/API/ConnectionInfo.swift, Sources/Shared/Environment/Environment.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve onboarding location access copy and internal URL handling

Sources/App/Resources/en.lproj/Localizable.strings, Sources/Extensions/Watch/Home/WatchHomeView.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Improve copy for watch loading screen button

HomeAssistant.xcodeproj/project.pbxproj, Sources/Shared/API/Models/AppEntitiesModel.swift, Sources/Shared/API/Models/WebhookSensor.swift, Sources/Shared/Database/DatabaseTables.swift, Sources/Shared/Database/Tables/HAppEntityTable.swift, Sources/Shared/Domain/DeviceClass.swift, Sources/Shared/HAAppEntity.swift, Tests/App/MagicItem/MagicItemProviderTests.swift
=> Add device class to app database

Sources/CarPlay/Templates/Entities/CarPlayEntityListItem.swift, Sources/Shared/Common/Extensions/String+HA.swift, Sources/Shared/HAEntity+CarPlay.swift
=> Fix CarPlay garage icon

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/WebView/WebViewController+WKScriptMessageHandler.swift, Sources/App/WebView/WebViewController.swift, Tests/App/WebView/WKUserContentControllerMessageTests.swift
=> Avoid WKUserContentController messages if app is in background

Sources/CarPlay/Templates/Entities/CarPlayEntityListItem.swift
=> Avoid showing states for entities which state is not useful in CarPlay

Sources/Shared/Common/SiriIntents+ConvenienceInits.swift
=> Update legacy open page logic to use new deeplink

Sources/App/WebView/WebViewController+WKScriptMessageHandler.swift
=> Organize WKScriptMessageHandler message handling

Sources/App/Scenes/BasicSceneDelegate.swift
=> Remove max window size for settings on mac

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/WebView/DownloadManager/ActivityViewController.swift, Sources/App/WebView/DownloadManager/DownloadManagerView.swift
=> Trucate download file name in the middle

Sources/App/Onboarding/Screens/OnboardingServersList/OnboardingServersListViewModel.swift
=> Reduce number of auto enabled sensors

Sources/App/Onboarding/Screens/OnboardingPermissions/LocationPermissionView.swift, Sources/App/Onboarding/Screens/OnboardingPermissions/LocationPermissionViewModel.swift, Sources/App/Onboarding/Screens/OnboardingServersList/OnboardingServersListView.swift, Sources/App/Onboarding/Screens/OnboardingWelcomeView.swift
=> UI adjustments for onboarding flow

HomeAssistant.xcodeproj/project.pbxproj, Sources/Shared/Assets/Assets.swift, Sources/Shared/Assets/Colors.xcassets/Contents.json, Sources/Shared/Assets/Colors.xcassets/trackColor.colorset/Contents.json, Sources/Shared/DesignSystem/Components/HAProgressView.swift
https://github.com/user-attachments/assets/c91d6f67-c533-40a2-b68c-b5a467ba344a
=> Add HAProgressView, ProgressView styled for Home Assistant

Sources/App/WebView/DownloadManager/DownloadManagerView.swift, Sources/Shared/DesignSystem/Components/HAProgressView.swift
=> Use new HAProgressView for DownloadManager

Sources/App/BarcodeScanner/Camera/BarcodeScannerCamera.swift
=> Use virtual devices to guarantee correct camera focus on barcode scanner

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/WebView/CustomRefreshControl.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/DesignSystem/Components/HAProgressView.swift
=> Use HAProgressView instead of standard as refresh control

Sources/App/WebView/WebViewController.swift, Sources/App/WebView/WebViewExternalBusMessage.swift, Sources/Shared/Environment/AppConstants.swift, Tests/App/WebView/WebViewExternalBusMessageTests.swift
Thanks to https://github.com/home-assistant/frontend/pull/25516 🥳
=> Navigate through frontend whenever possible before asking webview to load URL

Sources/App/Scenes/WebViewSceneDelegate.swift, Sources/Shared/API/HAAPI.swift
=> Update user's location when opening the App

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Notifications/NotificationManager.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/IncomingURLHandler.swift, Sources/App/WebView/WebViewController.swift, Sources/App/WebView/WebViewWindowController.swift, Sources/Extensions/Widgets/HAAppEntityAppIntentEntity.swift, Sources/Extensions/Widgets/OpenEntity/ControlOpenEntity/ControlOpenEntity.swift, Sources/Extensions/Widgets/OpenEntity/ControlOpenEntity/ControlOpenEntityValueProvider.swift, Sources/Extensions/Widgets/OpenEntity/ControlOpenEntity/OpenEntityAppIntent.swift, Sources/Extensions/Widgets/Widgets.swift, Sources/Shared/ControlEntityProvider.swift, Sources/Shared/Environment/AppConstants.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Sources/Shared/Widget/WidgetsKind.swift, Tests/App/Widgets/WidgetsKindTests.swift
=> Add AppIntent to open entity more-info dialog

Sources/App/Onboarding/API/OnboardingAuth.swift
=> Make local push opt-in

Sources/App/AppDelegate.swift, Sources/Shared/Settings/SettingsStore.swift
=> Reset local push and set it as opt-in

Sources/App/AppDelegate.swift
=> Add local push migration logs

Sources/App/Onboarding/Screens/OnboardingServersList/OnboardingServersListView.swift, Sources/App/Onboarding/Screens/OnboardingServersList/OnboardingServersListViewModel.swift, Sources/App/Resources/en.lproj/Localizable.strings, Sources/Shared/DesignSystem/Components/HAProgressView.swift, Sources/Shared/Resources/Swiftgen/Strings.swift, Tests/App/Onboarding/ServersList/OnboardingServersListViewModelTests.swift
=> Visual improvements for Home Assistant invitation onboarding

Sources/App/Scenes/WebViewSceneDelegate.swift
=> Replace location submit logic when scene active

Sources/Shared/Iconic/IconDrawable.swift
=> Add assertion for IconDrawable methods

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Settings/Connection/ConnectionSettingsViewController.swift, Sources/Shared/API/ConnectionInfo.swift, Tests/App/AppConstants.test.swift, Tests/Shared/ConnectionInfo.test.swift
=> Use cloud > remote > internal URLs in that order for invitation link

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/WebView/Views/ServerPickerView.swift, Sources/App/WebView/Views/WebViewEmptyStateView.swift, Sources/App/WebView/WebViewController.swift
=> Add server picker to the "disconnected" screen

Sources/App/Onboarding/Steps/Servers/OnboardingServersListView.swift
=> Fix onboarding UI for HA invitation link

HomeAssistant.xcodeproj/project.pbxproj
=> Import SharePush package through local package list instead of manual reference

Sources/App/WebView/Extensions/WebViewControllerProtocol+Implementation.swift, Sources/App/WebView/WebViewController.swift
=> Display empty state if connection is not estabilished with frontend after 4 seconds from a webview navigation

HomeAssistant.xcodeproj/project.pbxproj
=> Add missing SharedPush framework for watch - fix crash

HomeAssistant.xcodeproj/project.pbxproj, Sources/App/Resources/en.lproj/Localizable.strings, Sources/App/WebView/Views/StatusBarViews/WebViewControllerButtons.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/Resources/Swiftgen/Strings.swift
=> Add mac navigation arrows

Sources/App/WebView/WebViewExternalMessageHandler.swift
=> Add flag "downloadFileSupported" to external bus config

Sources/App/Onboarding/Steps/Permissions/OnboardingPermissions/OnboardingPermissionsNavigationView.swift, Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift, Sources/App/Settings/MagicItem/Add/MagicItemAddView.swift, Sources/App/Settings/SettingsRootDataSource.swift, Sources/App/WebView/WebViewController.swift, Sources/Shared/DesignSystem/Components/AppleLikeBottomSheet.swift, Sources/Shared/DesignSystem/Components/CloseButton.swift
=> UI fixes for iOS 26

Sources/App/Resources/Assets.xcassets/accentColor.colorset/Contents.json, Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift
=> Use accent color for icon in CarPlay configuration

Sources/Extensions/Widgets/Controls/Cover/ControlCover.swift
=> Fix cover control label
