home-assistant/iOS

HomeAssistant/HAAPI.swift

[Apple's default is 60 seconds](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest) and the current 3 seconds doesn't seem like enough time for many internet connections.
I'm hoping this will help with #33

Increase HTTP timeoutIntervalForRequest to 10 seconds

---

Podfile.lock

This is the earliest version that builds with XCode 9 and doesn't have the breaking changes of v3.x

Update Realm to 2.8.3

---

APNSAttachmentService/NotificationService.swift

Mostly fixes #39 
In the case where we're a camera notification and there is no custom attachment URL, we know that we have a URL like
> \(baseURL)/api/camera_proxy/\(entityId)?api_password=\(apiPassword)
which doesn't have a suffix for UNNotificationAttachment to auto-detect the content-type.
In this case we should default to "jpeg" since that's what "camera_proxy" seems to normally return. This saves users from having to manually specify the content-type for camera stream thumbnails in most cases.

Default camera category attachments to jpeg content-type

---

HomeAssistant/Views/AboutViewController.swift
HomeAssistant/Views/HomeAssistantLogoView.xib

From https://github.com/home-assistant/home-assistant-iOS/issues/25#issuecomment-313744559 
> On that note- should probably make the iOS app version number more obvious
Otherwise it's buried in Storage settings or by looking at the App Store
Asking for review since I haven't edited a xib file in years.

Add the version string to the about page

---

APNSAttachmentService/NotificationService.swift
HomeAssistant/AppDelegate.swift
NotificationContentExtension/NotificationViewController.swift

This makes it so device builds can work if the developer isn't in Robbie's team (UTQFCBPQRF).
According to https://developer.apple.com/library/content/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html#//apple_ref/doc/uid/TP30000897-CH204-SW1 defining `keychain-access-groups` in the entitlements means "apps would add new keychain items to that access group by default". We already have "$(AppIdentifierPrefix)io.robbie.HomeAssistant" in all of the entitlements files so it seems like specifying the accessGroup isn't necessary.
@robbiet480 Can you test that your saved login is still accessible if you upgrade to a build with this PR? According to the docs it should work and this will make it easier for other to contribute to the app.

Don't hardcode AppIdentifierPrefix in Keychain constructor

---

HomeAssistant/Views/WebViewController.swift

When the webview's scrollview is allowed to bounce it sometimes scrolls
to its bouncing margins when the user intended to scroll the page loaded
in the web view. This results in ugly and annoying effects such as the
top bar of the web interface scrolling down from the status bar. Since
the loaded page has a bouncing effect anyway it seems natural to disable
this capability.

Disable webview bouncing

---

HomeAssistant/HAAPI.swift

So first off, this is completely untested.
Starting Home Assistant 0.65, we've added service data validation to the device tracker see service. Once released, we realized that iOS app sends invalid data. This will remove those keys.
I saw one more reference to the device tracker see service, but it seems that any other app can define the data that is being sent (is that secure?)
https://github.com/home-assistant/home-assistant-iOS/blob/545ed6a7d48b70f9cb7de4c889dddfe65f48a486/HomeAssistant/AppDelegate.swift#L231

Remove invalid service data for device_tracker.see

---

HomeAssistant/Classes/RegionManager.swift

A few Event Log message typos have been bothering me, here's some fixes.

Fixing log message typos

---

HomeAssistant/Classes/RegionManager.swift

**Experimental test**
Don't immediately notify HA when exiting an iBeacon region, but still update the zone object.
Ideally will avoid iBeacon exits from non-home zones triggering a state change to `home` and falling back to GPS.

iBeacon exit attempt v2

---

CONTRIBUTING.md
README.md

We've had a couple of people (#532 and #476) contribute translations here. The current guides did not contain any information suggesting this was not the correct thing to do. Added a couple of lines to both `README.md` and `CONTRIBUTING.md` to help.

Add translation details to readme.md and contributing.md

---

Tools/BuildMaterialDesignIconsFont.sh

This fixes executing `Tools/BuildMaterialDesignIconsFont.sh` at least on 10.15.5 (Catalina). There are a few underlying issues here:
1. The `fontname.py` dependency was updated to require python3+, so we need to both install python3 variants and execute using the python3 binary.
2. The `MaterialDesign-Webfont` dependency, for versions ≥5.0, no longer parses successfully with the version of SwiftGen in Iconic.
```bash
$ Vendor/SwiftGen/build/swiftgen/bin/swiftgen icons /…/materialdesignicons-webfont-v5.0.45.ttf
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen
import UIKit
// No icon found
```
I started down the rabbit hole for 2 but couldn't find an obvious path forward -- it seems like SwiftGen has dropped icon-font building support, so updating to the …

Fix building MaterialDesignIcons

---

HomeAssistant/Views/NotificationCategoryConfigurator.swift
HomeAssistant/Views/Settings/NotificationSettingsViewController.swift

When saving a notification action or category right now, tapping the row representing the just-created one will not open the edit screen for that existing one but instead opens as if it is creating a new one again.
This fixes the issue by making sure the ButtonRowWithPresent keeps a reference to the action it wants to open, and allows that action to be changed to point to a different one once it's created.

Fix editing a just-created notification category or action

---

HomeAssistant/Classes/Action.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/ActionConfigurator.swift
Shared/API/HAAPI.swift
Shared/Resources/Swiftgen/Strings.swift

When editing an Action, the configurator currently shows a preview of what the button will look like, but it doesn't give any direct indication what the _event_ it fires will look like. One must look to the documentation to get an idea how to structure the automation.
This adds a preview of the yaml one would need to write as an automation, using the same flow as sending it to the server to avoid it getting stale over time, and allows the user to share it out via copying, email, etc.
This pulls together the different 'previews' in the configurator to be executed together:
- the title of the view controller (which wasn't updated live before)
- the actual preview button the user can tap
- this new yaml trigger preview
This also removes the toolbar with the help button from the action edit …

Action Configurator: Example Trigger Preview

---

HomeAssistant/Views/Settings/NotificationSettingsViewController.swift

The categories are loaded with a distinct sort:
```swift
let categories = Current.realm().objects(NotificationCategory.self).sorted(byKeyPath: "Identifier")
```
Since reordering makes no sense in this list, this removes the ability to reorder from the section.
The act of reordering actually deletes the category being dragged because Eureka does a `remove`+`insert` rather than `move`, and `NotificationSettingsViewController` will [silently delete the category](https://github.com/home-assistant/iOS/blob/d43b5ddd211c3cf98ed1b518cee92ada21b095b7/HomeAssistant/Views/Settings/NotificationSettingsViewController.swift#L372-L389) it sees the remove for.
This does occasionally crash, I think depending upon the lifecycle of the invalidated Realm object and whether something access it from the …

Fix deleting notification categories when reordering them

---

HomeAssistant/Views/WebViewController.swift

I offer this change to start a conversation about how the safe area insets are handled in the webview that powers the frontend on iOS. I think that allowing the webview to handle the safe area on its own will work out better in the long run, and solves a lot of real frustrations that I have been running into.
Judging by the [original commit](https://github.com/home-assistant/iOS/commit/414c5be29a4b3673ebc507e62012de72f547fdb3) being long enough in the past, and early enough in the iPhone X world, I'm hoping that the safe area problem can be handled a little cleaner.
There are a few cases that I believe are significantly improved with this change:
1. Landscape handling (practically anywhere)
On devices with safe area insets for the device bezel, e.g. the iPhone 11 I'm taking these …

Remove `WKWebView` safeAreaInsets resetting

---

Shared/API/HAAPI.swift

When updating sensors, any failed updates due to `not_registered` are registered and then the update is retried. However, if any of the sensors which failed to update _also_ fail to register, the fact that this is an error condition is silently ignored, and without backoff another update is immediately attempted.
You can reproduce this by e.g. hard-coding a sensor that will never successfully register into the sensors list, like so:
```swift
let sensor = WebhookSensor(name: "moo", uniqueID: "arfarf34")
sensor.State = nil
allSensors.append(sensor)
```
Fixes #599.
Refs home-assistant/core#36455.

Fix infinite loop when updating sensors

---

Shared/API/HAAPI.swift

When trying to register only a given list of sensors, all of the Promise are created immediately, and the webhook response promises invoke immediately. In the end, all the filtering was doing was preventing waiting for all of them, thus making the DoS in an infinite loop even stronger!
This modifies the filter check to do the filter before creating the promises, and thus only will register a sensor that is failing.
Refs #599.
Refs home-assistant/core#36455.

Fix always registering every sensor upon not_registered

---

Shared/Common/Extensions/Realm+Initialization.swift

Although it's easier for development (I've done it before) it's better to leave this `false` so you don't accidentally lose user data, e.g. Realm describes this property as:
> delete the Realm if migration is needed; this is useful under development since the data model might change often
The reason upgrading to Realm 5.x from the current version was losing the database is that Realm is doing an internal migration to a newer version of its database, and it is using this setting to decide whether to migrate or wipe.
Tested this out by upgrading a few times, with and without the flag. The migration doesn't have issues preserving the data.

Don't tell Realm to delete the database on migration

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Views/WebViewController.swift
Shared/API/HAAPI.swift
Shared/API/Requests/MobileAppRegistrationRequest.swift
Shared/API/Requests/MobileAppUpdateRegistrationRequest.swift
Shared/Authentication/TokenManager.swift
Shared/Common/Structs/Environment.swift
Shared/Settings/SettingsStore.swift

Add handling for when the access token is removed.
- Shows the onboarding flow for manual sign outs and invalid-token sign outs. Made the onboarding flow more resilient to being called more than once (see below).
- Shows the onboarding flow on startup if the user hasn't completed onboarding _or_ if we know they should see it.
- Adds some logging so we can easily see why a particular user was logged out.
Adds handling for when the integration is removed from the server.
- In this case, we re-register from scratch. This now includes the stable value `identifierForVendor` as an integration-specific unique ID, not based on any user input, which helps avoid any duplicate integrations from showing up.
- Tested a few scenarios: with an existing integration, made sure that adding device_id didn't …

Handle logouts and invalidated tokens

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Views/WebViewController.swift
Shared/Settings/SettingsStore.swift

Adds some state-aware handling to treat the While In Use permission level as valid for doing manual location updates. This also makes it so that failing to get a location doesn't result in not updating other sensors during a manual update request.

Manual location update for While In Use permission

---

HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/Onboarding/ManualSetupViewController.swift
Shared/Resources/Swiftgen/Strings.swift

If you, for example, enter `127.0.0.1:8123` without the scheme, this ends up being a quasi-valid URL that will fail later down the pipeline.
If you enter something that's even closer to valid like `http:127.0.0.1:8123` it will crash trying to make a WebSocket connection, since that API strictly looks for http/https schemes.
This prompts the user if they forget a scheme, trims any whitespace, and makes sure that the thing passes an is-URL heuristic (by initting a URL with the string) before allowing the user to continue.

Validate manually-entered URL strings

---

Shared/API/HAAPI.swift
Shared/API/Requests/MobileAppUpdateRegistrationRequest.swift

After retesting my expectations from #612 I discovered that the update registration call doesn't like having the  device_id included, so this removes it. Re-tested to make sure the same example registration cases still function as expected.
Shows up like:
> [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: extra keys not allowed @ data['device_id']. Got '4B94573F-FFA2-4D83-BEA4-CE5BE184DBF3'

Don't send device_id when updating registration

---

HomeAssistant/AppDelegate.swift

The controller was added to two UINavigationControllers and the second one lost the presentation race, so the former ended up being empty.
Fixes #526.

Fix opening notification settings deeplink

---

HomeAssistant/Resources/Base.lproj/Onboarding.storyboard
Shared/Resources/Swiftgen/Strings.swift

Update the placeholder for the manual onboarding box with `homeassistant.local:8123`. I believe all other instances are covering on the fly by localise? Also did a comment because why not

Replace hassio.local placeholders

---

HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/SettingsDetailViewController.swift
HomeAssistant/Views/WebViewController.swift
Shared/Resources/Swiftgen/Strings.swift
Shared/Settings/SettingsStore.swift

Scales the contents of the web view to a multiple of normal. This behaves similar to the +/- button in Safari.
This is different than both:
- `document.body.style.zoom` (which causes the header to be positioned wrong)
- `-webkit-text-size-adjust` (which causes items to be badly centered)
The setting looks like:
The difference between e.g. 150%, 100% and 85% looks like:

Page Zoom setting

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Utilities/Permissions.swift
HomeAssistant/Views/Onboarding/PermissionsViewController.swift
HomeAssistant/Views/WebViewController.swift
Shared/API/HAAPI.swift
Shared/Settings/SettingsStore.swift
WatchAppExtension/ExtensionDelegate.swift

You are allowed to request remote notification permission distinct from visual notification permission. This resolves logout->login requiring another app launch to register the push ID with the sever as well.

Always register for remote notifications

---

HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/SettingsViewController.swift
Shared/Resources/Swiftgen/Strings.swift

This now attempts to revoke the token, with a bail-out mechanism if it's taking too long, and triggers onboarding once everything is reset.

Make Reset also trigger onboarding

---

HomeAssistant/Views/WebViewController.swift

Showing an action sheet with just 1 item produces some AutoLayout issues, and we need the popover source to exist sooner forr the other ones.

Fix JavaScript alerts on iPad

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/SettingsDetailViewController.swift
HomeAssistant/Views/WebViewController.swift
Shared/Resources/Swiftgen/Strings.swift
Shared/Settings/SettingsStore.swift

Saves state (right now just the page the WebView is displaying) when backgrounding the app normally. This handles a few weird edge cases like saving a dashboard which ends up being deleted since the last restoration.
This also fixes a bug where the WebView was being told to load the frontend twice on startup, which explains some of the logo flashing that occurs on a clean start.
Adds an option (defaulting to on) to settings which controls whether state is restored.
[What it feels like](https://imgur.com/a/fQmXLSs). I'd like to (at some point) keep the snapshotted UI up until the WebView finishes loading, too.

State Restoration: Save Last Page

---

HomeAssistant/Views/SettingsDetailViewController.swift

Tells the system to hide the today widget when it's empty, or to show it when there's content.
Fixes #304 (a different way).

Today Widget: Empty Handling

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
HomeAssistant/AppDelegate.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Utilities/UIApplication+BackgroundTask.swift
HomeAssistant/Views/SettingsDetailViewController.swift
HomeAssistant/Views/WebViewController.swift
Shared/API/HAAPI.swift
Shared/Common/Structs/Environment.swift
Shared/Location/CLLocationManager+OneShotLocation.swift
Shared/Location/LocationTrigger.swift
Shared/Location/OneShotLocationManager.swift
Shared/Networking/BackgroundTask.swift
Shared/Resources/Swiftgen/Strings.swift
Shared/Settings/SettingsStore.swift
SharedTests/AuthorizationTests.swift
SharedTests/BackgroundTask.test.swift
SharedTests/CLLocationManager+OneShotLocationTests.swift

- Adds a thin wrapper around the old logic, which allows users to swap between the two, reducing the scariness of this PR.
- Wraps manual location updating in the same background task logic as background ones.
- Adds background time remaining (when available) as a part of the background task logic, so we can pipe that into the location updating logic, too.
This new logic is focused around: how many updates can we get and how much accuracy can we hit if we give Location Services a few more seconds to feed us location data? I've plugged in some random guesses at how long we're willing to tolerate these things.
Indications are that iOS is willing to toss us things like 2500m accuracy in some situations, which is a heck of a lot of drift for a background fetch update. We're being given an …

New One Shot Location Logic

---

Shared/API/HAAPI.swift

Refs #612. This was trying to register on every possible error. A better solution would be to look for specific error responses, but these all come through as 200's from the API calls even if the request fails.

Don't re-register when update has a network error

---

HomeAssistant/Views/WebViewController.swift

Refs #631 which fixed the confirm-less variant of this presentation. Like that alert, showing an action sheet in the middle of the screen where cancel is tapping anywhere outside is a bit confusing, and it didn't work to begin with -- it didn't like trying to have a sourceRect of the entire screen.
Fixes #582.

Fix another JavaScript alert issue on iPad

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Utilities/PermissionStatusRow.swift
HomeAssistant/Views/SettingsDetailViewController.swift
Shared/Resources/Swiftgen/Strings.swift

This adds a Background Refresh status row and adds disabling like:
- Zone enter/exit: when location isn't always
- Background fetch: when location isn't always or background refresh is off
- Sig loc change: when location isn't always
- Push notification: when location isn't always

Settings Permissions: Add Background Refresh

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Views/Onboarding/ConnectInstanceViewController.swift
HomeAssistant/Views/WebViewController.swift
Shared/API/HAAPI.swift

Moves the connect logic from the WebViewController to the AppDelegate, allowing us to trigger the Connect flow in more cases. This still doesn't invoke a location update on cold or warm launches.
Refs #552 which asks for better Zone updates. There's definitely cases where we don't update (we're in the background, and continue to be in the background, while getting location updates), but this should help, too.

Update sensors and other information on warm-launch

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/NotificationContentExtension.xcscheme
NotificationContentExtension/Camera.swift
NotificationContentExtension/TestNotifications/camera_notification.apns

- Adjusts the constraints on the preview image view while it vends so it isn't stretched. Fixes #513 / #167.
- Adds a sample .apns which can be used to trigger a Camera notification more easily.
Looking through the server code, it looks like we can also grab an HLS stream, which is what the frontend is using for previewing the camera. Refs #596. Created a ticket remember this as #649.

Notifications: Camera Aspect Ratio

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Resources/WebSocketBridge.js
HomeAssistant/Utilities/ThemeColors.swift
HomeAssistant/Views/WebViewController.swift
Shared/Common/Extensions/UIColor+HA.swift

`window.hassConnection` is `undefined` when the `.js` is initially injected, so none of the registrations were working. This adds what is effectively a runloop wait (it is available 0ms later, it's really just an ordering thing) to make sure the connection exists.
Fixes #557, fixes #645 
This now uses JavaScript to pull the underlying css variable for the particular theme colors, which should be a less fragile method to try and get it -- rather than parsing the actual CSS itself. We only care about the currently-active values, so we don't need to parse any other ones.
This is likely to break in the future and waits on home-assistant/frontend#4220 to correctly notify us when the change occurs.
Tries to set the right status bar text color based on the brightness of the given background …

Handle and persist theme color

---

HomeAssistant/Views/WebViewController.swift

If the WebView failed to load in the past, and we've successfully connected to the API (which we now do on both cold and warm starts since #648), trigger a reload for the case that it failed to load entirely. Mostly just adds the case that a nil url is valid cause to reload.

Reconnect WebView on a warm start if it failed to load

---

HomeAssistant/Resources/WebSocketBridge.js
HomeAssistant/Views/WebViewController.swift

Similar to #653 which did this for a completely-unloaded state, I also found I could get the frontend to think it initially failed to connect, which we can detect in some cases too.

Retry "Unable to connect" frontend error automatically

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/Settings/Sensors/SensorListViewController.swift
Shared/Resources/Swiftgen/Strings.swift
Shared/Settings/SettingsStore.swift

Updates sensors at a regular time interval while the app is in the foreground. Likely useful for e.g. wall tablets.
Fixes #644. Fixes #499. At least to the best of our abilities; if the app is not running, it cannot update outside of being woken up by e.g. background fetch or push notifications.
(Options in non-debug don't include 2 or 5 seconds.)

Sensor Settings: Periodic Update

---

HomeAssistant/Views/Settings/Sensors/SensorListViewController.swift
Shared/Common/Extensions/UIImage+Icons.swift

Uses the actual value for picking which icon to use, and also corrects what is likely an MDI change where `-` is now always `_` in icon names.

Sensor Settings: fix icon loading

---

HomeAssistant/Views/NotificationCategoryConfigurator.swift

Currently the help link in the notification category configurator does nothing from a user's perspective (it does actually fire a log entry). 
Replace log entry with link to actionable notifications part of the docs. Ditched the log as none of the other help links seem to use them.
Fixes #434

Fix Notifications Help Link

---

Shared/API/Models/WebhookSensor.swift

Add a space between the sensor value and the unit in the sensor settings pages. Fixes #660

Add space between sensor value and unit

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Views/WebViewController.swift

Changing the Window color affected the loading look of the WebView because its background wasn't being set because the WebView didn't exist yet. This moves the styling to later in the initialization (so it can style it) and removes the background color from the Window.

Fix window background color on iOS 13+

---

Shared/Common/Structs/Environment.swift

This codepath needs to maintain a strong reference to the CMPedometer, or else it deallocates which tears down the Promise prematurely, resulting in the sensors not being created/sent.

Fix Pedometer being deallocated during query

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Views/WebViewController.swift

This handles the various ways that we could launch:
- state restoration doesn't fire on notifications since the system knows it shouldn't
- launching from cold uses a Promise to wait (since it's launched well before WebViewController exists)
- launching  from warm goes through the same Promise but happens instantly
- handles one fun edge case of: start the app, get logged out due to deactivated token, open a notification with a url, finish onboarding -- this will correctly open the URL.
Fixes #250 -- use a URL like `/lovelace-name-here/0` to open a page as if you navigated to it normally.

Handle relative URLs in notifications to open in-app

---

.github/ISSUE_TEMPLATE/bug_report.md

Seems like a good idea when people open bug reports to ask whether they're using the "In-Development Updating" option.

Add In-Development Updating to issue template

---

HomeAssistant/Views/WebViewController.swift
Shared/Authentication/TokenManager.swift

Refs #592. I believe the issue is that the referenced module in the frontend is refreshing the token itself, and that's causing our expiration logic to be incorrect -- we think we have a valid token, but it's actually been replaced.
We do eventually recover when one of our own network requests yields an invalid token response, but that's _after_ we've already told the WebView about the token we believed was valid. The frontend will then retry in 10 seconds, but not before considering the token we provided as an invalid login attempt and throwing a log.
This also resolves some threading issues with the cache wrapping refresh token, whose goal was to avoid issuing more than one request at once. Since the WebView callbacks were happening on the on the main queue, and the Alamofire responses …

Fix authentication delay when WebView forces a token refresh

---

Shared/API/Webhook/Sensors/WebhookSensor+Activity.swift
Shared/API/Webhook/Sensors/WebhookSensor+Pedometer.swift
Shared/Common/Structs/Environment.swift
SharedTests/WebhookSensor/WebhookSensor+Activity.test.swift
SharedTests/WebhookSensor/WebhookSensor+Pedometer.test.swift

When refactoring this, I noted but forgot that SettingStore was checking this authorization status on behalf of the sensor code. This pulls it into the sensors so they can avoid causing a permission prompt.

Fix motion sensors not checking authorization status

---

HomeAssistant/Views/AboutViewController.swift
HomeAssistant/Views/NotificationCategoryConfigurator.swift
HomeAssistant/Views/SettingsDetailViewController.swift
HomeAssistant/Views/WatchComplicationConfigurator.swift
HomeAssistant/Views/WebViewController.swift

This changes the UI links to target <http://companion.home-assistant.io/app/ios/**> from where they are redirected by Netlify. This means we can quickly fix any links that become dead without the need to go through review with Apple. Currently this only deals with UI links, could expand this to cover all web resources used during run time.
Counterpart PR on the companion docs repo for the redirects: home-assistant/companion.home-assistant#248

Change UI links to target companion.home-assistant.io

---

HomeAssistant/Classes/RegionManager.swift
Shared/API/HAAPI.swift
Shared/API/Models/WebhookUpdateLocation.swift

This is gated by the 'Use In-Development Updating' flag as well.
Fixes #661 but I'd like people to validate it in the beta before we totally switch everything over.
Refs #404 - as this no longer forces the location to be the centroid of the region when entering.

Use more accurate location when entering and exiting regions

---

HomeAssistant/Classes/ZoneManager/ZoneManager.swift
HomeAssistantTests/ZoneManager/ZoneManager.test.swift

Although the old region management did allow tracking, but didn't observe them, this instead doesn't do anything special about them.

ZoneManager: Don't Region Monitor Untracked Zones

---

HomeAssistant/Classes/ZoneManager/ZoneManagerIgnoreReason.swift
HomeAssistant/Classes/ZoneManager/ZoneManagerProcessor.swift
HomeAssistantTests/ZoneManager/ZoneManagerProcessor.test.swift

Resolves forcing a round of location updates due to stale location data being available on startup, matching behavior.

ZoneManager: Ignore Old Location Updates

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Classes/ZoneManager/ZoneManager.swift
HomeAssistant/Classes/ZoneManager/ZoneManagerProcessor.swift
HomeAssistantTests/ZoneManager/ZoneManager.test.swift
Shared/ClientEvents/Model/ClientEventStore.swift
Shared/Common/Extensions/Realm+Initialization.swift

Instead of needing to wire up locations that are mutating zones into the manager, this makes the manager observe for any changes and sync them as a result.
One tough thing here: Realm, for some unbelievable reason, notifies about changes in the transaction that is mutating them. This means that anything which is observing the changes and may perform its own write in response needs to make sure it doesn't start a new write transaction, which also unbelievably crashes.

ZoneManager: Directly observe Realm for syncing

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/AppDelegate.swift
HomeAssistant/Classes/NotificationAction.swift
HomeAssistant/Classes/NotificationCategory.swift
HomeAssistant/Notifications/HomeAssistantAPI+Notifications.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Utilities/Notifications.swift
HomeAssistant/Views/ActionConfigurator.swift
HomeAssistant/Views/NotificationActionConfigurator.swift
HomeAssistant/Views/NotificationCategoryConfigurator.swift
HomeAssistant/Views/YamlSection.swift
Shared/API/HAAPI.swift
Shared/Resources/Swiftgen/Strings.swift

- Added `categoryName` to the contents of the event for activating a notification.
- Makes the acceptable case of categories both uppercase and lowercase. Refs #329.
- Copy/paste of an example service call for a category named TEST, which demonstrates per-action URLs:
```yaml
service: notify.mobile_app_#name_here
data:
push:
category: TEST
action_data:
url: "/lovelace/dashboard"
url:
- "_": "http://example.com/fallback"
- "THING": "http://example.com/url"
- "OTHER": "http://example.com/url"
```
Fixes #643.

Actionable Notifications: Per-Action URL, example YAML

---

HomeAssistant/Views/Settings/NotificationSettingsViewController.swift

Although the underlying models were not duplicated (because of primary key), they were always inserted which gave the visual impression that they were duplicated. Fixes #317.

Fix importing notification categories showing duplicates

---

Shared/API/HAAPI.swift

Instead of specifying 10 seconds as a timeout (which is 1/6th the default), allow the default to be inherited. This should improve situations where e.g. a very high-data-required API call during onboarding fails and doesn't allow the user to progress.
Fixes #580.

Increase network connections' timeout duration

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Classes/RegionManager.swift
HomeAssistant/Classes/ZoneManager/ZoneManager.swift
HomeAssistant/Views/SettingsDetailViewController.swift

Swaps between RegionManager and ZoneManager live. Both aren't over-retained, so hooray!

ZoneManager: Handle In-Dev Preference Toggle

---

Shared/API/MJPEGStreamer.swift

When we experience an error in the HLS or MJPEG streaming paths introduced in 2020.3, we continue down until we run out of available ways to play the camera. In this situation, we are receiving the error about the expired token _long_ before we've even gone to fetch a refresh token.
Surface bug: the completion handler is being invoked when we don't expect it to, and new error handling is making it error out when it would silently fail before.
So why exactly is the completion handler being invoked here? We haven't finished retrying it. The completion handler for the request in Alamofire is run on an `OperationQueue` which remains suspended until the network request finishes. So when you call…
```swift
dataRequest.response(completionHandler: …)
```
…the block parameter `completionHandler` …

Fix MJPEG streaming errorring when token is expired

---

Shared/API/HAAPI.swift

We know the version at this point in Onboarding, which makes it a lot more reliable to do this.
Fixes #721.

Fix compatibility with <0.104 by filtering out device_id

---

Shared/API/Webhook/Sensors/ConnectivitySensor.swift
Shared/Common/Structs/Environment.swift
SharedTests/Sensors/ConnectivitySensor.test.swift

Fixes #731. I mistook the old codepaths to have collapsed single-SIM devices into one sensor; instead, it isn't pre-multiple-SIM devices that get collapsed, it's just iOS 10/11.
This is my first ever somewhat-legitimate use of a `Dictionary<Optional<T>, *>`.

Fix sim_1 vs. cellular_provider on pre-multiple-SIM devices

---

Shared/Settings/SettingsStore.swift

Prepend integration unique ID for non-Release builds.
Fixes #723.

Prevent Beta from taking over Release integrations

---

Shared/API/Webhook/Sensors/StorageSensor.swift
SharedTests/Sensors/StorageSensor.test.swift

Sets the numerator for the percentage as the opportunistic space value, rather than the pre-purgable-data available space. Fixes #736.

Storage Sensor: More system-like % available

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Utilities/WatchHelpers.swift
HomeAssistant/Views/Settings/Sensors/SensorListViewController.swift
Shared/API/HAAPI.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
Shared/API/Webhook/Request&Response/WebhookResponseUpdateSensors.swift
Shared/Common/Structs/Environment.swift
SharedTests/Webhook/WebhookResponseUpdateSensors.test.swift

- Make WebhookManager & SensorContainer a singleton in Environment. The system really does not like the background session identifiers being reused, which happens during login as HomeAssistantAPI instances are created and destroyed.
- Adds a mutex around the state handling coming back from URLSession delegate methods and enqueueing. This doesn't seem to be a problem, but better safe than sorry.
Fixes #759.

Fix WebhookManager issue during login

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/AppDelegate.swift
HomeAssistantUITests/ZeroLatitude.gpx
Shared/Common/Structs/Environment.swift
Shared/Location/CLLocationManager+OneShotLocation.swift
SharedTests/CLLocationManager+OneShotLocationTests.swift

This requires locations we're considering as updates to:
- Not have a longitude or latitude of exactly 0. I'm not sure why this is happening, and it almost certainly is not something we're doing (I can't find any reason why it would be) but at least we can detect it. Fixes #684.
- Not have an accuracy that exceeds 1500m or be older than 600s. Refs #298. These are numbers that can be tuned in the future, too.
The tradeoff here is that we may be disregarding poor location information when entering and exiting monitored regions. We may need to write some compensating "zone enters/exits are not location-based" logic if this proves to be the case.
This also bumps up our requested accuracy level from 200m to "Best." I'm guessing in practice there may be no difference in the poor results iOS …

Add quality thresholds to location results

---

HomeAssistant/Views/Settings/ConnectionSettingsViewController.swift

Not providing the context causes an intentional crash, since we want to avoid accidentally sending unencrypted Webhook traffic.

Fix crash when changing connection settings in beta

---

Shared/Common/Structs/Environment.swift

The default values are 10 logs at 600 seconds each with a max file size of 1.5mb, so depending on how active the app is, anything that happened earlier in the day is gone. This extends our maximum logging size from 15mb to 30mb and a much longer duration of time.
Limits are about doubled for TestFlight builds.

Extend local logging from ~1.5 hours to ~3 days

---

Shared/API/Webhook/Request&Response/WebhookManager.swift
SharedTests/Webhook/WebhookManager.test.swift

iOS 14 is sending `urlSessionDidFinishEvents` without the paired `handleEventsForBackgroundURLSession` to start it, which means we're trying to `.leave()` a group we did not `.enter()` which causes DispatchGroup to assert.

Fix background crash on iOS 14 beta in our beta

---

Shared/API/Webhook/Request&Response/Promise+RetryNetworking.swift
Shared/Networking/ConnectionInfo.swift

UIAlertController doesn't want to be called off the main thread, and I did not intend for this retry behavior to jump to the global queue.

Fix off-main-queue crash during invalid connection in beta

---

HomeAssistant/AppDelegate.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
SharedTests/Webhook/WebhookManager.test.swift

Feels like every time I touch a background URL session I fall into this same trap. From the [Apple docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html):
> Because only one process can use a background session at a time, you need to create a different background session for the containing app and each of its app extensions. (Each background session should have a unique identifier.) It’s recommended that your containing app only use a background session that was created by one of its extensions when the app is launched in the background to handle events for that extension. If you need to perform other network-related tasks in your containing app, create different URL sessions for them.
What this means is that we need to …

Fix extension network requests having issues in beta

---

HomeAssistant/Classes/ZoneManager/ZoneManager.swift
HomeAssistant/ClientEvents/ViewControllers/ClientEventPayloadViewController.swift
HomeAssistant/ClientEvents/ViewControllers/ClientEventTableViewController.swift
HomeAssistant/Resources/Scenes.swift
HomeAssistant/Resources/Segues.swift
HomeAssistant/Views/SettingsViewController.swift
HomeAssistantTests/ZoneManager/ZoneManager.test.swift
Shared/Authentication/TokenManager.swift
Shared/ClientEvents/Model/ClientEventStore.swift
Shared/Location/CLLocationManager+OneShotLocation.swift
swiftgen.yml

- Stops logging the rare REST API calls that we do, aka getting the config.
- Adds a share/action button to the JSON detail screen.
- Adds some extra information to some events, removes some from others.
- Adds a search bar to the event log. Refs #395.
- (Likely) fixes a crash on iOS 14. Please verify! Refs #733.
- Switches to using SwiftGen for the storyboard interactions.

Event Log improvements

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Utilities/UIApplication+BackgroundTask.swift
Shared/API/HAAPI.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
Shared/Networking/BackgroundTask.swift
Shared/Networking/ProcessInfo+BackgroundTask.swift

I have a few theories about #777:
1. The system isn't bothering to execute the background request because we've exhausted the background allotment that it wants for us. This is [somewhat documented (descriptively)](https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background?language=objc):
> When the system resumes or relaunches your app, it uses a rate limiter to prevent abuse of background downloads. When your app starts a new download task while in the background, the task doesn't begin until the delay expires. The delay increases each time the system resumes or relaunches your app.
If this is what's happening, this fix won't do anything; the real fix will be to try to send ephemerally and drop to using a background request if that fails …

Wrap webhook networking in background tasks

---

HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/Settings/Sensors/SensorDetailViewController.swift
HomeAssistant/Views/Settings/Sensors/SensorListViewController.swift
Shared/API/HAAPI.swift
Shared/API/Models/Components/Zone.swift
Shared/API/Models/WebhookSensor.swift
Shared/API/Webhook/Sensors/GeocoderSensor.swift
Shared/Common/Extensions/Realm+Initialization.swift
Shared/Location/RealmZone.swift
Shared/Resources/Swiftgen/Strings.swift
SharedTests/Sensors/GeocoderSensor.test.swift

- Adds a method for declaring settings per-sensor
- Adds a setting to the Geocoded Location sensor to replace the state value with the best-match Zone name for that location. Fixes #347.
- Adds a `Zones` attribute to the Geocoded Location sensor which are the Zones that the location is inside of in the order of consideration of the state choice. This particular one ignores the setting.

Per-sensor settings; use Zones for Geocoded Location

---

HomeAssistant/ClientEvents/ViewControllers/ClientEventTableViewController.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
Shared/Resources/Swiftgen/Strings.swift

Fixes #786 by allowing interaction with the view while searching.

Fix client event log filtering in beta, add clear confirmation

---

Shared/API/Webhook/Sensors/BatterySensor.swift
SharedTests/Sensors/BatterySensor.test.swift

Pulls out the battery icon math into a switch statement. There's only a few buckets and I feel like this is easier to read.

Fix battery  icon at 19%

---

Shared/API/HAAPI.swift
Shared/API/Webhook/Request&Response/Promise+WebhookJson.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
Shared/Networking/BackgroundTask.swift

- Handles status code 400 which we were silently treating as successful. This ties to the "invalid JSON" that we've seen in server logs but don't know what's triggering it.
- Ups the logging to match debug builds; these don't leave the device and oh boy they are more useful this way. Now that the logs don't have very small limits this shouldn't be too bad.
- Lowers the logging level for background tasks. We still are logging it to disk, but we can change that too.

Handle webhook error status, add more detailed logging

---

APNSAttachmentService/NotificationService.swift
Shared/API/HAAPI.swift

- Removes `attachment` key requirement to show the automatic camera attachment image.
- Moves image downloads to the temporary directory, cleans out the old folder that contained them.
This is unlikely to explain very much file system space and iOS doesn't clear our temporary files very often, but this should at least make it more inspectable when that is taking up disk space.

Show camera image in notifications without `attachment`, clean up temporary files

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Classes/ZoneManager/ZoneManager.swift
HomeAssistant/Classes/ZoneManager/ZoneManagerRegionFilter.swift
HomeAssistant/Views/SettingsDetailViewController.swift
HomeAssistantTests/ZoneManager/ZoneManager.test.swift
HomeAssistantTests/ZoneManager/ZoneManagerProcessor.test.swift
HomeAssistantTests/ZoneManager/ZoneManagerRegionFilter.test.swift
Shared/API/Models/LocationHistory.swift
Shared/API/Models/WebhookUpdateLocation.swift
Shared/ClientEvents/Model/ClientEventStore.swift
Shared/Location/RealmZone.swift

Even without increasing the monitored regions in #785 we can still exceed the number of monitored region which causes a few fun things:
1. We try to add a new monitored region every single time we syncs zones, which produces an error from CL and bad logs
2. Depending on the order of execution, we may stop monitoring e.g. the home zone when we're next to it!
We want to focus on the monitored regions which can do the most for us, so we need to make sure we only monitor those that are most relevant.

Prefer monitoring closer regions over further

---

HomeAssistant/Classes/Action.swift
HomeAssistant/Utilities/SearchPushRow.swift
HomeAssistant/Views/ActionConfigurator.swift
HomeAssistant/Views/SettingsDetailViewController.swift

- Fixes keyboard overlapping icons when searching icons. Fixes #795.
- Fixes translucency of navigation bar when searching icons. Fixes #794.
- Fixes incorrect sort location (both initial and if drag/dropped before closing screen) of new actions. Fixes #796.
- Fixes initial value of text behaving like entered value instead of a placeholder. Refs half of #422.
- Fixes editing a just-created action (like #603 did for notification categories & actions).

Fix a few action editing rough edges

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Utilities/Bonjour.swift
HomeAssistant/Utilities/OpenInChromeController.swift
HomeAssistant/Utilities/Utils.swift
HomeAssistant/Views/AboutViewController.swift
HomeAssistant/Views/Onboarding/AuthenticationViewController.swift
HomeAssistant/Views/WebViewController.swift
Shared/API/HAAPI.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
Shared/Common/Structs/Constants.swift
Shared/Resources/Swiftgen/SharedPlist.swift
swiftgen.yml

- Uses SwiftGen to generate Shared Info.plist dictionary accessors, wraps them in Constants and uses them for version/build numbers.
- Generates and uses a User-Agent string in the API class and uses that within Webhooks, uses the same everywhere else.
- Avoids issuing a REST API call for config every time we load it from webhooks, since creating the Promise also issues the network request.
- Combines the Ephemeral and Non-Background sessions in WebhookManager; they're the same now, no reason to keep 'em separate.
Fixes #806.

Use the same User-Agent in Webhooks as elsewhere

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/AppDelegate.swift
Shared/API/Models/ModelManager.swift
SharedTests/ModelManager.test.swift

Removes old location sucess/failure and other client event logs after a not-so-cautiously-decided 256 hours (~10 days).
Refs #797 but does nothing to address whatever mysterious disk usage creep is happening there.

Clean up old database entries on disk on startup

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Views/Onboarding/ConnectInstanceViewController.swift

When the app is deleted, but the keychain values (webhook, auth token) persist, our state looks like:
1. The API, WebhookManager, etc., are all alive and well, talking to the server.
1. The UI shows the onboarding flow.
This is because we control whether onboarding should be displayed based on a UserDefaults entry for whether they've finished it, which is less likely than the keychain to persist across installs. What happens next is:
1. A webhook update is sent, since we're launching
1. If the webhook already existed, it's updated. If it did not, using the auth token that is still around, we re-register and create a new integration.
1. The user finishes onboarding, which creates a _new_ auth token, and registers a new integration.
If the integration that was still around in the keychain …

Handle deleting and reinstalling the app better

---

HomeAssistant/Classes/ZoneManager/ZoneManagerIgnoreReason.swift
HomeAssistant/Classes/ZoneManager/ZoneManagerProcessor.swift
HomeAssistantTests/ZoneManager/ZoneManagerProcessor.test.swift

This is only an issue for zones <100m, and is a logic issue following adding additional monitored regions for smaller zones. Since we are now giving 3 regions to smaller zones, we can't expect a direct "inside region = inside zone" relationship; you can be in 1 of the regions and outside the others but still be in the zone.
What this means is that a user can enter one of the wrapping regions, have their location (albeit outside the zone) updated from there and then when they enter one of the overlapping regions the app chooses not to update the location since it believes they are already inside the zone.
This fixes the issue by not caring if the user is in a zone or not when deciding whether to update location.

Allow "redundant" zone events to trigger location updates

---

HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/ActionConfigurator.swift
HomeAssistant/Views/RealmSection.swift
HomeAssistant/Views/SettingsDetailViewController.swift
Shared/API/Models/Action.swift
Shared/API/Models/RealmScene.swift
Shared/Common/Extensions/UIImage+Icons.swift
Shared/Resources/Swiftgen/Strings.swift

Add configure row underneath each Scene, which exposes:
- Colors of scene actions, which are the only fields not synced down.
- Add to Siri button.
- An example trigger to watch the service call for the scene.
Also updates the appearance of regular actions to include their icon and text.

Allow customizing Scene Actions

---

HomeAssistant/Views/ActionConfigurator.swift
Shared/API/Models/Action.swift

Fixes #422. This aims to create background colors that are:
1. Any hue (e.g. red, green, blue)
2. Saturation between 50% and 100% (avoiding super gray colors)
3. Brightness between 25% and 75% (avoiding blacks and whites)
It'll then set both the text and icon color to the same pairing we use for calculating whether to use a light or dark status bar color, sticking to white or black.
Examples:

Generate more compatible random colors for Actions

---

HomeAssistant/ClientEvents/ViewControllers/ClientEventPayloadViewController.swift
Shared/ClientEvents/Model/ClientEvent.swift

Fixes #815. Also avoids Data -> JSON -> Data -> String in favor of Data -> String when showing the payload. Does not apply retroactively.

Avoid unnecessary escaping slashes in Event Logs

---

HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Utilities/Utils.swift
HomeAssistant/Views/Onboarding/WelcomeViewController.swift
Shared/Common/Extensions/Version+HA.swift
Shared/Resources/Swiftgen/Strings.swift

- When the user is logged out and was last running 2020.4.1, shows a warning about why the user got logged out.
- If the user's Realm was created before 2020.1 went out and started sending device_id, shows a warning that the integration will be duplicated.
Fixes #820.
Shows the message until they press continue, so e.g. launching in the background won't cause them to not see it. Once they press continue, it'll show again for any reason.
Learn more goes to [https://companion.home-assistant.io/app/ios/about-the-move](https://companion.home-assistant.io/app/ios/about-the-move), which right now redirects to the blog post.

Show logged out reason for post-team migration

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/Settings/ConnectionSettingsViewController.swift
HomeAssistant/Views/Settings/ConnectionURLViewController.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
Shared/Networking/ConnectionInfo.swift
Shared/Resources/Swiftgen/Strings.swift
SharedTests/Webhook/WebhookManager.test.swift

Moves setting an internal or external URL into a sub-screen which has cancel/save buttons and an explicit lifecycle around whether the save is successful:
- When successful, pops off and shows the new value.
- When unsuccessful for connectivity reasons, allows the user to ignore the error and persist the URL change anyway.
- When unsuccessful because we reject the URL as being Nabu Casa or trying to clear the last one, we tell the user we can't save.
This also allows clearing external if internal is set and fixes trying to reset to external when there is no external.
Improves how and when we persist SSIDs in the list to be the same save button next to internal URL and adds a warning if location permission suggests we won't be able to determine SSID information.
Fixes #717.

Improve Connection Settings saving and editing

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp (Notification).xcscheme
HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
HomeAssistant/Views/SettingsViewController.swift
Shared/API/Models/Action.swift
Shared/API/Models/WatchComplication.swift
WatchAppExtension/ExtensionDelegate.swift
WatchAppExtension/InterfaceController.swift

This happens because the Mappable-variant encode/decode of an Action requires a write transaction (since ObjectMapper's mapping is `inout`, which triggers the "only set in a write transaction" check in Realm) which then, directly, caused a new update to the Watch.
Worked around this by making Action and WatchComplication sync via ImmutableMappable which does not do anything inout, and thus doesn't require a write transaction.
Fixes a few more issues:
- Setting shortcutItems and syncing to watch is now done entirely in the Actions observer; removed from Settings.
- Fix iPhone-not-connected action sending for Scene-synced Actions, which don't have their RLMScene synced to the watch.
- Fixed the empty state label not hiding if actions go in or out of 0-count after initially.

Fix infinite loop syncing Actions to watch

---

WatchAppExtension/InterfaceController.swift

This fixes showing just empty "Label" rows on the Watch because it was never able to configure the rows with their actions.

Fix actions on Watch App not configuring in dev

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Views/Onboarding/OnboardingNavigationViewController.swift
HomeAssistant/Views/WebViewController.swift
Shared/Common/Structs/Constants.swift

Handles the new Dark Mode in the front end -- when it transitions due to media query we need to query the visible colors we use.
Updates the tint color: in dark mode, use the HA blue. In light mode, use a darker version of the same color. Both colors pass WCAG 2.1 Level AA at [4.56](https://contrast-ratio.com/#%230175aa-on-%23f2f2f7) and [5.29](https://contrast-ratio.com/#%2303a9f4-on-%232c2c2e) on the e.g. the navigation bar in each mode.
Tint color change:
Transitioning in the WebView (wish GitHub supported video):
https://www.dropbox.com/s/l9hsw4447qgq9jv/Screen%20Recording%202020-08-03%20at%2023.08.37.mov?dl=0

Dark Mode: Update With Theme, New Tint Color

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/ActionConfigurator.swift
HomeAssistant/Views/InfoLabelRow.swift
HomeAssistant/Views/NotificationActionConfigurator.swift
HomeAssistant/Views/NotificationCategoryConfigurator.swift
HomeAssistant/Views/Settings/ConnectionURLViewController.swift
HomeAssistant/Views/Settings/NFC/NFCListViewController.swift
HomeAssistant/Views/SettingsDetailViewController.swift
Shared/Networking/ConnectionInfo.swift
Shared/Resources/Swiftgen/Strings.swift

- Makes the screens with 'cancel' (configuration things) not pull-down-to-dismissable.
- Adds a note about External URL not being used when Cloud is enabled.

Minor Settings Cleanup

---

HomeAssistant/AppDelegate.swift

Avoiding the problem (by uh–not locking) is only useful for testing.

Hackily work around 14b crash for testing

---

HomeAssistant/Utilities/CLKComplication+Strings.swift
HomeAssistant/Views/SettingsDetailViewController.swift
Shared/API/HAAPI.swift
Shared/API/Models/Action.swift
Shared/API/Models/WatchComplication.swift
Shared/API/Models/WebhookSensor.swift
Shared/API/Webhook/Sensors/GeocoderSensor.swift
Shared/API/Webhook/Sensors/PedometerSensor.swift
Shared/Common/Extensions/UIImage+Icons.swift
Shared/Common/SiriIntents+ConvenienceInits.swift
Shared/Common/Structs/Constants.swift

- Moves the server-based Version checking into a central place.
- Adds a version check around showing the Synced Actions section in Actions.
- Fixes some random import warnings that I just introduced.

Hide Action Syncing when not available

---

HomeAssistant/Classes/ZoneManager/ZoneManagerRegionFilter.swift
Shared/API/Webhook/Request&Response/WebhookResponseLocation.swift
Shared/Location/CLLocationManager+OneShotLocation.swift

We have a good handle on the location errors (and they fire a _lot_) and we don't need to report verbose analytics into Sentry for now. At the current rate this would have logged around 5-10m events/month, which is a lot of noise.

Remove current error and analytics logs

---

APNSAttachmentService/Info.plist
HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Resources/Info.plist
HomeAssistantTests/Info.plist
HomeAssistantUITests/Info.plist
Intents/Info.plist
NotificationContentExtension/Info.plist
Podfile.lock
Shared-watchOS/Info.plist
Shared/API/HAAPI.swift
Shared/Common/Structs/Constants.swift
Shared/Common/Structs/TagManagerProtocol.swift
Shared/Info.plist
SharedTests/Info.plist
TodayWidget/Info.plist
WatchApp/Info.plist
WatchAppExtension/Resources/Info.plist

- Updates to use the `scan_tag` webhook added in home-assistant/core#38721.
- Bumps Realm dependency and build numbers for the next build, since this is the only change for it.

Use Tag webhook, change event

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
Shared/Common/Extensions/Realm+Initialization.swift
Shared/Resources/Swiftgen/Strings.swift

If the database isn't able to be read for some reason, show the error message visually and offer delete/quit options. This should achieve 2 things:
1. We'll know about the root cause without trying to inspect logs.
2. The user will have a mechanism to fix it without deleting the app and reinstalling.

Handle Realm database issues without crashing

---

HomeAssistant.xcodeproj/project.pbxproj

Forward port of 14c92af8a7b81059287ca7233008f1979e61736b which is done in the older Xcode 3.4-compatible project file.
iOS 13 ships with CoreNFC.framework, but iOS 12 (and presumably earlier, where it _is_ declared as available) has the framework on some devices but not others. Big thanks to RobC in Discord for pulling an old iPad Air out of his closet to install a test build for verifying this fixes it.

Fix crash on iOS 12 (by weak-linking CoreNFC)

---

Shared/Networking/ConnectionInfo.swift

If we think we're not on the internal network -- but there is no external URL to reach -- don't reset to external which doesn't exist, just keep using internal. This avoids an infinite loop.
Fixes #894.

Fix crash when switching off internal address can't happen

---

HomeAssistant/Utilities/Permissions.swift

iOS 14 now returns whileInUse even when asking for always, so we need to treat it like success.

Fix onboarding location permission on iOS 14

---

HomeAssistant/Views/SettingsDetailViewController.swift
Shared/API/Models/Action.swift
Shared/API/Models/ModelManager.swift
Shared/API/Models/NotificationCategory.swift
Shared/API/Models/RealmPersistable.swift
Shared/API/Models/RealmScene.swift
Shared/API/Models/RealmZone.swift
SharedTests/ModelManager.test.swift

- Adds to ModelManager a hook to tell a class when models of its type are being deleted, so it can do any secondary cleanup necessary.
- Fixes a few Eureka issues where it would re-query for the cell update of a row as it's being deleted/removed from the table view, which Realm really would prefer you not do.
Fixes #891.

Fix crash deleting Action, delete Scene Action with Scene

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Classes/ZoneManager/ZoneManager.swift
HomeAssistant/Classes/ZoneManager/ZoneManagerEvent.swift
HomeAssistant/Classes/ZoneManager/ZoneManagerProcessor.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistantTests/ZoneManager/ZoneManager.test.swift
HomeAssistantTests/ZoneManager/ZoneManagerProcessor.test.swift
Shared/API/HAAPI.swift
Shared/API/Models/WebhookUpdateLocation.swift
Shared/Common/Structs/Environment.swift
Shared/Location/CLLocationManager+OneShotLocation.swift
Shared/Location/LocationTrigger.swift
Shared/Resources/Swiftgen/Strings.swift
SharedTests/Webhook/WebhookUpdateLocation.test.swift

- Fires `ios.zone_entered` and `ios.zone_exited` directly from monitored regions. This will include keys `"zone" = zone.xyz"` and sometimes `"multi_region_zone_id" = "180"` when the zone (<100m at the time of writing this) require multiple regions. Refs #924 which asked for this.
- Fixes passive beacon zones being sent up as definite zones, rather than GPS producers. I'm not sure when this regressed, this behavior looks the same to my eye to before it was reported broken, but it's an easy fix. Fixes #924.
- Fixes cases where a region monitoring enter event might not produce an in-region location update when the accuracy and position do not show the current location as being in the region. When this occurs, we fudge the accuracy to be larger than given such that the GPS location is inside …

Updates for region monitoring

---

HomeAssistant/AppDelegate.swift

Unless the app is in the foreground, background sessions appear broken -- I see `urlsessiond` logging about the network requests:
```
Task <B22D34D2-4EEB-475E-B233-AC2F67086EC4>.<489> uploadTaskWithRequest: <private> fromFile: <private>
Task <B22D34D2-4EEB-475E-B233-AC2F67086EC4>.<396> is for <<private>>.<<private>>.<396>
Task <B22D34D2-4EEB-475E-B233-AC2F67086EC4>.<489> enqueueing
Task <B22D34D2-4EEB-475E-B233-AC2F67086EC4>.<489> resumeTaskWithIdentifier, props <private>
Task <B22D34D2-4EEB-475E-B233-AC2F67086EC4>.<489> resuming, QOS(0x19)
Task <B22D34D2-4EEB-475E-B233-AC2F67086EC4>.<489> resuming
Task <B22D34D2-4EEB-475E-B233-AC2F67086EC4>.<489> has not requested a begin delay
Task <B22D34D2-4EEB-475E-B233-AC2F67086EC4>.<489> skipping delayed request callback - delegate not implemented …
```

Prevent using background session on Catalyst

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Notifications/HomeAssistantAPI+Notifications.swift
HomeAssistant/Utilities/Bonjour.swift
HomeAssistant/Utilities/WatchHelpers.swift
HomeAssistant/Views/Settings/NFC/NFCReader.swift
HomeAssistant/Views/Settings/NFC/NFCWriter.swift
HomeAssistant/Views/SettingsDetailViewController.swift
Podfile
Podfile.lock
Shared/API/HAAPI.swift
Shared/API/Models/NotificationCategory.swift
Shared/API/Models/WebhookUpdateLocation.swift
Shared/API/Webhook/Sensors/BatterySensor.swift
Shared/API/Webhook/Sensors/StorageSensor.swift
Shared/Common/Structs/DeviceWrapper.swift
Shared/Common/Structs/Environment.swift
Shared/Settings/SettingsStore.swift
SharedTests/CLLocationManager+OneShotLocationTests.swift
SharedTests/Sensors/BatterySensor.test.swift

Switches from UIDevice to (available on Mac) `IOKit` and its Power Sources module. This gives us a lot more granular information about batteries, like cycle counts and other fun things. Given the volume of [available keys](https://developer.apple.com/documentation/iokit/iopskeys_h/defines) I've decided to just use the existing, gross, developer-ish key as the attribute. May clean this up in the future, may say "meh" since we're going to be hard-coding English as well anyway.
Removes DeviceKit; it wasn't updated for Catalyst (so it called every Mac a 'Simulator') and I didn't feel like trying to pull it into the Catalyst era manually since our use of it is pretty slim. Most of the methods were already something I had shimmed for easier testing.
Refs #934.

Fix Battery Sensor in Catalyst; add more info to it

---

HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Utilities/MenuManager.swift
HomeAssistant/Views/WebViewController.swift
Shared/Resources/Swiftgen/Strings.swift

Removes pull-to-refresh on Catalyst in favor of these menu choices. Not 100% certain on the keyboard shortcuts here:
- Reload Page: ⌘R
- Update Sensors: ⇧⌘R
I chose to keep them related to each other because they currently are in functionality, and R works entirely on the left hand in the English keyboard.

Add "Reload Page" & "Update Sensors" menu items for Catalyst

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Resources/HomeAssistant Beta-catalyst.entitlements
HomeAssistant/Resources/HomeAssistant Development-catalyst.entitlements
HomeAssistant/Resources/HomeAssistant-catalyst.entitlements
Shared/API/Webhook/Sensors/MacCameraSensor.swift
Shared/Common/Structs/Environment.swift

Adds a sensor for every camera connected to a Mac. State is true if camera is in use. Only attribute is Manufacturer. Icon changes based on if camera is on or not.
[Cameo](https://github.com/lvsti/Cameo) shows the following data about cameras is provided by the system. If anything else looks interesting I can expose it as attributes:
Next version of this should monitor for camera state changes and update sensors. Example implementations:
* [stackoverflow.com/questions/42681127/coremediaio-incorrectly-updated-properties-kcmiodevicepropertydeviceisrunningso?rq=1](https://stackoverflow.com/questions/42681127/coremediaio-incorrectly-updated-properties-kcmiodevicepropertydeviceisrunningso?rq=1)
* [wouterdebie/onair@`52f2ea0`/Sources/onair/Camera.swift](https://github.com/wouterdebie/onair/blob/ …

Add macOS camera state sensor

---

Shared/API/Webhook/Sensors/MacCameraSensor.swift

This changes from e.g. `sensor.debug_mac_facetime_hd_camera_built_in` with states like `True`/`False` with a `binary_sensor.debug_mac_facetime_hd_camera_built_in` with states like `on`/`off`.

Make camera sensors be binary_sensor

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/AppDelegate.swift
Shared/API/Webhook/Sensors/BatterySensor.swift
Shared/API/Webhook/Sensors/SensorProviderDependencies.swift
Shared/Common/Structs/DeviceWrapper.swift
Shared/Common/Structs/DeviceWrapperBatteryObserver.swift
SharedTests/Sensors/BatterySensor.test.swift

Adds an Update Signaler for battery state (but not level) changes. Level is effectively a timer for updating (on Mac it's every 60 seconds), which is effectively the same as our periodic timer -- it doesn't signal any kind of state changes, just that time has elapsed. This will, for example, update sensors immediately upon charge starting or ending (while the app is running, of course). This works on macOS and iOS but not on watchOS.

Add BatterySensor Update Signaler

---

HomeAssistant/Views/WebViewController.swift

- Reading whether NFC is supported requires a few XPC calls, which slow down startup. Moves the overall reading off the main thread so the webview can continue to load.
- Reports false for `hasSettingsScreen` so the app's settings do not show up in the sidebar on Mac. App Menu > Preferences is the entry point for Mac.

config/get: make async, hide config from sidebar on Mac

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Views/Settings/Sensors/SensorDetailViewController.swift
Shared/API/HAAPI.swift
Shared/API/Models/WebhookSensor.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
Shared/API/Webhook/Request&Response/WebhookRequest.swift
Shared/API/Webhook/Sensors/ActiveSensor.swift
Shared/Common/Structs/ActiveStateManager.swift
Shared/Common/Structs/DeviceWrapper.swift
Shared/Common/Structs/Environment.swift
Shared/Resources/Swiftgen/Strings.swift
SharedTests/ActiveStateManager.test.swift
SharedTests/Sensors/ActiveSensor.test.swift

This binary sensor reports `on` when the machine is active, `off` otherwise. Active state tracks: 
- Idle time, defaulting to 5 minutes. If no keyboard, mouse, or tablet (wat) input is detected in that period, we consider this idle. This is exposed as a Sensor setting (in Preferences > Sensors > Active).
- Screensaver starting and ending.
- Sleeping starting and ending.
- Screen turning off and on (also called sleeping in some places in Apple-land).
- Lock Screen, which is both the Apple > Lock Screen and the Fast User Switching mechanism.
- Fast user switching. This is the Menu Bar "switch to X user" and can also end up triggering Lock Screen too.
If none of these are happening, we consider the machine active.

"Active" Sensor for Mac

---

Shared/API/HAAPI.swift

This value was not using the override. Fixes #967.

Fix device name in events when overridden

---

Shared/API/Webhook/Sensors/CoreMediaIO Helpers/HACoreMediaObjectCamera.swift
Shared/API/Webhook/Sensors/MacCameraSensor.swift

When a camera doesn't have a unique ID (which appears to be transient), ignore it until another sensor pass. We still observe for changes, so it should update if it turns on and gains a unique ID.
Fixes #971.

Fix handling of cameras without unique ID

---

Shared/API/HAAPI.swift
Shared/Common/Structs/Constants.swift

Per home-assistant/core#38572 we can define actions in YAML. Actions are provided as view due to HA limitations in getting one integration (`ios` here) to access webhooks registered to another (`mobile_app`).
Tested locally in the following cases:
- `ios:` loaded in `configuration.yaml` with `actions` key.
- `ios:` loaded in `configuration.yaml` without `actions` key.
- `ios:` not loaded.
Push categories are also loaded fine.
Fixes #494

Enable server-defined actions for 0.115

---

.github/ISSUE_TEMPLATE/feature_request_iOS.md
.github/ISSUE_TEMPLATE/feature_request_mac.md

When opening a FR using the (awesome) new issue template, the mac/ios labels were accidentally mixed up, this fixes.

Fix swapped labels in issue template

---

HomeAssistant/Views/Settings/NFC/iOSTagManager.swift
Shared/API/Webhook/Sensors/CoreMedia and CoreAudio Helpers/HACoreBlahObject.swift

- Fix under-allocation crash in Core{Media, Audio} reading. This was, for example, allocating 1 byte for a 4-byte integer when reading arrays. Often times this worked, but would not work long-term.
- Fix occasional crash checking for NFC support. It's never supported, so avoid the call on Catalyst. Fixes #989.

Fix a couple crashes on Mac

---

Shared/Settings/SettingsStore.swift

Catalyst [renders content at 77%](https://developer.apple.com/design/human-interface-guidelines/ios/overview/mac-catalyst/) to adjust for iPad sizing being appropriate on a Mac. However, it's inappropriate to downscale our webview -- this just makes the content unnecessarily small compared to the default 100%.
This resets so e.g.:
100% -> 130%
150% -> 195%
Fixes #994.

Scale up WebView zoom to counteract Catalyst 77% scaling

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Authentication/AuthenticationController.swift
HomeAssistant/Views/Onboarding/ConnectInstanceViewController.swift
HomeAssistant/Views/SettingsViewController.swift
HomeAssistant/Views/WebViewController.swift
HomeAssistant/Views/WebViewWindowController.swift
Shared/Authentication/TokenManager.swift
Shared/Common/Structs/Environment.swift
Shared/Common/Structs/OnboardingStateObservation.swift

- Handle multiple WebViewWindowController instances for onboarding, so if more than 1 (File > New) window is open during onboarding or when onboarding is needed, the state updates. Fixes #993.
- Fix Safari handling on Mac for onboarding. The scheme provided needs to be just the scheme and not the full callback URL. Although the latter works on iOS, the former is required for Mac. This resolves it prompting to open the app during login, and the Safari window not being closed.

Fix a couple Mac onboarding issues

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Views/Onboarding/AuthenticationViewController.swift
HomeAssistant/Views/Onboarding/ConnectInstanceViewController.swift
HomeAssistantTests/ZoneManager/ZoneManager.test.swift
HomeAssistantTests/ZoneManager/ZoneManagerProcessor.test.swift
Intents/IntentHandler.swift
NotificationContentExtension/CameraStreamHLSViewController.swift
NotificationContentExtension/CameraStreamMJPEGViewController.swift
Shared/API/HAAPI+RequestHelpers.swift
Shared/API/HAAPI.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
Shared/Authentication/AuthenticationAPI.swift
Shared/Authentication/TokenManager.swift
Shared/Common/Structs/Environment.swift
Shared/Settings/SettingsStore.swift
SharedTests/ModelManager.test.swift
SharedTests/Webhook/WebhookManager.test.swift
SharedTests/Webhook/WebhookResponseLocation.test.swift
SharedTests/Webhook/WebhookResponseServiceCall.test.swift
SharedTests/Webhook/WebhookResponseUnhandled.test.swift
SharedTests/Webhook/WebhookResponseUpdateSensors.test.swift
TodayWidget/TodayViewController.swift
WatchAppExtension/CameraNotificationController.swift

- Potentially fix persisting connection info changes. There are a few situations where we appear to have multiple copies in memory of ConnectionInfo and they fight each other. This removes all caches of this value except for via the SettingsStore getter. Refs #932. 
- Enables cloud by default. Fixes #745.

Improve some connection settings behaviors

---

HomeAssistant.xcodeproj/project.pbxproj
Shared/API/Models/WebhookSensor.swift
Shared/API/Models/WebhookUpdateLocation.swift
Shared/API/Webhook/Sensors/BatterySensor.swift
Shared/Common/Structs/DeviceBattery.swift
Shared/Common/Structs/DeviceWrapper.swift
SharedTests/Sensors/BatterySensor.test.swift
SharedTests/Webhook/WebhookUpdateLocation.test.swift

- Handles 0 batteries where we expect to not send any sensor. Fixes #992.
- Handles more than 1 battery, for example having a UPS hooked up over USB.
I don't have any non-battery Macs that I can test on, nor do I have a UPS to test with, so the actual real-world testing of this will unfortunately have to be by users.
Breaking change for current Mac users: the internal battery is gaining a new Unique ID, so devices with or without a battery are going to need to manually disable the old battery entries.

Handle 0…n batteries on Mac

---

HomeAssistant/Views/SettingsDetailViewController.swift
HomeAssistant/Views/WatchComplicationConfigurator.swift

Although the complication logic was persisting the information correctly, the initial load of the view controller wasn't showing the right values -- likely due to some lifecycle in the table views. Fixes #752 by moving the hidden/not-hidden state of various sections into the sections themselves and asks them to update. This feels a bit less fragile and certainly more explicit.
This moves to having an explicit cancel button (which doesn't persist) and save button (which does) like the action/notification category editing. This also doesn't mutate the config while changing templates, so cancel is always an escape button.

Complication Configuration: Explicit cancel/save, fix initial values

---

HomeAssistant/Views/Settings/NFC/NFCTagViewController.swift
Shared/API/HAAPI.swift

These values were incorrect (when we aren't firing the event) since the id used isn't the integration id we supply but a generated one we don't know about.
0.115 / 0.114

Remove device_id from example tag triggers

---

Widgets/Actions/WidgetActionsActionView.swift
Widgets/Actions/WidgetActionsContainerView.swift
Widgets/Actions/WidgetActionsProvider.swift

If we're given more space than we think is the minimum for a particular widget size, bump up the font. Fixes #1005. Applies to both iOS and Mac.

Allow widget text size to be larger when given more space

---

Widgets/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
Widgets/Resources/Assets.xcassets/WidgetBackground.colorset/Contents.json

Unexpectedly, these colors that I left at the default -- if white -- make the text hard to read. Any other color seems to set it to black. I don't understand, either. But it fixes it! And now we customize the 'add' button color.

Fix 'Choose' and other Widget config text readability

---

HomeAssistant/Views/Settings/Sensors/SensorDetailViewController.swift

Booleans encoded as NSNumbers from Objective-C when evaluated by `String(describing:)` end up showing their integer value, rather than boolean value. Since they're constants, we can directly compare -- otherwise we'd have no way of knowing it was `@YES` or `@NO`.
Fixes #1006.

Fix sensor detail view of Objective-C booleans

---

Intents/CallService.swift
Intents/FireEvent.swift
Intents/GetCameraImage.swift
Intents/PerformAction.swift
Intents/RenderTemplate.swift
Intents/SendLocation.swift

When we use `.confirmationRequired(…)` for the result of a parameter resolve, the system drops it and silently stops executing the shortcut (without erroring or success). This is a change in behavior from iOS 13.
Working around this improves the user experience anyway - if a value is required, for example, telling the system this allows it to prompt the user for a value rather than erroring.
Fixes #1031.

Fix not-fully-defined Shortcut execution by asking for values

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcworkspace/xcshareddata/swiftpm/Package.resolved

This brings back the iOS 14 lock-kill crash (in case Apple reintroduces it) and fixes the iOS 11/12 regression the same fix introduced.

Update Realm to 5.4.2

---

Shared/Common/Structs/DeviceWrapper.swift

Fixes #1038, e.g.: the user agent will be like `Home Assistant/2020.7 (io.robbie.HomeAssistant; build:1; macOS 11.0.0)`.

Force 'macOS' as the OS name wherever we ask the system, fixing User-Agent

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Scenes/WebViewSceneDelegate.swift
HomeAssistant/Views/ScaleFactorMutator.swift
Shared/Settings/SettingsStore.swift

When the NSView's scaleFactor is 0.77 and we set the WebView to be 1.30 to offset it, we end up slightly scaling the text since it's not a perfect multiplication.
This eliminates the scale factor entirely when the scene is for the WebView, but leaves other scenes (e.g. settings, about) alone since we do want the automatic scaling in them.
Fixes #1041.

Fix slightly-blurry scale issues with WebView

---

HomeAssistant/Classes/LifecycleManager.swift

The lifecycle of the Catalyst app has it enter the 'background' when all the windows are closed or the app is hidden. Normally, entering the background means we'll be suspended but this is not the case on Mac.

Allow background periodic sensor updates on Mac

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Resources/en.lproj/Localizable.strings
HomeAssistant/Scenes/SceneManager.swift
HomeAssistant/Scenes/SettingsSceneDelegate.swift
HomeAssistant/Utilities/MenuManager.swift
Shared/Resources/Swiftgen/Strings.swift

- Adds the menu item, which pushes the detail controller on the settings window (opening if necessary).
- Fixes the type handling of pending resolvers for scene activation. Since we may be calling in a superclass of the expected delegate type, we need to make the resolver conditionally cast to figure out if it's the same thing.
Fixes #940

Add "Configure…" to Actions menu

---

HomeAssistant/Authentication/AuthenticationController.swift

The symbol of SFAuthenticationSession isn't available, but we don't need it since macCatalyst's initial version is iOS 13+, which has ASWebAuthenticationSession.
Fixes #1035.

Fix running on older Catalina

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Views/Settings/ConnectionSettingsViewController.swift
Intents/PerformAction.swift
MacBridge/MacBridgeImpl.swift
MacBridge/MacBridgeWiFiConnectivityImpl.swift
Shared/API/Webhook/Sensors/ConnectivitySensor.swift
Shared/Common/Structs/Environment.swift
Shared/Common/Structs/MacBridgeProtocol.swift
Shared/Networking/ConnectionInfo.swift
SharedTests/Sensors/ConnectivitySensor.test.swift

Uses the new MacBridge to talk to macOS-only CoreWLAN, which can give us the WiFi information about the Mac.
- Adds back in the SSID/BSSID sensors, mirroring how iOS creates them. If there are no WiFi devices, this doesn't add any sensors.
- Restores the Internal URL when WiFi is available.
This is intentionally (currently) ignoring the fact that there may be more than one WiFi interface, because I did not want to refactor the connection things throughout the app yet.
This does not include the connectivity type sensors, because they do not provide useful information as of yet -- if we can say e.g. which ethernet devices are connected, that might be more useful.
This framework _does_ support live-updating us if there are any changes, so an update signaler for this may be good. Or it may …

Add Mac SSID/BSSID sensors

---

Configuration/HomeAssistant.xcconfig

Fix series 3 crash by disabling dead code stripping on watchOS

---

Shared/API/Models/Action.swift

Apple _specifically_ says:
> Setting this property assumes the subcomponent or component string is not percent encoded and will add percent encoding (if the component allows percent encoding).
Whoops.

Fix synced actions failing via Widget/Actions menu

---

HomeAssistant/AppDelegate.swift
HomeAssistant/Classes/LifecycleManager.swift
HomeAssistant/Classes/ZoneManager/ZoneManager.swift
HomeAssistant/Classes/ZoneManager/ZoneManagerProcessor.swift
HomeAssistant/Utilities/UIApplication+BackgroundTask.swift
HomeAssistant/Views/IncomingURLHandler.swift
HomeAssistant/Views/Settings/Sensors/SensorListViewController.swift
HomeAssistant/Views/WebViewController.swift
Shared/API/HAAPI.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
Shared/Common/Structs/Environment.swift
Shared/Networking/BackgroundTask.swift
Shared/Networking/ProcessInfo+BackgroundTask.swift

Since we're running in the app, we have access to the UIApplication background task assertions, which are a lot cleaner than the ProcessInfo variety since that API doesn't require blocking the execution of a thread while we do work elsewhere.

Avoid thread-blocking ProcessInfo background tasks in app

---

Shared/API/Models/WebhookUpdateLocation.swift
SharedTests/Webhook/WebhookUpdateLocation.test.swift

If the Mac has no batteries, the server rejects the `-1` battery level this was sending before since it requires a `positive_int` value. However, it's optional, so we can just omit it.
Fixes #1092.

Fix sending a location update when there are no batteries

---

Shared/API/HAAPI.swift
Shared/API/Webhook/Request&Response/Promise+WebhookJson.swift
Shared/API/Webhook/Request&Response/WebhookManager.swift
SharedTests/Webhook/Promise+WebhookJson.test.swift
SharedTests/Webhook/WebhookManager.test.swift

There's 2 ways that we're told that an integration/webhook has gone away:
1. Cloud will give a 404 error for the webhook response (easy!)
2. HA will give a 200 with an empty/unparseable body for the webhook response (hard!)
Rather than trying to build the inverse set of these errors, add logic to explicitly capture them. Hopefully.
Fixes #1085.

Fix re-registering integration unnecessarily for some http errors

---

Shared/Common/Structs/DeviceBattery.swift

Unfortunately I need to change the unique ID backing the Mac battery sensors again, which will mean duplicate entities for beta users.
At the time of writing this, my MacBook Pro entry in my HA instance has 4 batteries, which is of course incorrect. It looks like we cannot trust the ID for the power source like we trust e.g. the ID for the camera/microphone. They're of course different APIs but IOKit doesn't seem to make any guarantees.
This moves us to use, in the following order of preference:
1. Serial number (recommended to exist)
2. Name (required to exist)
3. Type (required)
Stringly-typed dictionary APIs are the worst! My hunch is we'll never drop down to type since name should win, but we'll see how often we are without a serial number as well.
Fixes #1030.

Fix battery sensor inconsistent unique ID (again)

---

HomeAssistant/Views/Settings/NotificationRateLimitsAPI.swift

I would have assumed I had noticed this earlier but it looks like it has been this way since I moved it off Firestore in July.

Fix notification settings showing 'errors' instead of 'attempts'

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant/Resources/Base.lproj/Intents.intentdefinition
HomeAssistant/Resources/Info.plist
Intents/Info.plist
Intents/IntentHandler.swift
Intents/UpdateSensors.swift

This is functionally nearly identical to the "Send Location" intent, but doesn't require providing a location to the shortcut to execute, nor does it need to do a network request to geocode, so it should be a lot faster at providing updates.
This is useful for e.g. "When Low Power Mode is turned on or off" or "When (phone) is connected or disconnected from power" automations in Shortcuts.app.
I submitted Intents.strings to Lokalise externally so it should come down in the next download into English as well.

Add "Update Sensors" intent

---

HomeAssistant/Classes/ZoneManager/ZoneManagerCollector.swift
HomeAssistantTests/ZoneManager/ZoneManagerCollector.test.swift

This avoids sending `ios.zone_{entered,exited}` on startup, and also stops resetting which monitored regions we are monitoring as a result of a location update, which may have been caused by resetting which monitored regions we are monitoring, etc., etc.
Since we do not locally need the in/out state of Zones, we can deal with their status being eventually correct instead of initially or whenever they change.
Fixes #1114.

Don't trigger location update on initial zone monitoring

---

Sources/App/Resources/Base.lproj/InfoPlist.strings
Sources/App/Resources/Info.plist
Sources/App/Resources/en.lproj/InfoPlist.strings

This is a preference (which can only be edited in the system Settings app) which can toggle on and off the intelligent tracking protection features of iOS 14. It doesn't appear that this string is used anywhere; it just shows a switch labeled "Allow Cross-Website Tracking."

Add cross-website tracking description to enable preference

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/Settings/NFC/NFCNDEFPayload+Additions.swift
Sources/App/Settings/NFC/NFCWriter.swift
Sources/App/Settings/NFC/iOSTagManager.swift

This is an external record which hints which application should be launched for the NFC tag. When uninstalled, this launches the app in the Play Store when read.
With this additional record, the payload size grows from 63 bytes to 115 bytes. Since this could potentially increase beyond a tag limit, the Android record will be dropped if the capacity could hold just the URI on its own.
Replaces #1078.

Add Android Application Record to NFC tag writing

---

HomeAssistant.xcodeproj/project.pbxproj

Accidentally checked in the "disable on Mac" because of auto provisioning profile issues when it's enabled.

Restore Share Extension on Mac

---

Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/App/WebView/WebViewController.swift
Sources/Shared/API/ConnectionInfo.swift
Sources/Shared/Common/Extensions/URL+Extensions.swift
Sources/Shared/Settings/SettingsStore.swift

This moves the 'connection did change' notification from "we moved from internal to external" to "connection info changed in any way." For example, updating the connection settings will cause the WebView to immediately update, rather than requiring a pull-to-refresh.
- We now update the WebView URL and Settings "Connected Via" much more aggressively/reliably. Fixes #339.
- Comparing the 'should we reload?' for the URL now takes into account things like port being different.
This also avoids persisting/notifying ConnectionInfo changes when the values aren't changing. For example, every time we update our registration if it's just staying the same don't bother.

Aggressively watch for connection changes in WebView

---

Sources/App/Settings/WatchComplicationConfigurator.swift

Found during debugging that this configuration wasn't being pushed to the Watch fast enough; I'd often need to forcibly call this to get the configuration updated.

Immediately update Watch upon Complication saving

---

Sources/Shared/API/Models/WatchComplication.swift
Sources/Shared/Common/Extensions/CLKComplication+Strings.swift

Requires an icon; adds the flag that we need the icon for the template and sets the image size.
Fixes #1166.

Implement Graphic Bezel Circular Text

---

Sources/App/Settings/WatchComplicationConfigurator.swift
Sources/Extensions/Watch/ComplicationController.swift
Sources/Shared/API/Models/WatchComplication.swift
Sources/Shared/Common/Extensions/CLKComplication+Strings.swift

- Fixes, in general, any complication involving a Ring -- none of the values were being persisted in a way it could understand and color was missing entirely.
- Fixes Extra Large's "Simple Image", "Stack Image", "Ring Text" and "Ring Image". Fixes #1165.
- Fixes Utility's Small "Square" image (the size name was wrong), "Ring Image" (same as above), "Ring Text". Fixes #1164.

Fix ring and single-color-tinted Watch Complications

---

Configuration/Entitlements/WatchApp.entitlements
HomeAssistant.xcodeproj/project.pbxproj
Sources/App/AppDelegate.swift
Sources/App/Settings/WatchComplicationConfigurator.swift
Sources/App/WebView/WebViewController.swift
Sources/Extensions/Watch/ExtensionDelegate.swift
Sources/Shared/API/Models/WatchComplication.swift
Sources/Shared/API/WatchHelpers.swift
Sources/Shared/API/Webhook/Request&Response/WebhookResponseUpdateComplications.swift
Sources/Shared/Common/Extensions/Dictionary+Additions.swift
Sources/Shared/Common/Extensions/String+HA.swift
Sources/Shared/Environment/Environment.swift
Tests/Shared/Webhook/FakeWebhookManager.swift
Tests/Shared/Webhook/WebhookResponseUpdateComplications.test.swift
Tests/Shared/Webhook/WebhookResponseUpdateSensors.test.swift

One of our top crashes (on all platforms) is crashing when completing the background refresh operation of the Watch Extension's update cycle. I believe this is because the task is being called more than once; presumably because we're mixing multiple types of tasks in one pointer -- communication updates and complication updates, and they stomp on each other.
Another issue here is that we're not using Background Sessions to do the complication updates, when we want to -- when I refactored Webhooks out of the HomeAssistantAPI code path, I neglected to update this Webhook call to handle background updating; it now does.
- Updates complication text rendering to go through the background session supporting Webhook update mechanism.
- Adds support for ring and gauge template rendering. Fixes …

Improve reliability of refreshing Watch Complications

---

Sources/App/Settings/WatchComplicationConfigurator.swift
Sources/Extensions/Watch/ExtensionDelegate.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/WatchHelpers.swift
Sources/Shared/API/Webhook/Request&Response/WebhookManager.swift
Tests/Shared/Webhook/WebhookManager.test.swift

Running the latest Watch Extension on my device, I'm seeing a lot of kills like:
> Termination Reason: CAROUSEL, Background App Refresh watchdog transgression. Exhausted wall time allowance of 15.00 seconds.
From the [documentation on `WKApplicationRefreshBackgroundTask`](https://developer.apple.com/documentation/watchkit/wkapplicationrefreshbackgroundtask#), the suggestion is to kick off a background URLSession request and immediately end the app refresh task, allowing the background session code paths to complete the execution. Given we're being killed so often, I'm guessing that part'll work just fine.
Fixes #1191.

End Watch Complication refresh task on network start, not network end

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp (Complication).xcscheme
HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp (Notification).xcscheme
HomeAssistant.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/AppleWatch/ComplicationEditViewController.swift
Sources/App/Settings/AppleWatch/ComplicationFamilySelectViewController.swift
Sources/App/Settings/AppleWatch/ComplicationListViewController.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/Settings/SettingsViewController.swift
Sources/Extensions/Watch/ComplicationController.swift
Sources/Extensions/Watch/ExtensionDelegate.swift
Sources/Shared/API/Models/WatchComplication.swift
Sources/Shared/API/WatchHelpers.swift
Sources/Shared/API/Webhook/Request&Response/WebhookResponseUpdateComplications.swift
Sources/Shared/Common/Extensions/CLKComplication+Strings.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Tests/Shared/Webhook/WebhookResponseUpdateComplications.test.swift

This allows for configuring more than 1 e.g. Modular Small at a time. This requires watchOS 7; for releases before watchOS 7 we do not allow a secondary template to be created. This could be improved by allowing swapping between one of the multiple for watchOS 6 and earlier, but I didn't implement this.
- Adds a "Display Name" to Complications. This is optional and falls back to the template type. This is primarily to differentiate complications; the underlying unique ID is just a UUID.
- Enable previews of complications, which is used when selecting them. This is a stripped-down version of the items in the template, usually just an icon provider or one of the text providers. This is largely easier now since we're now requesting templates for all complications, even those not actively …

Support multiple Apple Watch complications

---

Sources/Shared/Common/Extensions/CLKComplication+Strings.swift

Went through and audited the numbers and what Apple claims the values are. The ones in the docs call out that they're the 2x numbers in _pixels_ so they need to be converted to points to use. I filled in a few missing values and double checked the ones that were already there.
Fixes #276.

Fix complication image sizes

---

Sources/Shared/API/Webhook/Request&Response/WebhookManager.swift
Tests/Shared/Webhook/WebhookManager.test.swift

(Likely; this is really hard to test) fixes a crash in the WatchApp when it's already in memory and the system wakes it to handle a background session completion event. What is happening is we're being killed after 25 seconds because we haven't completed the `WKURLSessionRefreshBackgroundTask`.
What I think is happening is that the background session processes and completes before the background task sets up the completion handlers, since the delegate method ends up jumping to the delegate dispatch queue of the background session.

Handle background session completion before Extension/App Delegate

---

Sources/App/WebView/WebViewController.swift
Sources/Shared/Settings/SettingsStore.swift

Fixes #1201. WebKit (unsurprisingly) really does not like being told to execute JavaScript off the main thread.

Fix crash caused by background connection status change

---

Sources/App/LifecycleManager.swift
Sources/Shared/API/HAAPI.swift

We provide three lifecycle events communicated back to HA, `ios.finsihed_launching`, `ios_entered_background` and `ios.became_active`. One of the most obvious use cases, IMHO, of `ios.became_active` is to reset/clear the app badge. However, we currently provide any clear data in the event payload about the source (e.g. device name) of the event. This PR provides the same basic device info that we include in the action events. For sake of a single source, the definition of dictionary in `HomeAssistantAPI` is changed to public rather than duplicating elsewhere. Tested against current dev

Add device info to lifecycle events

---

Sources/App/AppDelegate.swift

For example, going from external to internal or vice-versa should update the context flag `isOnInternalNetwork`. We're likely still going to have cases where the Watch is not correct on which connection type to use, but hopefully location services causes the app to inform it most of the time.

Update the Watch when connectivity changes

---

Sources/Extensions/Intents/IntentHandler.swift

Reproducing this is pretty easy: add a Shortcut for e.g. call service and spam tap the placeholder while the intent is launching; it'll crash.

Fix a crash when lots of intent handlers are requested at once

---

Sources/App/Settings/AppleWatch/ComplicationListViewController.swift

Accessing the .displayName can occur during the deletion from e.g. UIView events causing a cell to update. We reload the cell on update, anyway, so all we really need to do is set the value initially.

Fix crash when deleting some Complications

---

Sources/Shared/API/Models/WatchComplication.swift

This resolves a crash on watchOS 6 when a Complication Template is missing required fields (e.g. one of the text providers) and instead returns the 'error' template.
watchOS 7 wasn't exactly better as it would not crash but it wouldn't be obvious about the error happening, so this also improves that situation.
This is a half-measure to telling the user which fields are optional or not when editing the complication, but it should be a _lot_ more obvious when we do not have the information necessary to make the template.

Avoid generating invalid templates due to non-optional fields

---

Sources/App/WebView/WebViewController.swift

This could be fixed better -- wait for the currently-presented thing to finish, present then -- but I don't think it's worth the effort.
Fixes #1115.

Fix crashing when an alert is presented during another presentation

---

Sources/App/ZoneManager/ZoneManagerEvent.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Location/CLLocationManager+OneShotLocation.swift

- NSLog is dangerous in production; it crashes randomly on iOS 13. It also truncates the logs to a certain length, unlike print(), so swap to that one.
- This also changes a few try! into not-force-unwrapping, one or two of which have fired into the crash reporter.
- Avoids logging about deleted zones while they are being deleted. Likely related to the infinite-loop zone (#1136) but definitely happens quite a bit right now.

Resolve minor debug logging and try! crashes

---

Sources/Shared/API/Webhook/Sensors/ConnectivitySensor.swift
Sources/Shared/Common/Extensions/Reachability+NetworkType.swift

The 5G connectivity defines are declared available in iOS 14.0+ but evaluate to nil or whatever on iOS 14.0.

Fix crash in connectivity sensor on iOS 14.0 (and not 14.1+)

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/Settings/Eureka/AccountInitialsImage.swift
Sources/App/Settings/Eureka/AccountRow.swift
Sources/App/Settings/SettingsViewController.swift
Sources/App/Utilities/Utils.swift

Extremely long horizon: multiple of these could be shown to configure the settings of a particular server.
Copies the look and feel of the 'avatar' initials and image loading from the frontend. When an avatar isn't set or isn't loaded yet, this shows the initials view.

Unify Server  & Connection settings into 1 row

---

Sources/App/Resources/en-GB.lproj/Localizable.strings
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/AppleWatch/ComplicationEditViewController.swift
Sources/Extensions/Watch/ComplicationController.swift
Sources/Shared/API/Models/WatchComplication.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Given that we essentially let users add anything from Home Assistant that can be represented as text as a complication I thought it would be a good idea to let people choose whether or not to display a complication when the watch is locked.
Tested on my watch and seems to be working 😯although I haven't tested the Realm migration yet. Apologies in advance, this is my first time trying something of this complexity (for me, appreciate it's actually pretty simple)

Allow hiding complications when watch is locked

---

Sources/Shared/Common/Extensions/UIImage+Icons.swift

So turns out there is a subset of the MDI icons available with the `hass:` prefix which is totally undocumented. It was introduced back in home-assistant/frontend#1214 to avoid loading the entire MDI set and I don't think was intended for user use but they do work perfectly in the frontend if used. I think this is now handled differently in the frontend but these icons remain.
This PR simply uses a little regex to check for `hass:` in addition to `mdi:`.
Could of course add as an additional `replacingOccurrences` after the first one but this to me seems neater, could perhaps tidy the other two to match.
Was reported on Discord [here](https://discordapp.com/channels/330944238910963714/551871772484698112/774005750011920384)

Handle hass: prefix in icon names

---

Sources/Extensions/Intents/CallService.swift
Sources/Extensions/Intents/GetCameraImage.swift
Sources/Extensions/Intents/RenderTemplate.swift
Sources/Extensions/Intents/SendLocation.swift

These confirm blocks were firing an error case and then success case. They aren't needed necessary any more since we do the validation when resolving.
Fixes #1250.

Fix crash when signed out and issuing intent

---

Sources/Shared/API/ConnectionInfo.swift
Sources/Shared/Common/Extensions/URL+Extensions.swift

Fix crash when connection URL contains invalid scheme

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/Extensions/Watch/ComplicationController.swift
Sources/Shared/Common/Extensions/CLKComplication+Strings.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Since we only offer complications for configured versions, we don't have a quick "launch the app" complication available without creating one, and you cannot create one that's just the HA logo.
Rather than adding a new template configuration for the app icon, this adds a complication to all places we support which show some variant of "Home Assistant", "HA" and the app icon without any kind of "this is an error!" state.
Fixes #1281. Fixes #525.

Add "Placeholder" complication

---

Sources/App/ZoneManager/ZoneManager.swift
Sources/App/ZoneManager/ZoneManagerCollector.swift
Tests/App/ZoneManager/ZoneManager.test.swift
Tests/App/ZoneManager/ZoneManagerCollector.test.swift

At least on iOS 13 and 14, initially monitoring a region causes the system to always fire a did-change-state delegate method for that zone. When users exceed the 20 region threshold, the delegate firing can cause us to bounce back and forth between sets of zones that we want to monitor, and each chain can cause another set of updates to occur. This is especially apparent for users using the iCloud3 integration which creates a multitude of 1m zones.
Fixes #1267

Fix infinite loop when monitoring regions when exceeding maximums

---

Sources/Shared/API/HAAPI.swift

This doesn't affect what happens -- saving 404 text to something.mp4 doesn't play -- but it does make the logs easier to see if something is going wrong.

Fix allowing a 404 error to be a 'successful' notification download

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/Shared-iOS.xcscheme
Sources/App/Resources/en.lproj/Localizable.strings
Sources/Extensions/NotificationService/NotificationService.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentErrorImage.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentManager.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentParser.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentParserCamera.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentParserURL.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Tests/Shared/NotificationAttachment/NotificationAttachmentManager.test.swift
Tests/Shared/NotificationAttachment/NotificationAttachmentParserCamera.test.swift
Tests/Shared/NotificationAttachment/NotificationAttachmentParserURL.test.swift

- Refactors notification attachment into smaller units. Adds tests.
- Adds an image attachment with whatever the error reason is when an attachment fails to download.
- Adds a Shared framework scheme which can run just its tests. It's a bit faster than doing the whole app which has a lot of extensions and watchOS targets.
This does not (yet?) create the error images for the service timeout. Not sure how relevant that may end up. I haven't yet come across a case of this happening in logs and being confusing.

Update notification attachment handling, add error images

---

Sources/Extensions/NotificationContent/MapViewController.swift

- Fixes a crash when `latitude` or `longitude` are String types but not able to be converted to Double/CLLocationDegrees.
- Adds support for Int or Float-based `latitude` or `longitude`, e.g. what native templates would provide were it not currently broken.

Fix crash when Map notification is provided invalid latitude/longitude

---

Sources/App/Resources/Info.plist
Sources/App/Resources/en.lproj/InfoPlist.strings

Required for Mac App Store review. This notably does not use the iOS keys (`NSLocationWhenInUseUsageDescription`, `NSLocationAlwaysUsageDescription`, `NSLocationAlwaysAndWhenInUseUsageDescription`) but instead uses the deprecated key `NSLocationUsageDescription`.

Add macOS-specific location permission description

---

Sources/App/Resources/Info.plist
Sources/App/Resources/en.lproj/InfoPlist.strings
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Connection/ConnectionURLViewController.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/Utilities/PermissionStatusRow.swift
Sources/App/Utilities/Permissions.swift
Sources/App/WebView/WebViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Settings/SettingsStore.swift

Fixes #776.
- Adds a temporary request for full accuracy when pulling-to-refresh.
- Prevents delays when sending sensor updates trying to get accurate locations when accuracy isn't full; we no longer consider ourselves having location permission when accuracy isn't full.
- Add "Location Accuracy" setting to Location settings, showing current state.
- Adds a warning to the Internal URL editing when accuracy isn't full, since it is required to get SSID information.
- Updates to use newer CLLocationManager "authorization changed!" methods in various places.

Updates for iOS 14's "Precise" location setting

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/MacBridge/MacBridgeAppDelegateHandler.swift
Sources/MacBridge/MacBridgeImpl.swift
Sources/Shared/Environment/ActiveStateManager.swift
Sources/Shared/Environment/MacBridgeProtocol.swift
Tests/Shared/ActiveStateManager.test.swift

Fixes #1270.
Sends a webhook update with the active status as 'off' when the app is terminating. This doesn't work if, of course, the app crashes or is force quit.
In a normal Mac app, to do something when Termination is about to happen, you tell the system to hold on a sec, you do the thing, and then you tell the system you're done. Easy, right?
Well, we're a Catalyst app, so no: it definitely is not that easy. Why should we have access to an `NSApplicationDelegate` instance to do this exchange?
After quite a bit of investigation, I'm reasonably sure that `NSUIApplicationDelegate` does termination like so: if there are any existing `UIApplication` background tasks, delay termination, wait for them to complete, then complete termination.
The trick then becomes trying to get a background …

Watch for App termination and update Active Status

---

Sources/MacBridge/MacBridgeAppDelegateHandler.swift

Fixes a regression from #1344 due to never getting an app delegate.

Fix infinite looping in Mac Extensions

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/MacBridge/MacBridgeImpl.swift
Sources/MacBridge/MacBridgeScreenImpl.swift
Sources/Shared/API/Webhook/Sensors/DisplaySensor.swift
Sources/Shared/Environment/DeviceWrapper.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Environment/MacBridgeProtocol.swift
Tests/Shared/Sensors/DisplaySensor.test.swift

Fixes #1247.
Adds 3 sensors for displays: "Displays" (a count), "Primary Display Name" (the name of the display with the menu bar on it), and "Primary Display ID" (the ID of the primary).
Documentation: home-assistant/companion.home-assistant#421
- `sensor.displays` 
- states like `0`, `1`, `2`, …
- attributes of `"Display IDs": ["id1", "id2", …]` and `"Display Names": ["name1", "name2", …]`
- `sensor.primary_display_name`
- states like `"None"`, `"Built-in Retina Display"`, etc.
- `sensor.primary_display_id`
- states like `"BE82E2E6-EA40-4963-93AD-A0BDC9D2F18F"`, `"1AB60A12-6BB3-4503-96BD-F5B481F5830E"` etc.

Add sensors for Mac displays

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/MacBridge/MacBridgeImpl.swift
Sources/Shared/API/Webhook/Sensors/FrontmostAppSensor.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Environment/MacBridgeProtocol.swift

Fixes #977.
Adds a sensor for the current frontmost app, also known as the current foreground or active app. 
Documentation: home-assistant/companion.home-assistant#425
Creates `sensor.frontmost_app` which has a state of the name of the current frontmost app, or None if there isn't one. I'm really not sure how that can happen, but it's definitely possible. This updates via a signal when it changes, so it happens immediately.

Add sensor for frontmost app on Mac

---

Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/App/Settings/Connection/ConnectionURLViewController.swift
Sources/Shared/API/ConnectionInfo.swift

Fixes #1366.
External URL and Cloud are mutually exclusive; better illustrates this fact in the UI by putting them next to each other.
- Fixes an issue where external wouldn't be promoted to remote at runtime.
- Fixes the 'connected via' not updating correctly when transitions happened, especially when saving.

Move Cloud setting into External URL

---

Sources/App/Settings/Sensors/SensorDetailViewController.swift
Sources/Shared/API/Webhook/Sensors/BatterySensor.swift
Tests/Shared/Sensors/BatterySensor.test.swift

Fixes #1311.
Removes duplicate attributes from both (so they do not refer to each other in attributes) and stops using `device_class` of `battery` on the state sensor.
Documentation: home-assistant/companion.home-assistant#430
Also stops showing the non-user-facing-anywhere-else "unique id" in the sensor detail list, and fixes an empty set of attributes (but non-nil dictionary) showing an empty section.

Clean up Battery Level & Battery State sensor attributes/classes

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/Shared/API/Webhook/Request&Response/WebhookManager.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Instead of saying something like `Shared.WebhookError code 1` when the webhook is responding back with status code 503, gives a more appropriate error.
What's really fun is the order of the enum appears to not matter for the debug error code. Reading the enum, you might think status code 1 was the 2nd error in the Error enum, but it's actually the 4th error in the list.

Improve messages for Webhook errors

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Fixes #1340.
Still allows selecting alternates. There doesn't appear to be any obvious url scheme that we can use to force Safari, so take over the Safari entry with just whatever `https://…` opens, which is the default browser.

Rename Safari "Open Links In" setting on iOS 14

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/Codegen.xcscheme
fastlane/Fastfile
fastlane/README.md
swiftgen.yml
swiftgen.yml.file-list.in
swiftgen.yml.file-list.out

- Saves a few seconds of incremental build time, especially by using input/output file lists for swiftgen.
- Fixes changing e.g. Localizable.strings not immediately taking effect in any target other than the main app.

Move SwiftGen/SwiftLint execution to an aggregate target

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/AppDelegate.swift
Sources/App/WebView/WebViewController.swift
Sources/App/WebView/WebViewWindowController.swift
Sources/Shared/Environment/Constants.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Environment/ServerAlerter.swift
Tests/Shared/ServerAlerter.test.swift

Shows an alert based on an alerts site JSON array, allowing us to customize alerts based on client or server version.
Not quite documentation, but the server-side JSON for this is here: home-assistant/alerts.home-assistant.io#269
- Does not send any local information anywhere. This only pulls the JSON remotely.
- Dismissing (by tapping the background, or swiping down) or opening the alert prevents it from displaying again.
- Supports any number of alerts, showing only the relevant and unseen ones.

Add server-driven alerts based on client or server versions

---

Sources/App/AppDelegate.swift
Sources/App/WebView/WebViewController.swift

- Fixes opening a second webview window on startup, due to trying to grab the webview promise before normal state restoration.
- Fixes not hiding the alert when tapping the 'open' button, as intended.

Fix a couple issues in server alert

---

Configuration/Entitlements/Launcher.entitlements
Configuration/HomeAssistant.xcconfig
HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/Launcher.xcscheme
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/Launcher/Application.xib
Sources/Launcher/Info.plist
Sources/Launcher/LauncherAppDelegate.swift
Sources/MacBridge/MacBridgeImpl.swift
Sources/Shared/Environment/MacBridgeProtocol.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Fixes #1383. Refs #949.
Allows the user to choose to launch the app on startup, which toggles on a login item which launches the app.
- Effectively this setting turns on whether to launch this Launcher app on login, and then the Launcher app launches the app whenever it's started, before terminating itself.
- Routes through the Mac Bridge to call `SMLoginItemSetEnabled` which appears to have no public API counterpart to get the current status. Various places point to `SMJobIsEnabled` which doesn't appear in any headers.
- Thanks @rudyrichter for the pointer on how to get this working.

Add "Launch App on Login" setting

---

Sources/MacBridge/MacBridgeStatusItem.swift

This length argument wants to be either the 'square' or 'variable'. Ours is slightly wider than it is tall, so using variable.

Use correct constant for status item creation

---

Sources/Shared/Environment/LocalizedManager.swift

Fixes e.g. using the key like `settings_detail.general.…` as the fallback if we cut a release without updating localized strings.
Before, after.

Use English as fallback when L10n key doesn't exist

---

HomeAssistant.xcodeproj/project.pbxproj

Fixes #1393.
Two issues:
1. SwiftLint doesn't support spaces in the config path (seemingly as of 0.42.0, see realm/SwiftLint#3471)
```bash
> Pods/SwiftLint/swiftlint --config "/Users/zac/Sources/hass ios/.swiftlint.yml"
error: SwiftLint Configuration Error: Could not read file at path: /Users/zac/Sources/hass
```
2. We were invoking it and passing things without spaces around the paths.

Fix compiling with spaces in paths

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/AppDelegate.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/Shared/Common/Extensions/Version+HA.swift
Sources/Shared/Environment/ServerAlerter.swift
Sources/Shared/Environment/Updater.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Settings/SettingsStore.swift
Tests/Shared/ServerAlerter.test.swift
Tests/Shared/Updater.test.swift

Fixes #1378.
- Adds a setting to control the automatic update checking, and an option to not include betas. 
- Adds a privacy option to disable server-side alerts.

"Check for Updates" & "Alerts" settings

---

Sources/Shared/API/WebSocket/AuthenticatedUser.swift
Sources/Shared/Environment/ServerAlerter.swift
Sources/Shared/Settings/SettingsStore.swift
Tests/Shared/ServerAlerter.test.swift

Fixes #1391.
Adds optional flag `admin_only` to the alert definition. Doesn't show them when it's set and the current user isn't an admin.
n/a

Add admin-only filtering for server-based alerts

---

Sources/App/Settings/NFC/NFCTagViewController.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Webhook/Sensors/PedometerSensor.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Environment/ServerAlerter.swift
Sources/Shared/Environment/TagManagerProtocol.swift
Sources/Shared/Settings/SettingsStore.swift

Fixes #1397.
Makes server version optional, returning nil when we don't know rather than a fallback version.
n/a
n/a
Prevents an issue where we'd alert about the fallback version being old enough to have an alert, rather than the actual version which comes later. Amusingly the work I did to make sure that we'd handle app-launch-to-web-view events supporting an onboarding flow in the middle causes the alerts to be delayed until the webview loads after initial login.

Make server version optional, fixing an alert issue

---

Sources/Shared/API/Webhook/Request&Response/Promise+WebhookJson.swift

Fixes #1398.
There's a core bug somewhere that's causing webhooks to start 5xx-ing. I haven't been able to reproduce it locally yet. Adding this log should help users who run into this bug, since we don't otherwise share these network failures for webhooks.
(Pretend like 200 is really a failure here.)

Add an event log entry when webhooks 4xx or 5xx

---

.github/workflows/ci.yml
Sources/Shared/Iconic/MaterialDesignIcons.swift
Tools/BuildMaterialDesignIconsFont.sh

First time bumping since moving to straight SwiftGen. Very easy. The next one will likely be hard as 6.x has migrations.
This includes a new icon, `webcam-off`. Once core has it, it would be nice to switch the camera sensors to use it.

Update MaterialDesignIcons to 5.9.55

---

Sources/App/WebView/WebViewController.swift
codecov.yaml

Changes the alerts to be more distinct - orange (stolen from the home-assistant.io page) instead of red.

Switch from red to orange for alerts

---

Sources/Shared/Environment/Environment.swift

Fixes a crash caused by #1390. Since all API was moved to use promises, and promises' default behavior for `then`/`map` is to dispatch to the main queue, this causes some `Current.api.then…` calls to become unnecessarily synchronous.
I am not super sure why `.main` as the default for the map queue makes sense. Maybe it prevents some cases where a promise will over-use the thread it's called on. This may also produce some bugs where we previously accessed things on the main queue under the assumption that it defaulted to this behavior.
Also adds a logger to the default PromiseKit prints, so that it routes into normal logs.

Update PromiseKit default map queue, fix crash performing action

---

Sources/Extensions/NotificationContent/CameraStreamMJPEGViewController.swift
Sources/Extensions/Watch/CameraNotificationController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/MJPEGStreamer.swift

Fixes attempting to use partial `Data` to construct the images in the MJPEG streaming. When I updated this code to a newer version of Alamofire, I did so without realizing the boundary conditions for when the data in memory is available.
Alamofire 6 may include a way to do this without having to implement the URLSession delegate method ourselves. See Alamofire/Alamofire#3401.

Fix MJPEG streaming in beta

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/AppDelegate.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Utilities/AppMacBridgeStatusItemConfiguration.swift
Sources/App/Utilities/MenuManager.swift
Sources/MacBridge/MacBridgeStatusItem.swift
Sources/MacBridge/NSEvent+Additions.swift
Sources/Shared/Environment/MacBridgeProtocol.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
codecov.yaml

Adds a basic menu structure to the status item. This includes:
- Toggling the app (e.g. activate or deactivate)
- Performing actions
- Opening About, Checking for Updates, opening Preferences and Quitting
There's not a clean way to do the left/right click handling. There's a few ways, all with their own pluses and negatives:
- Calling `popUpMenu(_:)` programmatically works, but it's marked as deprecated and it's tough to get Swift to not care.
- Handling `menuWillOpen` to instead do the left-click behavior and abort the menu display.

Add menu to status item on right-click

---

Sources/App/LifecycleManager.swift

The 'warm' connect was keying off background/foreground, which doesn't happen at all on Big Sur, and only happened in limited cases on Catalina. This now does it a lot more often.

Fix not doing a 'warm' connect on Big Sur

---

Sources/App/AppDelegate.swift
Sources/App/LifecycleManager.swift
Sources/App/Notifications/NotificationManager.swift
Sources/App/Onboarding/ConnectInstanceViewController.swift
Sources/App/Settings/ActionConfigurator.swift
Sources/App/Settings/AppleWatch/ComplicationEditViewController.swift
Sources/App/Settings/Eureka/AccountRow.swift
Sources/App/Settings/Sensors/SensorListViewController.swift
Sources/App/WebView/IncomingURLHandler.swift
Sources/App/WebView/WebViewController.swift
Sources/App/ZoneManager/ZoneManager.swift
Sources/App/ZoneManager/ZoneManagerProcessor.swift
Sources/Extensions/Intents/CallService.swift
Sources/Extensions/Intents/FireEvent.swift
Sources/Extensions/Intents/GetCameraImage.swift
Sources/Extensions/Intents/PerformAction.swift
Sources/Extensions/Intents/RenderTemplate.swift
Sources/Extensions/Intents/SendLocation.swift
Sources/Extensions/Intents/UpdateSensors.swift
Sources/Extensions/NotificationContent/CameraViewController.swift
Sources/Extensions/NotificationService/NotificationService.swift
Sources/Extensions/Today/TodayViewController.swift
Sources/Extensions/Watch/CameraNotificationController.swift
Sources/Extensions/Watch/ExtensionDelegate.swift
Sources/Extensions/Watch/InterfaceController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/ModelManager.swift
Sources/Shared/API/Webhook/Networking/WebhookManager.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Environment/TagManagerProtocol.swift

- Reverts #1418 - there's enough logic that is relying on the single-threadedness of then/map-ing on a shared queue.
- Forces all `Current.api` access to be done not on a queue intentionally, to avoid thread jumping when we don't expect, which is the core crash that this was trying to fix.

Revert PromiseKit threading change

---

Sources/Shared/Environment/Environment.swift
Sources/Shared/Location/CLLocationManager+OneShotLocation.swift
Tests/Shared/CLLocationManager+OneShotLocationTests.swift

- Breaks apart some shard tests so we have one-test-case-per-test-method
- Uses Promises correctly rather than exercising a queue

Attempt to fix location tests sometimes deadlocking

---

.github/workflows/ci.yml
.github/workflows/distribute.yml
fastlane/Fastfile
fastlane/README.md

- Breaks apart artifacts from giant zips to smaller files.
- Adds dSYM download & sentry lane. Since this doesn't work with the ASC API, it's less easy to automate right now.
- Adds a default timeout for both testing and release building.
- Dumps the version info during a build since it's useful for constructing releases, for now.

Minor automatic build followup

---

Sources/App/Settings/Connection/ConnectionURLViewController.swift

Removes the restriction around entering nabu.casa URLs directly. 
We do not gain much by disallowing it, other than support requests, and the most common case is that the remote UI isn't actually set up or is having SSL issues, which this will validate and check the URL before saving, providing an error message if appropriate.

Allow entering nabu.casa URLs manually

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/MacBridge/Bundle+Additions.swift
Sources/MacBridge/MacBridgeAppDelegateHandler.swift
Sources/MacBridge/MacBridgeImpl.swift

Accessing the NSStatusBar in an extension causes a crash; this avoids calling it in extensions. We also should not be touching the status bar in an extension either way.
Didn't show up during the betas, nor does it show up in Sentry. I'm guessing it's crashing so early in the MacBridge code that it doesn't have an opportunity to deal with crash logs.
Crashes look like:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Application Specific Information:
Assertion failed: (CGAtomicGet(&is_initialized)), function CGSConnectionByID, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/SkyLight/SkyLight-570.7/SkyLight/Se …
```

Fix crash in Mac extensions

---

Sources/App/Resources/WebSocketBridge.js
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/WebView/WebViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Settings/SettingsStore.swift

Refs home-assistant/frontend#8192.
When enabled, pinch to zoom is allowed in the frontend. When disabled, which is the default, it is not allowed. This does not respect what the frontend sends for the values of `minimum-scale`, `maximum-scale` and `user-scalable` and instead overrides them.
In home-assistant/frontend#7180, the frontend was changed to enable pinch to zoom in the app by removing the `user-scalable` flag. Browsers ignore this flag, but our UI is meant to feel like an app, not like a webpage. The accessibility part of the argument doesn't mirror iOS accessibility: dynamic type is how the system behaves and it doesn't scale elements like navigation or tab bars. To achieve an iOS-like accessibility experience, we have a setting to adjust only the text size in the frontend.
But …

Add setting to control pinch-to-zoom in frontend, defaulted off

---

Sources/App/AppDelegate.swift
Sources/App/Notifications/NotificationManager.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/Utilities/Utils.swift
Sources/App/ZoneManager/ZoneManager.swift
Sources/Shared/Settings/SettingsStore.swift
Tests/App/ZoneManager/ZoneManager.test.swift

The "Significant Location Change" and "Zone enter/exit" settings for Locations' Update Sources previously did not work. This now watches both settings for changes and handles enabling or disabling their respective monitoring.
- It takes a few seconds for the location-in-use arrow to disappear after disabling them.
- Users may be a little surprised if things _stop_ working, since they may have toggled these off for some reason in the past.

Fix location settings for siglog changes & zones

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Sensors/SensorDetailViewController.swift
Sources/App/Settings/Sensors/SensorListViewController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/WebhookSensor.swift
Sources/Shared/API/Webhook/Sensors/SensorContainer.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Tests/Shared/Sensors/SensorContainer.test.swift

Fixes #358.
Allows toggling on or off certain sensors. This does not currently delete the sensor but instead sets its state to 'unavailable'.
- Sensors are still only showing up in the sensor list if they have been generated during the app lifecycle. So for example the Geocode sensor doesn't show up unless a location update happened, and motion sensors do not show up if motion permission is disabled.
- Avoids removing items from the cache when they aren't around anymore, or when we think they are stale.

Allow disabling individual sensors

---

Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Webhook/Networking/WebhookManager.swift
Tests/Shared/Webhook/WebhookManager.test.swift

Fixes #1473. Again.
When we issue webhook requests, we were failing to cancel any previous requests (which want to be cancelled) that were executed on not-the-background session. This moves to now checking both the background and non-background for cancellable requests.
- Moves to explicitly cancelling, rather than silently replacing and succeeding, replaced requests. For example, a sensor update will now be explicitly cancelled if a new sensor update comes through, rather than following the success path.
- This resolves an issue where a sensor update occurs, fails on the non-background session, and retries with the same request data on the background session. This can lead to an older sensor update request, with outdated information, happening long after the most recent and correct one …

Fix non-background-session webhook request replacement

---

Sources/Shared/API/Webhook/Networking/WebhookManager.swift
Tests/Shared/Webhook/WebhookManager.test.swift

Fixes regression in #1487.
Ephemeral webhook sends do not have any persisted info on them, and that's to be expected.
None.

Fix incorrectly cancelling ephemeral tasks

---

Configuration/Entitlements/App-ios.entitlements
Sources/App/Notifications/NotificationManager.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Notifications/NotificationSettingsViewController.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/WebView/IncomingURLHandler.swift
Sources/App/WebView/WebViewWindowController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Handles being launched by universal links (e.g. https://my.home-assistant.io/redirect/logs) or via the url scheme `homeassistant://navigate/path/to/lovelace`.
https://user-images.githubusercontent.com/74188/109757851-7487b780-7b9f-11eb-923d-5388964d85a5.mov
This doesn't yet work on Mac, because my initial `WKWebView` implementation doesn't want to give us any events about URL schemes like `homeassistant://…` being tapped. I'm unsure how useful it'll be on Mac either way, but at least the `homeassistant://navigate/xyz` will still work there.

Handle my.home-assistant.io links on iOS

---

Sources/App/WebView/ScaleFactorMutator.swift

Fixes #1499.
Fixes a crash caused by infinitely cursing into `setHa_scaleFactor(_:)` due to (of course) swizzling!
Apple renamed (which is totally their prerogative, but it's also my prerogative to swizzle if they aren't going to make public API to do what I want 😈 ) the `scaleFactor` multiple for non-Mac optimized Catalyst builds, renaming it to `sceneToSceneViewScaleFactor`. Since we weren't checking if the swizzle was successful, the code path where we attempt to call into the swizzled variant calls itself infinitely until it gets killed.
Verified that the scale factor using this new property correctly doesn't make the webview super tiny, and hopefully made this less likely to break in the future.

Fix crash on macOS 11.3

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Shared/Location/CLLocation+Sanitize.swift
Sources/Shared/Location/CLLocationManager+OneShotLocation.swift
Tests/Shared/CLLocation+Sanitize.test.swift
Tests/Shared/CLLocationManager+OneShotLocationTests.swift

Fixes #1498.
Ignores secondary location data (like vertical accuracy) which is NaN or infinite; the latter of which CLLocationManager is happily delivering at least in the iOS 14.5 betas.
The problem with values like infinity is that they can't be represented in JSON, which means the system will raise an exception during JSON serialization. What's extra troublesome and ridiculous is that the JSONSerialization methods are marked `throws` -- as in, they throw Swift errors -- but the only error scenarios I can fathom (or can see in the [public implementation](https://github.com/apple/swift-corelibs-foundation/blob/99d6439016c008962d1b1cfc299dbbfd207c6454/Sources/Foundation/JSONSerialization.swift)) are ones that it raises exceptions for. Effectively, it never throws; it always raises an …

Fix crash on iOS 14.5 due to invalid location data

---

Podfile
Podfile.lock
Sources/App/AppDelegate.swift
Sources/Extensions/Watch/ExtensionDelegate.swift

Temporarily works around a race condition in Communicator where setting up observers happens at the same time as an observation firing, and the underlying data structure gets borked.
This is by far our biggest crash on both iOS and watchOS. This isn't a great fix -- a good one would provably require restructuring initialization of Communicator. This version is using a fork where I exposed publicly the underlying observer data structure so I could mutate it directly. Hopefully this is temporary.

Fix crash due to race condition in Communicator

---

Sources/App/Utilities/MenuManager.swift

Another macOS 11.3-ism, it appears to already have created a `.preferences` menu and doesn't at all like inserting another one.
This also resolves some issues I was ignoring where it would complain about menu changes via insert rather than replace in some cases. I'm guessing 11.3 is more sensitive about these things now.

Fix Preferences… not showing up on macOS 11.3

---

HomeAssistant.xcodeproj/project.pbxproj

It is too annoying when writing new code for the editor to be constantly whining. During `fastlane lint` / `fastlane autocorrect` is good enough.

Remove Xcode hook of SwiftFormat lint

---

Sources/Extensions/Intents/IntentHandler.swift

Refs #1219.
The original version tried to use different queues for every instance, which of course didn't do anything.

Fix threading crash in Intents

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/ClientEvents/LocationHistoryDetailViewController.swift
Sources/App/ClientEvents/LocationHistoryListViewController.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/Settings/SettingsViewController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/LocationHistory.swift
Sources/Shared/API/Models/WebhookUpdateLocation.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Hopefully improve debugging location issues by providing a visualization of what we know about a location update.
- Shows a blue circle for zones, an orange circle for non-single-region zones' regions, a purple circle for location and its accuracy.
- Allows sharing a bunch of debug data about the location and region states.
- Allows clearing of location history.

Add "Location History" to Settings

---

Sources/App/ZoneManager/ZoneManagerProcessor.swift
Sources/Shared/Common/Extensions/CLLocation+Extensions.swift
Tests/App/ZoneManager/ZoneManagerProcessor.test.swift
Tests/Shared/CLLocation+Extensions.test.swift

Fixes #1520.
Fixes a case where entering the 3-region overlap with extremely good accuracy wouldn't trigger an update to inside the zone. Also fixes not using the fuzzed accuracy at all on older than iOS 13.4.

Fix a sub-100m zone stuck-outside issue & a iOS pre-13.4 issue

---

Sources/App/ClientEvents/LocationHistoryListViewController.swift

Fixes crash due to out-of-bounds array access.
Not the first time, and definitely not the last time, that endIndex being non-inclusive tricks me.

Fix crash on last location history item

---

Sources/App/ClientEvents/LocationHistoryDetailViewController.swift
Sources/App/Settings/Notifications/NotificationSettingsViewController.swift

Fixes a crash in the new location history when tapping share, fixes another when tapping push ID.

Fix a couple iPad crashes due to popover source

---

Sources/App/ClientEvents/LocationHistoryDetailViewController.swift

The list shows seconds, and this should too.

Use with-seconds time in location history detail

---

Podfile.lock
Sources/App/Settings/Eureka/AccountRow.swift
Sources/App/Settings/SettingsViewController.swift

Uses the `caches.user` added to HAKit to observe the user and live-update the account row whenever the user or their avatar changes.
https://user-images.githubusercontent.com/74188/111947182-25e08580-8a9a-11eb-8778-09cf5eea5d86.mov
There does not currently appear to be any events that fire when a user is renamed, and in fact the frontend doesn't show new names until refresh, so the name part here does not update.
This also doesn't yet pull the location name from WebSocket so that is still loaded initially once.
Also resolves a few circular references which prevented settings from deallocing, which would have kept these subscriptions around indefinitely.

Live-update account row in settings

---

Sources/App/WebView/IncomingURLHandler.swift
Sources/Extensions/Intents/RenderTemplate.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Moves over the directly-render templates. Complications can never be moved over because they need to work cleanly with the background session logic on the watch.
Slightly poorly ergonomic about subscribing and then cancelling; might be nice to provide a "send this subscription and unsubscribe after the first event" flag, but nothing great for how to do that comes to mind.

Move render template (non-complication) to WebSocket API

---

Sources/App/AppDelegate.swift
Sources/App/Notifications/NotificationManager.swift
Sources/App/Settings/Notifications/NotificationSettingsViewController.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/Settings/SettingsViewController.swift
Sources/App/Utilities/Utils.swift

Fixes #1312.
After resetting user defaults, where we store the push ID, this sets a new value through so it'll be used during the next registration.

Reset push ID when resetting everything else

---

Sources/Extensions/Watch/InterfaceController.swift
Sources/Shared/API/HAAPI.swift

Fixes #1552.
Only fires on the watch if sending via phone is not an option, and only allows ephemerally sending an action.
Ephemerally sending doesn't retry nearly as much, and doesn't enter into any background URL session for possible persistent retry.

Reduce how often performing an action is retried

---

Sources/Shared/API/Webhook/Sensors/FrontmostAppSensor.swift

Since we change the settings on the formatter, we end up paying initialization cost for each one, which adds up fast when command-tabbing.

Cache date formatter for frontmost app sensor

---

Podfile.lock
Sources/App/AppDelegate.swift
Sources/Shared/Environment/Environment.swift

Fixes a crash (when parsing an entity fails) and parsing an entity with weird date formatting. 
- Moves to using leveled logs from HAKit so the error ones poke through in Sentry.
- Removes an unnecessary error on every startup that the updater isn't running in iOS or App Store.

Bump HAKit and minor logging updates

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/App-Debug.xcscheme
Sources/App/ZoneManager/ZoneManagerAccuracyFuzzer.swift
Sources/App/ZoneManager/ZoneManagerProcessor.swift
Sources/Shared/Common/Extensions/CLLocation+Extensions.swift
Tests/App/ZoneManager/ZoneManagerProcessor.test.swift

When the accuracy is fuzzed based on a region enter, we need to use that fuzzed location for the next fuzzer.
To make it less easy to make this bug happen again (where the intermediary fuzz value is ignored), this moves them to be reducing the same variable in a row.
Also fixed the test case for this flow to explicitly have this double-up requirement.

Fix another sub-100m zone fuzzed accuracy enter issue

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/ClientEvents/LocationHistoryDetailViewController.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Eureka/ButtonRowWithLoading.swift
Sources/App/Settings/Sensors/SensorListViewController.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/WebView/WebViewController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/LocationHistory.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift
Sources/Shared/Location/CLLocationManager+OneShotLocation.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Settings/SettingsStore.swift
Tests/Shared/CLLocationManager+OneShotLocationTests.swift

Updates to reduced location accuracy, manual updates, and error message display.
- Shows error messages on the bottom of the screen, with as much room as they need. Fixes #311.
- Allows the reduced accuracy setting to send those poor accuracy results to the server. This should cut down on people who accidentally disabled full but don't realize it; seeing a location update with 3km precision should hopefully let 'em know.
- Adds a "Update Location" button to the Location settings.
- Updates the display of the "track_ios" hint (this one's for you Tom 😛).

Location updates for reduced accuracy

---

Sources/Extensions/Share/ShareViewController.swift

I can't figure out when this started crashing, maybe a recent Xcode release, but it crashes due to the `init(nibName:bundle:)` initializer not being generated when the `init(coder:)` initializer is marked as unavailable. Strange. It crashes not just on the latest iOS 14 but also in iOS 13, so it's almost certainly a generated code and not runtime issue.

Fix crash in share extension

---

Sources/App/Notifications/NotificationManager.swift

Fixes #258. Depends on home-assistant/mobile-apps-fcm-push#48 which adds support for the command.
Adds `clear_notification` to remove notifications. This behaves like Android which can only clear based on the `tag`/`collapse-id`.
- Documentation: home-assistant/companion.home-assistant#497
This may be unreliable as it depends on the app launching in the background to do the actual clear.

Add app support for clear_notification command

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/NotificationContent/CameraStreamHLSViewController.swift
Sources/Extensions/NotificationContent/CameraStreamHandler.swift
Sources/Extensions/NotificationContent/CameraStreamMJPEGViewController.swift
Sources/Extensions/NotificationContent/ImageAttachmentViewController.swift
Sources/Extensions/NotificationContent/NotificationViewController.swift
Sources/Shared/Common/Extensions/NSLayoutConstraint+Additions.swift

Refs #1591.
Adds support for using image notification attachments in the content extension.
Dynamic actions require the 'DYNAMIC' category but our content extension causes attachments to not appear and we want every possible feature to work with just this category.

Static image attachments in dynamic category

---

HomeAssistant.xcodeproj/project.pbxproj
HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-NotificationContent.xcscheme
Sources/Extensions/NotificationContent/CameraStreamHLSViewController.swift
Sources/Extensions/NotificationContent/NotificationViewController.swift
Sources/Extensions/NotificationContent/VideoAudioAttachmentViewController.swift

Fixes #1591.
Adds support for using video and audio notification attachments in the content extension, including audio playback for both.
https://user-images.githubusercontent.com/74188/115503572-7c70e900-a22b-11eb-970b-b4e9c2225986.mov
Dynamic actions require the 'DYNAMIC' category but our content extension causes attachments to not appear and we want every possible feature to work with just this category.

Static video/audio attachments in dynamic category

---

Sources/App/Notifications/NotificationManager.swift
Sources/Shared/Notifications/UNNotificationContent+Additions.swift

Fixes #1593.
Suffixes the given identifiers with a consistent string, split when sending anywhere.
Since Android requires an action identifier of 'URI' to open URLs, users may enter more than 1 in the actions array; this fixes using just the first matching identifier.

Handle multiple dynamic actions with the same identifier

---

Sources/App/Resources/WebSocketBridge.js

Fixes #1493.
When page zoom is smaller than 100%, setting the minimum/maximum scale to 1.0 causes the layout to break.
| -- | -- |
| <img width="350" src="https://user-images.githubusercontent.com/74188/116007536-0e2e7c80-a5c5-11eb-85bb-bdb4a0da6092.png"> | <img width="350" src="https://user-images.githubusercontent.com/74188/116007539-15558a80-a5c5-11eb-8b80-e10425937267.png"> |
If the user transitions from pinch-to-zoom to not pinch-to-zoom, this will no longer reset any pre-existing pinched zoom. At least on iOS 13 and 14, you can un-pinch-to-zoom and it'll lock in at the regular scale afterwards, but only if you do not do it with the sidebar open; that will then require a refresh.

Fix scaling issue with page zoom < 100% and pinch-to-zoom disabled

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/NotificationContent/CameraViewController.swift
Sources/Extensions/NotificationContent/ImageAttachmentViewController.swift
Sources/Extensions/NotificationContent/MapViewController.swift
Sources/Extensions/NotificationContent/NotificationLoadingViewController.swift
Sources/Extensions/NotificationContent/NotificationViewController.swift
Sources/Extensions/NotificationContent/VideoAudioAttachmentViewController.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentManager.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentParser.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentParserCamera.swift
Sources/Shared/Notifications/NotificationAttachments/NotificationAttachmentParserURL.swift
Tests/Shared/NotificationAttachment/NotificationAttachmentManager.test.swift
Tests/Shared/NotificationAttachment/NotificationAttachmentParserCamera.test.swift
Tests/Shared/NotificationAttachment/NotificationAttachmentParserURL.test.swift

Allows attachments to be loaded on-the-fly in the content extension if they are not present.
Documentation: home-assistant/companion.home-assistant#510
- Adds `lazy` as an option to the `attachment` dictionary. When true, this prevents the attachment from being downloaded except when displayed in the content extension.  
This is similar, but not identical, to hide-thumbnail. Hiding the thumbnail still uses the internal storage of the notifications which are limited to e.g. 50mb. However, we'd still want to pre-load those attachments even if the thumbnail is hidden.
- Retries non-lazy attachments which failed due to a network error when the content extension opens.

Support attachments which aren't downloaded in advance

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/NotificationContent/Resources/TestNotifications/dynamic_notification.apns
Sources/Extensions/Watch/CameraNotificationController.swift
Sources/Extensions/Watch/DynamicNotificationController.swift
Sources/Extensions/Watch/MapNotificationController.swift
Sources/Extensions/Watch/Utilities/WKInterfaceLabel+Additions.swift
Sources/WatchApp/Base.lproj/Interface.storyboard

Fixes #1612.
Sets the number of lines to 0, and to make the group prettier also hides the labels when empty.

Fix watch notifications not handling multi-line

---

Sources/App/AppDelegate.swift
Sources/App/Notifications/NotificationManager.swift
Sources/Extensions/Watch/ExtensionDelegate.swift
Sources/Shared/API/HAAPI.swift

Fixes #1604.
Dynamic actions -- unlike category-based -- appear to never forward their action handling to the iOS app, despite what the documentation says. Adds tooling to do call it manually.
Not setting the notification delegate doesn't resolve this, either -- it doesn't appear we're doing anything unexpected, this is just an undocumented/rarely-used area, I guess.

Fix events not firing from watch dynamic notification actions

---

Sources/App/Settings/AppleWatch/ComplicationEditViewController.swift
Sources/App/Settings/Eureka/HAFormViewController.swift
Sources/App/Settings/Eureka/TemplateSection.swift

Prevents the keyboard from immediately dismissing on scroll, allows scrolling on the text view.
This is potentially a bug in the future if drag-start triggers some side effect in Eureka, but eh…seems unlikely.

Fix keyboard and scroll handling in template editing

---

Sources/App/Settings/Observation/NotificationCategory+Observation.swift

Until the notification content extension is loadable on Mac, this is a misleading button.
Even with a working content extension, you have to click the well-hidden chevron to expose the actions for it to actually load the possible actions, making the notification banner completely useless and this loading action even moreso.

Remove 'loading actions' from DYNAMIC on Catalyst

---

Configuration/HomeAssistant.xcconfig
HomeAssistant.xcodeproj/project.pbxproj

Without the prefix, crash logs for example show up as `Extensions-NotificationContent` which gives little indication what app it's from. This should help in error reporting.
The app itself, Shared and MacBridge are staying how they are now.

Prefix extensions/executables with HomeAssistant

---

Sources/App/ClientEvents/LocationHistoryDetailViewController.swift
Sources/App/ZoneManager/ZoneManagerIgnoreReason.swift
Sources/App/ZoneManager/ZoneManagerProcessor.swift
Tests/App/ZoneManager/ZoneManagerProcessor.test.swift

Fixes #1620.
Prevents doing a location update just after a region event -- within 30 seconds. Region events may have accuracy fuzzing which the significant location change wouldn't know about, so it would override the fuzz. Region events are never prevented.
This also makes processor events queue up rather than all executing simultaneously, both so we can make sure we don't do this error case and so we don't have other weird state transitions that I can't think of.

Fix location change overriding recent region changes

---

Sources/App/ZoneManager/ZoneManagerAccuracyFuzzer.swift
Sources/App/ZoneManager/ZoneManagerProcessor.swift
Sources/Shared/Common/Extensions/CLLocation+Extensions.swift
Tests/App/ZoneManager/ZoneManagerProcessor.test.swift
Tests/Shared/CLLocation+Extensions.test.swift

Fixes #1627.
When a GPS coordinate is outside the zone, even if accuracy places it inside, the logic in core will prefer a zone which contains the exact coordinates, regardless of accuracy. This moves the coordinate over to be inside the zone.
- Allows fuzzers to change coordinate, even though we really do not want to do this. This is effectively fudging the real location data, which is something I've avoided as much as possible to this point.
- Adds a helper method to determine bearing to another location so that we know how to adjust the position towards the center of the zone.

Fixes zone enter with multiple overlapping zones where core ignores accuracy

---

Sources/App/Settings/SettingsDetailViewController.swift
Sources/Shared/Settings/SettingsStore.swift

Disables crash reporting and analytics by default.
| -- | -- |
| ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-03 at 15 50 53](https://user-images.githubusercontent.com/74188/120721844-82d9be00-c483-11eb-960e-bd3a3b915211.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-03 at 15 50 55](https://user-images.githubusercontent.com/74188/120721846-866d4500-c483-11eb-83ab-675212011995.png) |
- Users who have changed _any_ privacy setting have all of the values persisted, but users who have never done so will now find crash reporting and analytics disabled.
- Crash reporting being disabled explicitly prevents any communication with Sentry.
- Analytics doesn't actually do anything other than control whether error/warning logs are sent to Sentry if a crash occurs, so …

Change crash reporting & analytics to opt-in

---

Sources/App/Onboarding/ConnectInstanceViewController.swift
Sources/Shared/API/Authentication/AuthenticationAPI.swift
Sources/Shared/API/Authentication/TokenManager.swift

Resolves #1542.
Logs the error code we get when refreshing a token and log out if we encounter a 403 during token refresh.
- Fixes an auth handling issue where the WebSocket connection doesn't connect initially.
- Logs out when we encounter a 403 during token refresh. Only a few auth providers do this; specifically, the `trusted_networks` one will reject token refreshes for auth tokens it vends when not on the trusted network. Otherwise, we'll keep retrying and end up getting banned (if enabled).
- Includes the error that we get into the event log so we can trace back the failure easily.

Improve handling around refresh token errors

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/Resources/Info.plist
Sources/Extensions/Intents/Resources/Info.plist

Moves INShareFocusStatusIntent to be inserted dynamically at build time for non-Xcode 12 only. ASC's build upload fails if we include this intent in a build from a too-old Xcode.

Fix distribute using Xcode 12 due to too-new intents

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Shared/Notifications/LocalPush/UserDefaultsValueSync.swift
Tests/Shared/UserDefaultsValueSync.test.swift

Old-style KVO requires manually removing observations, of course, otherwise it'll hit random memory and crash.

Fix crash in push provider when stop/start

---

Podfile.lock

Fixes the local push subscription failing if it connects while HA is restarting, before mobile_app is loaded.

Bump HAKit for local push improvement

---

Sources/Extensions/PushProvider/PushProvider.swift

This may make turning off Wi-Fi a little bit more reliable. Or not, it doesn't seem to get called. Maybe in the future.

Immediately disconnect in PushProvider when asked to stop

---

Sources/Shared/Common/Extensions/XCGLogger+UNNotification.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Location/CLLocationManager+OneShotLocation.swift

Looks like iOS 15 (and maybe earlier) will crash if we try and ask for background updates in the extension.

Fix crash in background in push provider from update_location call

---

Sources/Shared/Common/Extensions/URL+Extensions.swift

If a URL is specified like `http://localhost:80` then WKWebView will eat the port, and we'll assume the URL being displayed is always one that needs to be mutated due to settings or internal/external change when the app enters foreground.

Fix active URL check failing if port was specified as 80/443

---

Sources/App/Notifications/NotificationManager.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Notifications/NotificationSettingsViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Settings/SettingsStore.swift

Adds a setting (defaulted on) to reset the badge to 0 when launching the app.
| -- | -- |
| ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-25 at 10 23 38](https://user-images.githubusercontent.com/74188/123462674-72f35c80-d59f-11eb-93d7-eaa021a021a2.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-25 at 10 23 40](https://user-images.githubusercontent.com/74188/123462699-7a1a6a80-d59f-11eb-9e23-238b7265e853.png) |
Documentation: home-assistant/companion.home-assistant#549
This is the general behavior on most iOS apps, and should make micro-managing the badge a little easier.

Reset badge to 0 automatically when opening the app

---

Sources/App/ZoneManager/ZoneManagerAccuracyFuzzer.swift

Refs #1693. I'm pretty sure it's not fuzzing location or accuracy in these cases, but I can't be 100% sure.
Hopefully makes some location things easier to see when looking at logs.

Log about accuracy/coordinate fuzzing when occurring

---

Sources/App/ZoneManager/ZoneManagerAccuracyFuzzer.swift
Sources/Shared/API/Models/RealmZone.swift
Tests/App/ZoneManager/ZoneManagerProcessor.test.swift

Fixes #1693.
When we fuzz the coordinate to deal with zone overlap issues in core, we need to also take into account whether we're actually in the zone we'd be fuzzing coordinate to. For zones >=100m, this is the region, but for smaller zones we need to make sure all of the monitored regions agree before changing coordinate.

Fix incorrectly entering a <100m zone whose regions intersect a nearby zone

---

Configuration/Scripts/fix_xcode_12.5_target_platform_issues.sh
HomeAssistant.xcodeproj/project.pbxproj

Works around Xcode 12.5 / 13.0 (beta 1/2 at least) regressions in target launching.
When running tests for iOS simulator, we get an error like:
> The bundle identifier for Home Assistant Launcher.app couldn’t be read. No such file or directory: “/Users/zac/Library/Developer/Xcode/DerivedData/HomeAssistant-ahjyjjgpphztaebycwnsuwmrdiho/Build/Products/Debug/Home Assistant Launcher.app”.
The Launcher.app target is set to macOS only, so it's not built for iOS simulator. Building it first then executing tests works, so clearly Xcode is incorrectly trying to analyze the target when it isn't used.
This also happens when building for Catalyst, where it can't find the watchOS app which isn't being compiled since it is iOS only:
> The bundle identifier for HomeAssistant-WatchApp.app couldn’t be …

Fix tests and Watch App execution in Xcode 12.5

---

HomeAssistant.xcodeproj/project.pbxproj
Podfile.lock

Fixes flooding the logs with "Received invalid command: mobile_app/push_notification_channel" when HA is restarting.

Bump HAKit for re-subscription delay

---

Sources/Extensions/NotificationContent/ImageAttachmentViewController.swift

Fixes #1709.
Loads a webview to play back gif attachments, since they may be animated and UIImageView doesn't handle that for us.
Due to sandboxing and security scoping, getting this to display reliably is a little convoluted - we need to load by Data and inject a CSS style to get the image to scale as we want, since we size the webview to fit based on aspect fit rules.

Fix playback of animated GIFs in notification content extension

---

Sources/Extensions/PushProvider/PushProvider.swift
Sources/Shared/Notifications/LocalPush/LocalPushManager.swift
Tests/Shared/LocalPushManager.test.swift

Refs #1799.
I can't see too many cases where we'd drop a subscription, but this is one of them - basically, multiple connection info change notifications fire at once, and the invoked method isn't threadsafe.
Also adds some more logging and discrete subscription cancelling when stopping to hopefully help debug this in the future if it continues.

Possibly fix phantom local push subscription not alerting

---

Sources/App/Settings/Sensors/SensorDetailViewController.swift
Sources/Shared/API/Webhook/Sensors/ActiveSensor.swift

Fixes a crash caused by infinitely recursing the value change.
This also allows setting fractional minute values, every 15 seconds. The minimum timer which we check is 5 seconds, and that low means we won't detect changes if they occur in a 10 second period which feels too low.

Fix crash updating active sensor idle time setting

---

Sources/Shared/Location/CLLocationManager+OneShotLocation.swift
Tests/Shared/CLLocationManager+OneShotLocationTests.swift

Refs [a forum post](https://community.home-assistant.io/t/ios-15-location-issues/323498).
iOS 15 appears to give us extremely small values for longitude like `9.368162246e-315`, which we should throw away as invalid.
I reduced the logging we do for longitude/latitude, but we don't send it anywhere anymore (since only errors go up to Sentry on crash), so I'm adding it back in so I can see in future logs what's happening. Some of the logs from the user show the invalid value happening _multiple_ times and I just can't tell if we're butchering it from the raw, or if the raw coming in is bad. This should help.

Handle invalidly close to 0.0 latitude/longitude as invalid too

---

Configuration/Podspecs/NotificationTestCases.podspec.json
Podfile.lock
Sources/Shared/Notifications/LocalPush/NotificationParserLegacy.swift

Refs home-assistant/mobile-apps-fcm-push#58, refs home-assistant/mobile-apps-fcm-push#57.
Updates the test dependency and makes the new cases pass: badge with commands, clear_badge not using a command (this one doesn't matter for local push, however).

Update local push parsing for recent fcm changes

---

Sources/Extensions/Intents/FocusStatusIntentHandler.swift
Sources/Shared/API/Webhook/Sensors/FocusSensor.swift
Sources/Shared/Environment/FocusStatusWrapper.swift
Tests/Shared/Sensors/FocusSensor.test.swift

Fixes the insta-updating of the focus sensor on iOS 15.
`INFocusStatusCenter.default.focusStatus` always returns isFocused=false in the extension, but the intent provides the correct focus status for each update -- so we need to cache this value in the extension, and not trust the focus center state.

Fix focus sensor updating in iOS 15 RC

---

Sources/Shared/Environment/FocusStatusWrapper.swift

Fixes `INFocusStatus` not being available in Xcode 13 for Catalyst.
This whole "you can only develop for Monterey using Xcode 13's earlier betas" schtick is just frustrating.

Fix Mac compilation in Xcode 13 RC

---

Sources/Shared/API/Webhook/Sensors/LastUpdateSensor.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift
Sources/Shared/Iconic/MDIMigration.swift
Sources/Shared/Iconic/MaterialDesignIcons.swift
Tests/Shared/Sensors/LastUpdateSensor.test.swift
Tools/BuildMaterialDesignIconsFont.sh

- Upgrades the font, config, and adds a migration for renamed/removed icons.
- Migrates the one use of a renamed/removed one: `laptop-mac` -> `laptop`
This change should also make it a little easier to do the migrations, since the Realm+Initialization part won't need to be touched, probably.

Upgrade MaterialDesignIcons to 6.1.95

---

Sources/Shared/API/Webhook/Sensors/FocusSensor.swift
Sources/Shared/Environment/FocusStatusWrapper.swift
Sources/Shared/Notifications/LocalPush/UserDefaultsValueSync.swift
Tests/Shared/Sensors/FocusSensor.test.swift

Fires a sensor update pass if the app is running when the focus status changes.
The focus sensor _always_ live-updates, but it does so in the Intents extension. This allows the Intents extension to inform the app that it did an update, which (unfortunately, for now) fires a sensor update pass in the app. So we're over-updating the sensors, but we're keeping the in-app sensor list updated. Worth the cost, I think, since the app running when focus changes happening feels rare unless the user's playing with the sensor.

Add live-updating to in-app display of focus sensor

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/NotificationContent/MapViewController.swift
Sources/Extensions/NotificationContent/NotificationViewController.swift
Sources/Extensions/NotificationContent/VideoAudioAttachmentViewController.swift

Fixes #1592.
Enables the Notification Content extension now that it works in Xcode 13.
This is an entirely tooling enabling of this feature, as the extension works on macOS 11. There is a gotcha: the Notification Service Extension attachments are inaccessible. Additionally, macOS always displays the attached-by-us images/movies, which is a frustrating difference in behavior between macOS and iOS, but makes this particular deficiency less noticeable. Filed as FB9638431.

Enable Notification Content extension on macOS 11+

---

Sources/Shared/API/Models/NotificationAction.swift
Sources/Shared/API/Responses/MobileAppConfig.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift

Fixes #1657.
Adds the `icon` key to actionable notifications' actions, which must be `sfsymbols:`-prefixed strings of SFSymbols names.
With a payload that looks like…
```js
{
/* … */
"actions": [
{
"action": "SOUND_ALARM",
"title": "Sound Alarm",
"icon": "sfsymbols:bell",
},
{
"action": "SILENCE_ALARM",
"title": "Silence Alarm",
"icon": "sfsymbols:bell.slash",
}
]
}
```
| Dark | Light |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/74188/134095088-554f48e9-fe65-417f-9aa5-59c408299da9.png) | ![image](https://user-images.githubusercontent.com/74188/134095094-debd4625-b60c-4dda-ac92-8ac0f5b44c5e.png) |
Documentation: home-assistant/companion.home-assistant#577
Apple requires that these icons either be pre-baked asset catalog assets, or part of the SFSymbols library …

Add icons to dynamic notification actions

---

Sources/App/Onboarding/PermissionButton.swift
Sources/App/Onboarding/PermissionLineItemView.swift
Sources/App/Onboarding/PermissionsViewController.swift
Sources/App/Resources/Base.lproj/Onboarding.storyboard
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Sensors/SensorListViewController.swift
Sources/App/Utilities/Permissions.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Environment/FocusStatusWrapper.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Refs #945.
Adds the Focus permission to the onboarding permission screen and cleans up some of the views there.
https://user-images.githubusercontent.com/74188/134089206-2786d6f0-9cba-43bc-abcb-1e3267f53b61.mov
- Makes a lot of the strings here localizable which were not before.
- Doesn't yet have a unique Lottie animation for the focus permission.
- Fixes tapping a denied permission, now opens Settings app.
- Fixes some of the text getting truncated or hidden because of the number-of-lines requirements.

Add Focus permission to onboarding

---

Sources/Shared/API/Models/NotificationAction.swift
Sources/Shared/Environment/FocusStatusWrapper.swift

Once again fixes Mac compilation on the Xcode 13 RC.
The build failures will continue until morale improves.

Fix, once again, compiling for Mac

---

Sources/App/WebView/WebViewController.swift

Fixes #1671.
Always allows access to to the camera and microphone via `navigator.mediaDevices.getUserMedia`.
Since this is gated on the app-level system permission for Camera and Microphone, it feels silly to require the user to allow access to them during the normal app runtime - this is exclusively a weird WebView behavior-ism. Also doesn't feel worth making this a preference - if users don't want the frontend to access it, it seems to me like the app-level permission is enough.
Tested this by using e.g. [the WebRTC samples](https://webrtc.github.io/samples/): going to a video or audio or both test page, after granting app permission, successfully starts right away.

Always allow media capture in frontend

---

.github/workflows/ci.yml
README.md

The simulator app can be useful for non-developers to test things, since setting up the build environment can be a hassle.
This CI workflow (very intentionally) doesn't include _any_ credentials or secrets, so the outputs cannot possibly include anything secret.

Upload built simulator app after running tests

---

Sources/App/AppDelegate.swift
Sources/App/LifecycleManager.swift
Sources/Shared/API/Webhook/Sensors/FocusSensor.swift
Sources/Shared/Environment/Environment.swift
Tests/Shared/Sensors/FocusSensor.test.swift

Fixes unnecessarily doing a sensor update pass when launching in the background, as well as an occasional crash talking to UIApplication's applicationState off the main thread.

Only signal focus sensor updates in the foreground

---

Sources/App/Resources/Base.lproj/Intents.intentdefinition
Sources/Extensions/Widgets/Actions/WidgetActions.swift
Sources/Extensions/Widgets/Actions/WidgetActionsActionView.swift
Sources/Extensions/Widgets/Actions/WidgetActionsContainerView.swift

This updates our maximum action count per size, adding extra large:
| Family | Old Maximum | New Maximum Count |
| Small | 1 | 1 |
| Medium | 4 | 8 |
| Large | 8 | 16 |
| Extra Large (new) | n/a | 32 |
Extra Large is approximately 2 'Large' stacked horizontally, so we extend this into 3 (for ≤15 items) or 4 columns, depending on item count.
| Kind | Image |
| -- | -- |
| Maximum | ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2021-09-25 at 20 17 55](https://user-images.githubusercontent.com/74188/134792223-a83bbee7-7a6c-407f-864f-3c87cd3caee3.png) |
| Old Maximum | ![simulator_screenshot_6AD05BE4-7D54-4B83-8FD1-A1C110EAD0B6](https://user-images.githubusercontent.com/74188/134792289-37200bce-220d-4938-82b1-d4b6545ff3e8.png) |
Documentation: …

Permit more actions in widgets, support extra large on iPadOS 15

---

Sources/Extensions/Widgets/Actions/WidgetActions.swift
Sources/Extensions/Widgets/Common/WidgetBasicView.swift
Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift
Sources/Shared/API/WebSocket/HAPanel.swift
Sources/Shared/Common/Extensions/UIImage+Icons.swift
Sources/Shared/Common/SiriIntents+ConvenienceInits.swift
Sources/Shared/Iconic/MaterialDesignIcons.swift
Tools/icons.stencil

- Fixes e.g. HACS (which is `hacs:hacs`) icons showing the A/B icon. We now fall back to the outline cog.
- Hide panels without the "show in sidebar" option. We get them in the response, but e.g. the title is incorrect.
- Changes sort order in the automatic version to more closely align with the frontend.
- Fixes a case where chosen panels in the past would fail to be updated due to being at the tail end of the array in the API response, due to truncating to widget size _before_ updating.

Minor fixes for open page widget

---

Sources/App/AppDelegate.swift
Sources/App/ClientEvents/ClientEventTableViewController.swift
Sources/App/ClientEvents/LocationHistoryListViewController.swift
Sources/App/Settings/AppleWatch/ComplicationEditViewController.swift
Sources/App/Settings/Notifications/NotificationActionConfigurator.swift
Sources/App/Settings/Notifications/NotificationCategoryConfigurator.swift
Sources/App/Settings/Notifications/NotificationCategoryListViewController.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/ZoneManager/ZoneManager.swift
Sources/App/ZoneManager/ZoneManagerIgnoreReason.swift
Sources/App/ZoneManager/ZoneManagerProcessor.swift
Sources/App/ZoneManager/ZoneManagerRegionFilter.swift
Sources/Extensions/Watch/ExtensionDelegate.swift
Sources/Shared/API/Authentication/TokenManager.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/ModelManager.swift
Sources/Shared/API/Models/RealmZone.swift
Sources/Shared/API/Webhook/Networking/Promise+WebhookJson.swift
Sources/Shared/API/Webhook/Networking/WebhookResponseLocation.swift
Sources/Shared/API/Webhook/Networking/WebhookResponseServiceCall.swift
Sources/Shared/API/Webhook/Networking/WebhookResponseUpdateComplications.swift
Sources/Shared/ClientEvents/Model/ClientEventStore.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift
Sources/Shared/Location/CLLocationManager+OneShotLocation.swift
Tests/App/ZoneManager/ZoneManager.test.swift
Tests/Shared/ClientEventTests.swift
Tests/Shared/ModelManager.test.swift

Starting in iOS 15, there's a number of crashes happening in the background with Realm. They don't appear to be due to the file lock in the shared app container, but this may help resolve them either way -- easy to see if the next beta doesn't crash a bunch.

Try and fix Realm crashes via excessive background tasks

---

Sources/Shared/API/ConnectionInfo.swift

Fixes a crash where activeURL stack overflows itself when overriding active URL type without sufficient location privacy permission.
Pulls the ConnectionInfo activeURL changes from multi-server back to 2021.11.

Fix infinite loop in onboarding due to internal URL override

---

Sources/Shared/API/HAAPI.swift

If the API call to `mobile_app/registrations` fails due to a 404, explain that the component needs to be loaded. This likely, in the old flow, was erroring a bit more randomly on the final screen, as the same order of checks was happening.
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/74188/141503139-e09bf4fb-fafb-4743-ad14-34cd9c1bc923.png) | ![image](https://user-images.githubusercontent.com/74188/141503061-7712615f-21fd-45b9-8a83-8ddc67bb6721.png) |
This is the "Alamofire.AFError 9" error during onboarding _after_ logging in noted in [this forum post](https://community.home-assistant.io/t/ha-companion-app-alamofire-aferror-9/355504/11).
It is worth noting that this error message could be happening because the internal URL (or the URL …

Provide clearer error if mobile_app is not loaded during onboarding

---

Sources/App/Onboarding/API/OnboardingAuthDetails.swift
Sources/Shared/API/ConnectionInfo.swift
Sources/Shared/Common/Extensions/URL+Extensions.swift

Fixes receiving "Alamofire.AFError 9" with a response status code of 404 during onboarding when a URL like `http://192.168.1.3:8123/` (with trailing slash) is provided.
The real crux of this issue is that ConnectionInfo strips it, but the connectivity check in onboarding does not, giving us a URL like `http://92.168.1.3:8123//auth/authorize` which errors with a status code of 404.

Fix onboarding error 404 when URL has a trailing `/`

---

HomeAssistant.xcodeproj/project.pbxproj

Remove Launcher.app from Resources in built app. Its presence in Resources (as well as LoginItems) was causing issues, and it did not belong in Resources.

Fix Mac TestFlight build

---

Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/App/WebView/WebViewWindowController.swift

Shows onboarding when necessary, or switches to another server otherwise.
When deleting a server, resetting the app, logging out in the WebView, or being logged out due to token invalidation, we now either:
1. Change to another server in the WebView, if one is available, or
2. Show onboarding, like we did before when the only server was invalidated

Handle individual server deletion & logout

---

Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/ZoneManager/ZoneManagerCollector.swift
Sources/App/ZoneManager/ZoneManagerEvent.swift
Sources/App/ZoneManager/ZoneManagerRegionFilter.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/Action.swift
Sources/Shared/API/Models/ModelManager.swift
Sources/Shared/API/Models/NotificationCategory.swift
Sources/Shared/API/Models/RealmPersistable.swift
Sources/Shared/API/Models/RealmScene.swift
Sources/Shared/API/Models/RealmZone.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift
Tests/App/ZoneManager/ZoneManager.test.swift
Tests/App/ZoneManager/ZoneManagerCollector.test.swift
Tests/App/ZoneManager/ZoneManagerProcessor.test.swift
Tests/App/ZoneManager/ZoneManagerRegionFilter.test.swift
Tests/Shared/ModelManager.test.swift
Tests/Shared/RealmZone.test.swift
Tests/Shared/Sensors/GeocoderSensor.test.swift
Tests/Shared/Webhook/WebhookUpdateLocation.test.swift

Stores a zone from s1 in Realm like `s1/zone.name` rather than `zone.name` so it's distinct from `s2/zone.name`. This is most apparent for `zone.home` which universally conflicts.
This does not yet extend to the other synced models as we use their identifier in persisted locations that aren't programmatically changeable (e.g. action IDs are stored in intents). Zones don't pose such a problem, and are the most likely suspect to even have duplicates right now; scenes, actions, and deprecated notification categories can be done after an external beta.

Store zones by server, allowing duplicate entity ids

---

Sources/Shared/Common/Extensions/Realm+Initialization.swift

Fixes a crash because the old version (2021.11) didn't have serverIdentifier, just a transitive Realm version I was using (which did) which doesn't promote it to oldObject values.
😆

Fix crash when migrating from 2021.11 to 2021.12

---

fastlane/Fastfile

This has been timing out recently, which is a huge waste of compile time to have to manually run the action again

Retry uploads to Apple a few times if they fail

---

Sources/Shared/Settings/SettingsStore.swift

Need to fall back to any server if the server's gone. Other alternative is to reset the template to empty and pick a new server, but that felt a little bit more like losing the template unexpectedly.
This can also be temporarily fixed by editing `~/Library/Group Containers/group.io.robbie.homeassistant/Library/Preferences/group.io.robbie.homeassistant.plist` and removing the `menuItemTemplate-server` key.

Fix menu bar template when deleting server it was set to

---

Sources/Shared/API/Server.swift
Sources/Shared/API/ServerManager.swift

Fixes regression from #1941.
The default value of `.max` isn't adjusted to a real one until after onboarding is finished, but we do a model fetch _during_ onboarding to test that it works.

Fix crash adding new server with scene actions

---

Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Server.swift
Tests/Shared/Server.test.swift

Changes the server name row into an editable one, persists along with the server and uses it everywhere. Basically identical to 'device name' in functionality there.
Also hides the 'activate' button if there's only one server.
| ----- | ---- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-28 at 14 32 16](https://user-images.githubusercontent.com/74188/143788804-400475b0-44eb-4f73-a105-861f1a3cc9ae.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-28 at 14 31 57](https://user-images.githubusercontent.com/74188/143788806-7f586477-7e2f-41e2-bdb3-0b49c28a7895.png) |
| ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-28 at 14 32 11](https://user-images.githubusercontent.com/74188/143788813-9fcf7bce-97e4-4def-98db-a52a415f31bc.png) | ![Simulator Screen Shot - …

Changeable local name for servers

---

Sources/App/Settings/Eureka/ServerSelectRow.swift
Sources/Shared/API/Models/Action.swift

Fixes bad logic in the "can server identifier be edited?" check, and colors the detail label of the server select row like a field row in other Eureka contexts.
| Thing   | Light | Dark |
| ------- | ----- | ---- |
| Scene   | ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-29 at 19 04 58](https://user-images.githubusercontent.com/74188/143978645-efa59759-a08b-4a85-b3e9-ac418a952f54.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-29 at 19 04 56](https://user-images.githubusercontent.com/74188/143978665-b1c176b4-ef83-48b6-8fbb-e23573e1bf78.png) |
| Synced  | ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-29 at 19 04 50](https://user-images.githubusercontent.com/74188/143978853-3688885b-d849-4914-99fe-b3d7506b3f77.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-29 at …

Fix server seeming to be editable for scene actions & color when disabled

---

Sources/Shared/API/ServerManager.swift
Tests/Shared/ServerManager.test.swift

A deleted server could end up re-saved if modified by something just after it's being deleted; e.g., a network connection change or whatnot.

Fix deleted server being modified resurrecting it

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/App/WebView/WebViewWindowController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Adds a two-finger left/right swipe gesture to go left/right between servers. Caches the WebView when switching, which makes swiping back and forth significantly faster. Shows the name of the server as it switches.
| Thing | Light | Dark |
| ----- | ----- | ---- |
| Settings | ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-29 at 20 57 27](https://user-images.githubusercontent.com/74188/143988210-06ba5d9f-8a3b-4c02-afcd-90df3a39b01b.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-29 at 20 57 28](https://user-images.githubusercontent.com/74188/143988218-b7245caa-d9a9-4aff-ba7c-2a494c21474d.png) |
| Switching | ![Simulator Screen Shot - iPhone 13 Pro - 2021-11-29 at 20 58 36](https://user-images.githubusercontent.com/74188/143988298-75844447-a7f5-446a-bfd4-44cc8a7f6300.png) | …

Two-finger swipe to switch servers

---

Sources/App/Utilities/Permissions.swift

Refs #1919 (and may fix it).
Checks whether Location Services are enabled before checking the authorization status.
Best as I can tell, whenever it's disabled globally, we get 'denied' as the status back. It's possible some environments on Mac (likely which are patching/overriding location services or something) do not keep this constraint.

Check location services enabled status in onboarding permissions

---

Sources/App/Onboarding/API/OnboardingAuthLogin.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/Shared/Resources/Swiftgen/Strings.swift
Tests/App/Auth/OnboardingAuthLoginImpl.test.swift

Fixes #1951.
Alert that we're opening Safari for login after a few seconds of waiting (so it's not distracting as Safari normally opens it). This alert dismisses on its own when cancelling or completing login, so 'cancel' is its only choice.
| Scanning | Manual |
| -------- | ------ |
| <img width="712" alt="image" src="https://user-images.githubusercontent.com/74188/144169514-08690d60-873f-45f1-a4e9-7bc11914b411.png"> | <img width="712" alt="image" src="https://user-images.githubusercontent.com/74188/144169633-9b811ed6-48db-4ea1-949e-16fa3071254f.png"> |

Show an alert on macOS when opening web auth session

---

Sources/App/WebView/WebViewController.swift
Sources/App/WebView/WebViewWindowController.swift

- Changes the swipe gesture to switch between servers to require 3 fingers.
- Adds forward/back gestures when using 2 fingers.
- Allows swiping when the swipe HUD is shown, so you can spam it fast.

Add two-finger swipe to go forward/back, change server to three-finger

---

Sources/App/Onboarding/API/OnboardingAuth.swift
Sources/Shared/API/ConnectionInfo.swift
Tests/App/Auth/OnboardingAuth.test.swift

Regressed in new onboarding; old onboarding did this during the final checklist screen, which no longer exists.

Fix cloud not enabling by default in onboarding

---

Sources/App/Onboarding/API/OnboardingAuthError.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/Shared/Resources/Swiftgen/Strings.swift

Augments the internet offline error with a hint about the permission.

Add hint about local network permission to internet offline error

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Shared/API/ConnectionInfo.swift
Sources/Shared/Environment/ConnectivityWrapper.swift
Tests/App/Auth/OnboardingAuth.test.swift
Tests/Shared/ConnectionInfo.test.swift

Fixes #1918.
During initial onboarding (or even after the fact), we don't have permission to read SSID values due to Location permission occurring later. When only an internal URL was set, we were falling back to homeassistant.local.:8123 which is possibly not valid, rather than using the one we slurped from discovery info.
Manually entering a URL worked here because it sets the value as 'external URL' which didn't have this issue.

Fix onboarding timeout when only internal URL is set and we lack SSID info

---

Sources/Shared/Environment/Environment.swift

In iOS/macOS extensions, prefer using the immediate webhook session rather than the background session as XPC in extensions to urlsessiond is a bit spotty.
This may fix errors like "Could not communicate with background transfer service" in Shortcuts.

Stop using background sessions in extensions by default on iOS

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/AppDelegate.swift
Sources/App/Resources/Info.plist
Sources/Extensions/Intents/IntentHandler.swift
Sources/Extensions/Intents/Resources/Info.plist
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Webhook/Sensors/SensorContainer.swift
Sources/Shared/Common/SiriIntents+ConvenienceInits.swift
Sources/Shared/Intents/CallServiceIntentHandler.swift
Sources/Shared/Intents/FireEventIntentHandler.swift
Sources/Shared/Intents/FocusStatusIntentHandler.swift
Sources/Shared/Intents/GetCameraImageIntentHandler.swift
Sources/Shared/Intents/IntentHandlerFactory.swift
Sources/Shared/Intents/OpenPageIntentHandler.swift
Sources/Shared/Intents/PerformActionIntentHandler.swift
Sources/Shared/Intents/PickAServerError.swift
Sources/Shared/Intents/RenderTemplateIntentHandler.swift
Sources/Shared/Intents/RoutingIntentHandler.swift
Sources/Shared/Intents/SendLocationIntentHandler.swift
Sources/Shared/Intents/UpdateSensorsIntentHandler.swift
Sources/Shared/Intents/WidgetActionsIntentHandler.swift
Tests/Shared/Sensors/SensorContainer.test.swift

- Stops caching of sensor values and now sends them to the server regardless if we think they have changed. Fixes #1473. The sensor container was (a) prone to issues (as it could not fully capture network semantics) and (b) not updated for multi-server support.
- Moves all intent handling that I can into the app for iOS 14+ / macOS 11+. The only intent that must be in the extension is the focus intent, which now strictly updates just the focus sensor on macOS, since it did not have access to all sensor values. Fixes #1921.

Fix cases of sending invalid sensor values on macOS

---

Sources/App/Settings/Eureka/AccountInitialsImage.swift

The images were being draw at something like `40.53x40.53` which, unsurprisingly, can cause some aliasing issues.
| ------ | ----- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2021-12-05 at 15 02 27](https://user-images.githubusercontent.com/74188/144767927-d5812c04-f380-4ffe-8f35-bc675d5868c9.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2021-12-05 at 15 01 59](https://user-images.githubusercontent.com/74188/144767925-7d58be25-9d85-4354-aa78-fda2413e5455.png) |
This depends on the image contents or dynamic type font setting whether this reproduces.

Fix avatar showing a black line on some edges

---

Sources/Shared/API/Models/WatchComplication.swift

Fixes #1955.
We were not updating any complications watch-side, so any updates exclusively came from the iOS app's updating them.
Complications weren't syncing over to the watch with their serverIdentifier value set, so when we went to update none of the API instances thought their server had any complications needing updating.

Fix complications not updating in 2021.12

---

Sources/App/AppDelegate.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/Shared/Resources/Swiftgen/Strings.swift

Alerts if there are any notification categories (local or synced) if the user is an admin on any of their servers.
The configuration is marked as deprecated in home-assistant/core#61078 and will produce warnings until it's removed from there as well.
| ----- | ---- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2021-12-05 at 22 32 20](https://user-images.githubusercontent.com/74188/144798997-e105d578-535b-45fd-a7aa-3679ba0b5949.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2021-12-05 at 22 32 21](https://user-images.githubusercontent.com/74188/144799004-6139960c-e07c-4613-b992-8a4282aa6b4b.png) |

Add deprecation alert for notification categories

---

Sources/App/WebView/WebViewController.swift
Sources/Shared/API/WebSocket/WebSocketMessage.swift
Sources/Shared/Environment/Constants.swift

Fixes #1801 by working around the Apple bug.
Refs home-assistant/frontend#10819.
Requires core-2021.12.0b6 or newer.
When the app has been in the background for a while without executing, reset the WebSocket connection in the WebView when execution begins again.
Also implements the new `theme-update` external bus command since it will log as an unhandled message. This likely means we're over-updating theme colors, but that is relatively cheap to do and doesn't cause harm.
This works around a bug in NSURLSession's WebSocket implementation -- which WKWebView moved to in iOS 15 -- where it cannot reliably detect network connectivity failures due to extended backgrounding. Eventually it'll get a "connection reset by peer" or other error, but in the meantime it reports itself as still …

Reconnect if the WebView WebSocket connection is likely disconnected

---

.github/workflows/ci.yml
.github/workflows/distribute.yml
Podfile
Podfile.lock

Fixes #1983.
Apple broke the bitcode recompilation pipeline for versions of iOS before iOS 15 (when concurrency was introduced) when apps aren't yet built with 13.2. This hopefully resolves the crash on launch their regression has introduced in TestFlight.

Bump to Xcode 13.2 in CI

---

Sources/Shared/API/Server.swift
Tests/Shared/ServerManager.test.swift

Changing the version wasn't considered enough of a change to update the value, so once the server version was initially set it couldn't change.
Extra relevant because the version check in #1987 is a very recent version.

Fix server version changes & sort order not persisting

---

Sources/Shared/API/Models/Action.swift
Sources/Shared/API/Models/ModelManager.swift
Sources/Shared/API/Models/NotificationCategory.swift
Sources/Shared/API/Models/RealmPersistable.swift
Sources/Shared/API/Models/RealmScene.swift
Sources/Shared/API/Models/RealmZone.swift
Tests/Shared/ModelManager.test.swift

When a server is deleted, we now update the identifiers of any locally-defined actions or complications to point to the first server. We want to avoid ever having a server identifier pointing to a deleted server so we can trust the identifiers more.
Deleting in this case would be bad as it's an unexpected data loss. I can imagine someone deletes and re-adds the server (potentially the last one, too), or other maintenance tasks.

Fix server identifier of non-synced actions & complications for deleted servers

---

Sources/Shared/API/ConnectionInfo.swift
Tests/Shared/ConnectionInfo.test.swift

I regressed this in the multi-server PR -- we want to still use the Cloudhook URL, even if remote UI isn't set up.

Use cloudhook URL if present on non-internal

---

Sources/App/Scenes/WebViewSceneDelegate.swift

The default behavior here is to open a second scene for the external display, but since you can't interact with it, it's not super useful.
We could maybe do something like:
- Offer to track the current page in the phone
- Add a setting to control which page to show, e.g. mirror or display
The upside of the second WebView scene is that it's at the full resolution of the device (e.g. at 1080p landscape, not whatever the phone is showing).

Decline opening a WebView for AirPlay to mirror instead

---

Sources/App/AppDelegate.swift

Turns out 2021.2 already happened, and I want to push it out a bit more.

Bump notification category deprecation to iOS-2022.4

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/RealmZone.swift
Sources/Shared/API/Models/WebhookUpdateLocation.swift
Sources/Shared/API/Server.swift
Sources/Shared/API/Webhook/Sensors/GeocoderSensor.swift
Sources/Shared/Common/ObjectMapperTransformers.swift
Sources/Shared/Environment/Constants.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Tests/Shared/Webhook/WebhookUpdateLocation.test.swift

Requires home-assistant/core#62243.
Allows sending exact locations (current behavior, gps coordinates), no locations (sets the device tracker to 'unknown' effectively), and zone-only locations (we send `home`, `other_zone_name` or `not_home` only).
| Thing | Light | Dark |
| Setting | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2021-12-20 at 13 55 29](https://user-images.githubusercontent.com/74188/146837890-d43d5427-9574-4d24-90b7-91c631f92ad0.png) | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2021-12-20 at 13 55 30](https://user-images.githubusercontent.com/74188/146837899-d3fd3879-61f9-4b8e-8d71-4032e0c96867.png) |
| New Enough | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2021-12-19 at 14 04 41](https://user-images.githubusercontent.com/74188/146692573-2 …

Setting for types of locations sent to a server

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/App/Settings/Sensors/SensorListViewController.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/WebView/WebViewController.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/WebhookSensor.swift
Sources/Shared/API/Server.swift
Sources/Shared/API/Webhook/Networking/WebhookResponseUpdateSensors.swift
Sources/Shared/API/Webhook/Sensors/SensorContainer.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Tests/Shared/Sensors/SensorContainer.test.swift
Tests/Shared/Webhook/WebhookResponseUpdateSensors.test.swift

When set to "None", all sensors sent to the server will be redacted.
| Thing | Light | Dark |
| Settings | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2021-12-20 at 21 59 01](https://user-images.githubusercontent.com/74188/146879285-d51cbe25-762f-459f-8ee2-6c3407620b1e.png) | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2021-12-20 at 21 59 02](https://user-images.githubusercontent.com/74188/146879298-7e72e020-16d7-4b75-a2cb-e4e49f16d53a.png) |
| Detail | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2021-12-20 at 21 59 07](https://user-images.githubusercontent.com/74188/146879316-7bb54369-455c-4b84-9a68-3e424a76e98c.png) | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2021-12-20 at 21 59 09](https://user-images.githubusercontent.com/74188/146879322-895acc93- …

Server privacy setting for sensors

---

Podfile.lock

Fixed compression in Starscream for aiohttp's WebSocket implementation and enabled it in HAKit.
This compression is pretty significant. My test server with ~1350 states clocks in at 580kb of data which compresses down to like 70kb, give or take.

Update Starscream fork & HAKit for WebSocket compression

---

.github/workflows/push_deploy.yml
Sources/PushServer/Sources/App/RateLimits/RateLimits.swift
Sources/PushServer/Sources/App/configure.swift

- Reduces Redis storage usage by minimizing keys & values.
- Increases Redis initial connection timeout from 10ms to 60s. This is the _intended_ duration by the library, but a healthy amount of default values in [the Vapor side](https://github.com/vapor/redis/blob/8037b6f66aec6a3bfbd13c7e881a80b3ac9e4f15/Sources/Redis/RedisConfiguration.swift#L27) causes `nil` to be passed down, which causes a `?? .milliseconds(10)` in [the Redis library](https://gitlab.com/Mordil/RediStack/-/blob/8ff8b03907ca0ff9d9f1778c932dbb0ae6884bd9/Sources/RediStack/Configuration.swift#L295).
- Makes APNS deploys cancel earlier ones, and detaches from the deploy so the GHA can exit earlier.

Minor redis & deploy improvements

---

.github/workflows/push_deploy.yml

For some reason this isn't parsing correctly without the string quotes. Also fixes the logic anyway.

Fix deploy YAML

---

.github/workflows/ci.yml

CI action takes too long.
It could be a good idea to cache Derived Data folder in the github action.
The point is to cache Build and SourcePackages and set the IgnoreFileSystemDeviceInodeChanges parameter to yes, as described in https://stackoverflow.com/a/54055857/1012432.
The thing is that SPM  revokes DerivedData when running in another machine and it downloads and recompile all again.
Another way to get the same result is to add the parameter IgnoreFileSystemDeviceInodeChanges=1 to xcodeBuild.
There was a try but seems it didn't work and was removed on  https://github.com/home-assistant/iOS/pull/1242.
It was a good try, but maybe the IgnoreFileSystemDeviceInodeChanges option was not setted.
In some projects i worked it was possible to reduce a pipeline from 30 minutes to 5 minutes. …

Caching derived data

---

Sources/Shared/API/Models/RealmZone.swift
Tests/Shared/RealmZone.test.swift

Fixes #2064.
When multiple zones contain the location when sending zone names only to the server, prefers the smaller radius.

Fix overlapping zones with zone-only privacy level

---

Sources/App/Utilities/AKConverter.swift

Fixes #2073.
If the input file is in the right format, succeed and copy it instead of failing.

Fix importing audio failing if format is correct already

---

Sources/Shared/Common/Extensions/URL+Extensions.swift

The webview resolves itself to the lowercased version of the URL, so any comparisons we do to determine if we need to reload result in reloading.
Some reports of this [on Reddit](https://www.reddit.com/r/homeassistant/comments/snz9g0/every_time_app_loses_focus_causes_lovelace_to/). This was found in the (only) logs I've received so far, and I can reproduce the issue for this specific reason. Could be other oversights.

Fix WebView reloading itself when hostname contains uppercase

---

Sources/Shared/API/Responses/DiscoveredHomeAssistant.swift

Version 0.110 started sending internal_url/external_url, but older versions than that send base_url.
This is really only a problem because versions older than 0.104 do not support including the device id in the registration, but we don't know the version number until we pull the config from the webhook, which can only be created after registering the device. Thus, if you're using a version older than 0.104 and doing manual setup, it'll still always fail, but discovery-based will start working after this.

Fix discovery of instances older than 0.110

---

Sources/Shared/API/Authentication/TokenManager.swift
Sources/Shared/API/HAAPI.swift

There is a potential race condition in token retrieving which could result in providing an old access token to a WebView external auth request. This should at least make it not provide the wrong one, even though the race condition will still occur with the saved keychain data.
My hunch is that a server's info is updated using stale data just as an access token is updated, which would cause the "grab the server.info.token" to use the wrong access token when constructing the dictionary.
Grabbing it from the server is unnecessary here - we're in the promise chain for getting the new access token anyway, so we can avoid the underlying issue by using the right token when we know it works.
I can sort of reproduce this by hammering server info updates and grabbing the dictionary but not in any …

Potentially fix invalid authentication issues

---

Sources/Shared/API/ServerManager.swift
Tests/Shared/ServerManager.test.swift

The cache for server infos was inserting the old 'fallback' value when read after deletion, which caused it to be used if the server was re-added while the app was still in memory afterwards.

Fix a just-deleted server being readded using old info

---

Sources/Shared/API/ConnectionInfo.swift
Sources/Shared/API/Webhook/Networking/Promise+WebhookJson.swift
Sources/Shared/API/Webhook/Networking/WebhookManager.swift
Sources/Shared/API/Webhook/Networking/WebhookRequest.swift
Sources/Shared/Environment/Constants.swift
Tests/Shared/ConnectionInfo.test.swift
Tests/Shared/Webhook/Promise+WebhookJson.test.swift

Refs home-assistant/core#67429.
Fixes the logic for decryption to use the full key, rather than half of it, when decoding/encoding the additional encryption we use for webhooks only.
This encryption is largely superfluous in the era of Let's Encrypt's dominance, but we're going to be reusing it for end-to-end encrypted notifications.

Convert webhook secret to bytes from hex

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/WebView/WebViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Settings/SettingsStore.swift

Fixes #1720.
On iPhone, this turns off the status bar text but continues to use the space, since the frontend doesn't handle the top safe area.
On iPad, this turns off the status bar and doesn't reserve any space.
| - | On | Off |
| iPad | ![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) (15 2) - 2022-03-05 at 19 18 14](https://user-images.githubusercontent.com/74188/156907781-b155d227-5429-4218-accd-f25ee4823e13.png) | ![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) (15 2) - 2022-03-05 at 19 18 37](https://user-images.githubusercontent.com/74188/156907787-4162dab4-4cd9-4431-ae4a-7944db706330.png) |
| iPhone | ![Simulator Screen Shot - iPhone 13 Pro (15 2) - 2022-03-05 at 19 22 08](https://user-images.githubusercontent.com/74188/156907836-b9e …

Add "Full Screen" setting

---

Sources/App/Onboarding/API/OnboardingAuthError.swift
Sources/App/Onboarding/API/Steps/OnboardingAuthStepConnectivity.swift
Tests/App/Auth/OnboardingAuthStepConnectivity.swift

Evaluates the certificate directly to try and get better error messages from SSL errors.
| ------ | ----- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-05-07 at 16 34 31](https://user-images.githubusercontent.com/74188/167275480-6ff57e2c-bfeb-4593-96bb-defa2197b95f.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-05-07 at 23 27 59](https://user-images.githubusercontent.com/74188/167284731-0488e550-45b6-4f09-b27c-f4d7f2ae7613.png) |

Improve SSL connection errors in onboarding

---

Sources/App/WebView/WebViewController.swift

Fixes e.g. [Frigate](https://docs.frigate.video/)'s notifications which open a /api/something path to show a video. Non-frontend pages will cause us to potentially get stuck since there's no on-screen UI to go 'back'.

Open non-frontend pages in external browser

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/LifecycleManager.swift
Sources/App/Settings/Sensors/SensorListViewController.swift
Sources/Extensions/PushProvider/PushProvider.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/PeriodicUpdateManager.swift

When the Local Push extension is running (when we're on Wi-Fi in an SSID marked as 'Internal' and location is set to Always), we're given a persistent opportunity to do work. When we're running, we now update sensors on a regular interval.
Documentation: home-assistant/companion.home-assistant#753
Updating the metadata/sensors every 5 minutes (by default) should have minimal, if any, battery implications. This follows the same setting as the "Periodic" timer which we use for foreground updates.

Periodically update sensors from local push extension

---

.github/workflows/distribute.yml
fastlane/Fastfile

Potentially fixes the distribute failures occurring. It looks like Apple's notarize server is down though, so blippity blip blip.

Retry notarize if it fails, allow Mac/iOS distributes to independently fail

---

Sources/App/Settings/Eureka/AccountRow.swift

Use an auth challenge aware URLSession to download the avatar. Missed this one internal use of URLSession.session in #2131.

Fix avatar row in settings with untrusted certificates

---

Sources/Shared/Common/Extensions/Realm+Initialization.swift

Undoes the evidently-faulty logic for how I was trying to automate the MDI migrations

Fix migration in last MDI update

---

README.md

This change to the README adds the installation step required for `cocoapods-acknowledgements` to the readme (where `pod` is installed via Homebrew rather than Bundler). The call to `pod install` would previously fail with:
[!] Your Podfile requires that the plugin `cocoapods-acknowledgements` be installed. Please install it and try installation again.
This also updates the Homebrew paths used to be dynamically determined, allowing the install instructions to work on Apple Silicon and for any custom Homebrew installation location.

Update README to ensure cocoapods plugin is installed, update Homebrew paths

---

Sources/App/Resources/Info.plist
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/Utilities/OpenInFirefoxControllerSwift.swift
Sources/App/Utilities/Utils.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

This adds support to open URLs in Firefox Focus/Klar. Firefox Focus and Klar are the same project
(see https://github.com/mozilla-mobile/focus-ios; and https://support.mozilla.org/en-US/kb/difference-between-firefox-focus-and-firefox-klar), but use different app scheme prefixes on account of the FOCUS name being used by a Mozilla partner in Germany, Austria and Switzerland.
This PR adapts and reuses the existing Firefox URL opener to being able to accept a different scheme for each app, defaulting to the standard `firefox://` prefix for regular Firefox.
From reading the developer docs, I'm unclear on if/how I should update the `Localizable.strings` files for other languages at this point. If there's something else I need to do for …

Add Firefox Focus/Klar as browsers for opening links

---

Sources/Shared/API/HAAPI.swift

The push provider's periodic updating runs the 'connect' mechanism, which also updates the registration/integration. In iOS 16, this means we're updating the device name to 'iPhone' because our device name entitlement only exists in the main app. To avoid this issue, we no longer update the registration in the push provider.

Skip updating registration in push provider

---

Sources/Shared/Common/Extensions/Realm+Initialization.swift

Fixes #2207.
By default, Realm does not compact its database and [they recommend doing so in production](https://www.mongodb.com/docs/realm/sdk/swift/realm-files/compacting/):
> Every production application should implement a `shouldCompactOnLaunch` callback to periodically reduce the realm file size.
This enables compaction when the database contains more than 50% free space in its on-disk representation. We periodically delete old models at runtime by age, so we expect this to be the case.

Enable Realm database compaction on launch

---

.github/workflows/distribute.yml
.github/workflows/size.yml
Gemfile.lock
fastlane/Fastfile
fastlane/Pluginfile
fastlane/README.md

The nice folks at [Emerge](https://emergetools.com) have given us access to their platform for sizing the app and doing some non-live performance testing. This integrates it it.
Turning off Bitcode by switching to Xcode 14 is causing our binary size to bloat, and to investigate this best I'll fix this long-term by keeping track of size changes.
This adds emerge to a few places:
1. Individual builds that are submitted to Apple
2. Pull requests
The PR builds do not get sent to Apple nor are they uploaded because we do not want to allow in-development changes to go anywhere with our official signing information.

Add Emerge integration

---

.github/workflows/distribute.yml
.github/workflows/size.yml
fastlane/Fastfile

The merge commit, rather than the status-able commit, were being sent up as the sha. Whoops.

Specify correct shas to Emerge

---

Sources/Extensions/NotificationContent/MapViewController.swift

The dynamic map attachment for push notifications has a fixed span for the region it shows. For certain cases you might want to show the map with a different zoom level. This pull request adds the `latitude_delta` and `longitude_delta` for this specific purpose.
Documentation: home-assistant/companion.home-assistant#891

Custom zoom level option for map dynamic attachment

---

Sources/App/Scenes/SettingsSceneDelegate.swift

Fixes #2300.
macOS 13, by default when linked against its SDK, places the navigation item contents in the toolbar. However, we already have a toolbar in settings, so it doesn't do anything and thus pushed screens are problematic.
This all needs to be rewritten into SwiftUI so we can use a native Mac UI. 😅

Fix settings navigation bar not appearing on macOS 13

---

Sources/MacBridge/MacBridgeImpl.swift
Sources/Shared/Environment/DeviceWrapper.swift
Sources/Shared/Environment/MacBridgeProtocol.swift

Instead of showing "iPad" we now show the correct name again.
`UIDevice.current.name` on Catalyst incorrectly protects the computer name behind an entitlement which isn't granted on Mac (we have it on other platforms). Since Mac doesn't have this entitlement, bridge to AppKit land and grab the value from there.

Fix device name reporting "iPad" on macOS 13

---

Sources/App/Onboarding/API/OnboardingAuth.swift
Tests/App/Auth/OnboardingAuth.test.swift

Stops inserting the current network hardware address, since it may be hardware which is connected to other networks. Allow the user to choose this later.
Since we can't directly tell when a hardware address is a valid way to consider internal, don't automatically include it. This resolves an issue where we'd think any Wi-Fi connection was internal which is invalid logic.

Don't automatically consider hardware address for internal URL

---

Sources/App/Resources/Info.plist
Sources/App/Resources/en.lproj/InfoPlist.strings

In addition to microphone permission, this is required for speech recognition in Assist.

Add speech recognition privacy description

---

Sources/App/Resources/Info.plist

Fixes error from Apple `ITMS-90032: Invalid Image Path - - No image found at the path referenced under key 'CFBundleAlternateIcons': 'default'`
Follow up from #2418

fix ha-blue icon

---

Gemfile.lock
Sources/App/WebView/IncomingURLHandler.swift
Sources/App/WebView/WebViewWindowController.swift

Navigate to default server when deeplink to the app passing "?server=default".
Currently when you use deep link to navigate to one lovelace page and you have multiple HA servers in your iOS App it always asks which server you want to use.
With this change you are able to default to your current server by using a query item "?server=default"
https://github.com/home-assistant/iOS/assets/5808343/c29ac74e-8ea4-4d5a-93ec-53ef7c64ced6

Navigate to default server when deeplink to the app passing "?server=default"

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

When you open your watchOS App for the first time you may encounter several scenes already active to be used in the watch App (specially if you have Philips Hue in HA), this change allows you to unselect all scenes at once (hide from watch app) if you want.
https://github.com/home-assistant/iOS/assets/5808343/e2f0f9fb-704d-4240-a817-4cf7318269b3

Toggle scenes/actions for watchOS App all at once

---

Sources/Shared/API/Webhook/Sensors/CoreMedia and CoreAudio Helpers/HACoreBlahObject.swift
Sources/Shared/API/Webhook/Sensors/CoreMedia and CoreAudio Helpers/HACoreBlahProperty.swift
Sources/Shared/API/Webhook/Sensors/CoreMedia and CoreAudio Helpers/HACoreMediaObjectCamera.swift
Sources/Shared/API/Webhook/Sensors/CoreMedia and CoreAudio Helpers/HACoreMediaObjectSystem.swift
Sources/Shared/API/Webhook/Sensors/InputOutputDeviceSensor.swift

Apparently `#if canImport(CoreMediaIO)` is now true even if you are trying to run the App on iOS instead of macOS, so this PR wraps it also under `#if targetEnvironment(macCatalyst)`

Wrap CoreMediaIO inside macCatalyst condition

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/Intents/Resources/Base.lproj/AppIntentVocabulary.plist
Sources/Extensions/Intents/Resources/Info.plist

Comply to: https://developer.apple.com/documentation/sirikit/registering_custom_vocabulary_with_sirikit/global_vocabulary_reference/intent_phrases
Pending translations to other languages.
Even though INShareFocusStatusIntent is an intent that apparently it's only used for iOS to tell HA when focus is active, we still get warning from Apple about having a siri vocabulary for it, perhaps we can keep it simple like what is in this PR just to address the warning.

Include vocabulary plist for INShareFocusStatusIntent

---

fastlane/Fastfile

Add missing language mapping to fastfile

---

Tests/Shared/Webhook/WebhookResponseUpdateComplications.test.swift

Fix flaky test testComplicationsWithPreRendered

Fix flaky test testComplicationsWithPreRendered

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/DropSupport/DropSupportMessageViewController.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/WebView/WebViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Add drop support announcement view

Add drop support announcement view

---

Sources/App/ThreadCredentialsSharing/ThreadClientService.swift

Prevent throw for second thread credentials call, since sometimes "preferredCredential" succeeds but "allCredentials" fail, we don't want to avoid showing the preferred credential.

Prevent throw for second thread credentials call

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/DebugSettingsViewController.swift
Sources/App/ThreadCredentialsSharing/ThreadCredentialsSharingView.swift
Sources/App/ThreadCredentialsSharing/ThreadCredentialsSharingViewModel.swift
Sources/App/WebView/WebViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Utilities/Haptics.swift

https://github.com/home-assistant/iOS/assets/5808343/0c6933a5-8208-4275-baad-39f731e2af46

Redesign thread credentials sharing

---

Sources/App/Resources/Info.plist

Avoid INStartCallIntent warning for using com.apple.developer.usernotifications.communication entitlement

Avoid INStartCallIntent warning for using com.apple.developer.usernotifications.communication entitlement

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Vehicle/Templates/Entities/CarPlayEntitiesListTemplate.swift

Update CarPlay message while entities are getting filtered

---

Sources/App/Settings/SettingsDetailViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

https://github.com/home-assistant/iOS/issues/2549

Fix info icon usage in actions

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Vehicle/Templates/Actions/CarPlayActionsTemplate.swift
Sources/Vehicle/Templates/Areas/CarPlayAreasViewModel.swift
Sources/Vehicle/Templates/Areas/CarPlayAreasZonesTemplate.swift
Sources/Vehicle/Templates/CarPlayPaginatedListTemplate.swift
Sources/Vehicle/Templates/Domains/CarPlayDomainsListTemplate.swift
Sources/Vehicle/Templates/Entities/CarPlayEntityListItem.swift
Sources/Vehicle/Templates/HAEntity+CarPlay.swift
Sources/Vehicle/Templates/MaterialDesignIcons+CarPlay.swift

Add pagination to CarPlay Areas and Actions tabs

---

.github/dependabot.yml

Github does have the [dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot) feature create pull request for dependecies that are outdated. This pr implements this for github actions.
No user facing changes.
NA
NA

implement dependabot to check for updates for github actions;

---

.github/workflows/push_ci.yml
Sources/PushServer/Package.resolved

To support new swift syntax we need to upgrade dependecies of the push server. See build erros in https://github.com/home-assistant/iOS/actions/runs/7963681144/job/21739760838?pr=2585.
No user facing chages.
NA
NA

Update Push server deps;

---

Sources/App/Settings/ActionConfigurator.swift
Sources/App/Settings/SettingsDetailViewController.swift

When user tap on "Create automation" inside the action configuration screen the app was crashing because it was trying to save the action which was controlled server-side (created in yaml). This was fixed in this PR

Prevent crash on creating automation from a server controlled iOS Action

---

Sources/App/Settings/SettingsDetailViewController.swift

In continuation of https://github.com/home-assistant/iOS/pull/2607, this replaces the deprecated `CLLocationManager.authorizationStatus()` call.

Address deprecated call in `SettingDetailViewController`

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/AppIntents/IntentActionAppEntity.swift
Sources/Extensions/AppIntents/PerformAction.swift
Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift
Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
Sources/Extensions/Widgets/Actions/WidgetActions.swift
Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
Sources/Extensions/Widgets/Common/WidgetBasicView.swift
Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
Sources/Extensions/Widgets/Widgets.swift

This PR upgrades 2 Siri intents to AppIntents and adds a new widget which can run actions (and scene actions) in background

Actions widget with background execution

---

Sources/Shared/Common/Extensions/UIColor+CSS3+Hex.swift

- removes unused `hexDescription`
- `fileprivate` => `private`
- typo fix (see screenshot)

🧹  Remove unused `hexDescription`

---

Sources/App/WebView/WebViewController.swift

As the closure always return a `UIButton`, the property itself does not need to be an (force-unwrapped) Optional.

Remove `settingsButton` optionality

---

Sources/Shared/Common/Extensions/CMMotion+StringExtensions.swift

- use a `switch` instead of if-else if-else
- use type inference for better readability

Use a `switch` for `CMMotionActivityConfidence.description`

---

Sources/Shared/Extensions/Data+Hexadecimal.swift

Replaces deprecated `Data.init`.

🔧 Fix deprecated `Data.init`

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/DebugSettingsViewController.swift
Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Add force refresh widgets to debug tools

---

HomeAssistant.xcodeproj/project.pbxproj
Podfile
Podfile.lock

Specify starscream version in podfile

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/SettingsDetailViewController.swift
Sources/Shared/API/Models/Action.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Some users have pointed out thei Actions sometimes are not sync, this is to help out define if the time of the sync is relevant. 

Add button to manually sync server Actions

---

HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
Sources/Extensions/Widgets/Assist/WidgetAssistProvider.swift
Sources/Extensions/Widgets/Assist/WidgetAssistView.swift

Material design font was not previously registered for this widget which was causing a crash, even though somehow the widget rendered correctly several times.

Register material design font for Assist widget

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/Widgets/Common/WidgetBasicView.swift
Sources/Shared/Extensions/Color+Codable.swift
Sources/Shared/Extensions/MaterialDesignIcons+Encodable.swift

Fix for:
This could also be one of the reasons for widgets going blank once in a while

Fix "View ID is not encodable" on WidgetBasicViewModel

---

Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift
Sources/Extensions/Widgets/Actions/WidgetActionsProvider.swift
Sources/Extensions/Widgets/Assist/WidgetAssistProvider.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift

When Realm was accessed it was bringing up to 20mb to memory, which helped exceeding 30mb (extensions limit) causing crash on widgets.
Specifying realm object types help use just enough memory needed

Fix widgets memory issue

---

Podfile.lock

Add missing podfile.lock

---

Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Intents/PerformActionIntentHandler.swift
Sources/Shared/Intents/WidgetActionsIntentHandler.swift

Improve memoty usage in intents using just the object types needed from realm database

Avoid invoking entire realm for action intents

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/Scenes/WebViewSceneDelegate.swift
Sources/App/WebView/IncomingURLHandler.swift
Sources/App/WebView/SafeScriptMessageHandler.swift
Sources/App/WebView/WebViewController.swift
Sources/App/WebView/WebViewWindowController.swift

I noticed we are losing web views during the usage of the App, for example, when the user logs out we create a new web view after it logs in, but the old webview was kept in memory due to strong reference of WKScriptMessageHandler or due to not be listed in our cached webviews dictionary (and then not removed).
This PR gains controls of creation and usage of webviews aswell as removing them when not needed anymore, it also fixes the issue that some users experience "failure to authenticate" notifications (that were partially caused by these ghost webviews)

Keep only necessary webviews alive in the app

---

Sources/App/Resources/WebSocketBridge.js
Sources/App/Utilities/ThemeColors.swift
Sources/App/WebView/WebViewController.swift

We were using `--app-header-background-color` for status bar in the app and frontend uses `--app-theme-color`, this PR changes that to keep consistency with frontend

Use same variable for status bar color as frontend

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/Extensions/Widgets/Assist/WidgetAssistProvider.swift
Sources/Shared/Intents/AssistInApp/AssistInAppIntentHandler.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Instead of leaving the widget in a "configuration pending" mode, this PR sets the preferred pipeline and first server available as the initial widget config

Define initial Assist widget configuration to use preferred pipeline

---

Sources/App/WebView/WebViewController.swift

overlayViewController reference was mistakenly weak, which was causing barcode scanner to not be displayed. On top of that now we can always have just one overlay, assist/barcode scanner/settings, presenting one will dismiss the previous one.

Fix barcode/assist/settings overlays, manage all overlays with 1 reference

---

Sources/App/Resources/WebSocketBridge.js
Sources/App/Utilities/ThemeColors.swift
Sources/App/WebView/WebViewController.swift

Reopening this PR now that https://github.com/home-assistant/frontend/pull/20758 is implemented

Align status bar color using same var as front end

---

Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift

Open Page widget had a an issue that depending on the servers you have configured and it's panels, it could select the wrong one for the widget.

Fix Open Page widget selection bug

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/ActionConfigurator.swift
Sources/Extensions/Watch/Home/Mocks/MockWatchHomeViewModel.swift
Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift
Sources/Extensions/Watch/Home/WatchHomeViewModel.swift
Sources/Extensions/Widgets/Actions/WidgetActions.swift
Sources/Extensions/Widgets/Common/WidgetBasicView.swift
Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift
Sources/Shared/API/Models/Action.swift
Sources/Shared/API/Responses/MobileAppConfig/MobileAppConfigAction.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Based on user feedback, color customisation is important on their iOS Actions, in widgets and Apple Watch, so this PR adds this option back but with a little modification, we will first enforce the tile card design as the standard, if the user wants to use custom colors it has to enable "custom colors" toggle in actions configuration screen. (I will also make a PR in Core to be able to configure that via YAML)
This PR also makes the "default" background color for watch items to be dark instead of white.

Add Actions custom colors back

---

Sources/Extensions/Watch/Complication/ComplicationController.swift
Sources/Extensions/Watch/ExtensionDelegate.swift
Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift
Sources/Shared/API/Models/Action.swift
Sources/Shared/Common/Extensions/Realm+Initialization.swift

For some reason Realm database migration was not being called event though scheme version was already bumped to 28, apparently this was caused by watch complication that was accessing realm passing specific object types
Test process:
- Checkout commit c257fa21f62acb964edb28c6d3db0796a86731f1
- Run App in iPhone and watch (with some Actions created)
- Checkout commit 2c8470e5fec8a6c715bfe7de113b3f35c37a4e84
- Run App in iPhone and watch
> - this was crashing in watch and now it is running the migration block.

Fix watch crash (Realm migration not called)

---

Sources/Shared/API/HAAPI.swift

sharedEventDeviceInfo contains "sourceDevicePermanentID",  "sourceDeviceName" and "sourceDeviceID" values. 
It is used in other action events (such as event triggered from the Apple Watch). "sourceDeviceName" can be used to send an actionable notification back to the device that was used to scan tag. Currently it's not possible, since these values are not dispatched in the event body.

Add sharedEventDeviceInfo data into the "tag_scanned" event

---

Sources/App/WebView/WebViewController.swift

Use mobile web content for iPad and desktop for mac

---

HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift
Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntentTimelineProvider.swift
Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift
Sources/Extensions/Widgets/Actions/WidgetActionsProvider.swift

Workaround for iOS 18 to avoid 'Realm accessed from incorrect thread.' if not called from main thread while in iOS 17 it reports the same error if called in the main thread.

Workaround to avoid iOS 18 crash widgets that use Realm

---

Sources/App/Improv/ImprovDiscoverView.swift

This PR moved SSID input step before connecting to device to avoid timeout while user inputs SSID.
Also copy update.

Improv-BLE UX updates

---

Sources/Extensions/AppIntents/Sensor/IntentSensorsAppEntity.swift
Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift

Fixed two issues mentioned in #3067;
Sensors in the suggested sensors view should be grouped by server now
The order of the selected sensors is now respected if they come from two different servers
The `for` loop bothers me, Swift feels a lot like Kotlin and a `map` seems more appriopiate.
Because an async call happens in it I could not get `map` working that is nice to read, let me know if there is a better option chatgpt gave me this
```
let sensorValues = try await withThrowingTaskGroup(of: WidgetSensorsEntry.SensorData?.self) { group in
for sensor in configuration.sensors ?? [] {
group.addTask {
guard let server = Current.servers.all.first(where: { $0.identifier.rawValue == sensor.serverId }) else {
throw WidgetSensorsDataError.noServers
}
return try await fetchSensorData(for: sensor, …
```

Group by server, widget selection order

---

Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
Sources/Extensions/AppIntents/Sensor/IntentSensorsAppEntity.swift
Sources/Extensions/Widgets/Light/IntentLightEntity.swift
Sources/Extensions/Widgets/Scene/Control/IntentSceneEntity.swift
Sources/Extensions/Widgets/Switch/IntentSwitchEntity.swift
Sources/Shared/ControlEntityProvider.swift

Changed the implementation of `getEntities(matching string: String? = nil)` to return an array of key values pairs instead of a dictioniary. The intent of the function seems to return a sorted list of entities grouped by server name since the servers are sorted `Current.servers.all.sorted(by: { $0.info.name < $1.info.name })`. A dictioniary does not guarantee order, resulting in unpredicting results in my `Sensor` widget configure window. Sometimes one server is first, the next time the other. 
Apple also recommends using a KeyValuePair when order is important:
https://developer.apple.com/documentation/swift/keyvaluepairs
`Use a KeyValuePairs instance when you need an ordered collection of key-value pairs and don’t require the fast key lookup that the Dictionary type provides.`
Because …

Preserve order getEntities function

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/DebugSettingsViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Add option to reset entities database in case user endup with some clutter from previous server.
TODO: Handle old cache information automatically

Add "reset app entities database" option in debug section

---

Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
Sources/Shared/DataWidgetsUpdater.swift

Since we can't update controls using push notifications yet (due to notification limits), this PR uses the refresh interval opportunity from widgets to also update controls

Refresh controls when widgets initialize

---

Sources/App/WebView/DownloadManager/DownloadManagerView.swift
Sources/App/WebView/DownloadManager/DownloadManagerViewModel.swift
Sources/Shared/Environment/AppConstants.swift

Improve download manager

---

Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift

Really small mr, I just came across it looking into the scripts widget. I assume the for loop only returns when all sync operations are finished, removing the need to manually check for it
The preview still seems to work fine when adding a widget

simplify for loop

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/AppDelegate.swift
Sources/App/HAApplicationShortcutItem.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Scenes/WebViewSceneDelegate.swift
Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/App/Settings/Observation/Action+Observation.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/WebView/IncomingURLHandler.swift
Sources/Extensions/Widgets/OpenPage/OpenPageAppIntent.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Settings/SettingsStore.swift

This opens HA server in safari instead of in the catalyst WKWebView

Add "Mac native features only" experimental mode

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/Scenes/WebViewSceneDelegate.swift
Sources/App/Settings/SettingsViewController.swift
Sources/Shared/API/Models/AppEntitiesModel.swift
Sources/Shared/API/Models/LegacyModelManager.swift
Sources/Shared/Environment/Environment.swift
Sources/Shared/Environment/PeriodicAppEntitiesModelUpdater.swift
Sources/Shared/HATypedRequest+App.swift
Tests/App/Auth/OnboardingAuthStepModels.test.swift
Tests/App/Auth/OnboardingAuthStepNotify.test.swift
Tests/Shared/ModelManager.test.swift

This PR will change the approach of how the app keeps it's data updated by not subscribing to all state changes and only periodic updating it's app entities instead.
This will avoid several issues where users experience their app to freeze due to 9k entities updating every second and notifying the app.

Periodic update app entities instead of subscribing to state updates

---

Sources/Shared/API/Webhook/Sensors/AudioOutputSensor.swift

Rename iOS audio sensor values

---

Sources/App/WebView/WebViewController.swift
Sources/Shared/HAGesture.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Fix swipe direction and comment gestures that are not working well yet

---

Sources/App/Onboarding/API/OnboardingAuth.swift
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/App/Settings/Connection/ConnectionURLViewController.swift
Sources/App/WebView/WebViewController.swift
Sources/Shared/API/ConnectionInfo.swift
Sources/Shared/API/Fixtures/ServerFixture.swift
Sources/Shared/API/Server+Fakes.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Tests/Shared/ConnectionInfo.test.swift
Tests/Shared/ServerManager.test.swift
Tests/Shared/Webhook/WebhookManager.test.swift

Since we don't fallback to internal URL anymore for security reasons, this PR adds a toggle to allow fallbacking in case the user really needs it (with a warning before enabling).

Add option to always fallback to internal URL

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Shared/Common/Extensions/GRDB+Initialization.swift
Sources/Shared/EntityRegistryListForDisplay.swift
Sources/Shared/Environment/PeriodicAppEntitiesModelUpdater.swift
Sources/Shared/HATypedRequest+App.swift

So we can use the "decimal places" value to display sensors widget correctly
CC: @Penait1 

Cache config/entity_registry/list_for_display

---

Sources/App/Settings/Eureka/AccountRow.swift

Avoid unecessary subscription while fetching user avatar

---

Sources/App/Resources/en.lproj/Localizable.strings

As GitHub is a brand name, the camel-case "H" should be kept.
Noticed this in Lokalise as a translator added a respective comment.

Fix typo "Github" in Localizable.strings

---

Sources/App/Resources/en.lproj/Localizable.strings
Sources/Extensions/Watch/Assist/WatchAssistView.swift

Remove trailing space from copy

---

Sources/App/WebView/WebViewController.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

Fix duplicate swipe gesture

---

Sources/App/Settings/Widgets/Builder/WidgetBuilderView.swift
Sources/App/WebView/WebViewWindowController.swift
Sources/Extensions/Widgets/Widgets.swift

Allow custom widget on iOS 17 and close other controllers when create widget is triggered

---

Sources/Shared/HAGesture.swift

Since the swipe right in a native app goes back, swiping with 2 fingers right makes more sense to also go back instead of forward

Replace default 2 fingers swipe gesture to make it more intuitive in iOS

---

Sources/App/Onboarding/Screens/Bluetooth/BluetoothPermissionView.swift
Sources/App/WebView/WebViewExternalMessageHandler.swift
Sources/Shared/Settings/SettingsStore.swift

Before the screen was shown twice then never again if the user skips it, but then there is no way for the user to manually enable bluetooth.
With this change the user can still close the permission screen but it will be prompted again to make a choice as soon as devices & integrations page loads.

Display bluetooth permission request until user make a choice

---

Sources/App/AppDelegate.swift
Sources/App/Settings/ClientEventsLogView/ClientEventsLogView.swift
Sources/App/Settings/ClientEventsLogView/ClientEventsLogViewModel.swift
Sources/App/Settings/SettingsDetailViewController.swift
Sources/App/ZoneManager/ZoneManager.swift
Sources/App/ZoneManager/ZoneManagerRegionFilter.swift
Sources/Shared/API/Authentication/TokenManager.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/AppEntitiesModel.swift
Sources/Shared/API/Models/RealmZone.swift
Sources/Shared/API/Webhook/Networking/Promise+WebhookJson.swift
Sources/Shared/API/Webhook/Networking/WebhookManager.swift
Sources/Shared/API/Webhook/Networking/WebhookResponseLocation.swift
Sources/Shared/ClientEvents/Model/ClientEventStore.swift
Sources/Shared/Common/Extensions/XCGLogger+Export.swift
Sources/Shared/Database/DatabaseTables.swift
Sources/Shared/Database/Tables/ClientEventTable.swift
Sources/Shared/Environment/AppConstants.swift
Sources/Shared/Environment/AppDatabaseUpdater.swift
Sources/Shared/Environment/Environment.swift
Tests/App/ZoneManager/ZoneManager.test.swift
Tests/Shared/ClientEventTests.swift

More context can be found here: https://github.com/groue/GRDB.swift/issues/1626#issuecomment-2623927815
This PR tries to workaround crashes related to database lock in multiple OS processes, now client events are saved on jsonfile instead of GRDB

Save ClientEvents on local json file instead of GRDB to avoid crashes

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Scenes/WebViewSceneDelegate.swift
Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift
Sources/App/Settings/Widgets/Builder/WidgetBuilderView.swift
Sources/App/Settings/Widgets/Builder/WidgetBuilderViewModel.swift
Sources/App/Settings/Widgets/Builder/WidgetCreationView.swift
Sources/Extensions/Widgets/Common/WidgetBasicView.swift
Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift
Sources/Extensions/Widgets/Custom/AppIntents/CustomWidgetActivateAppIntent.swift
Sources/Extensions/Widgets/Custom/AppIntents/CustomWidgetPressButtonAppIntent.swift
Sources/Extensions/Widgets/Custom/AppIntents/CustomWidgetToggleAppIntent.swift
Sources/Extensions/Widgets/Custom/AppIntents/ResetAllCustomWidgetConfirmationAppIntent.swift
Sources/Extensions/Widgets/Custom/AppIntents/UpdateWidgetItemConfirmationStateAppIntent.swift
Sources/Extensions/Widgets/Custom/WidgetCustom.swift
Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift
Sources/Shared/DesignSystem/Components/ExternalLinkButton.swift
Sources/Shared/Resources/Swiftgen/Strings.swift
Sources/Shared/Widget/CustomWidget.swift

Add option to require confirmation before running custom widget item

---

Sources/App/Scenes/WebViewSceneDelegate.swift
Sources/Extensions/Widgets/Custom/AppIntents/CustomWidgetToggleAppIntent.swift
Sources/Extensions/Widgets/Custom/AppIntents/UpdateWidgetItemConfirmationStateAppIntent.swift
Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift
Sources/Shared/Domain/Domain.swift
Sources/Shared/Environment/AppConstants.swift

There is a long term bug in iOS which calls widget timelines several times even though once would be enough to render the widget. Since apparently Apple is not giving attention to that and out custom widgets make data calls, this PRs ads a small cache to prevent unecessary data calls. 

Workaround iOS issue calling widget timelines several times

---

Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
Sources/App/Settings/Connection/ConnectionURLViewController.swift
Sources/Shared/API/ConnectionInfo.swift
Tests/Shared/ConnectionInfo.test.swift

Reverts home-assistant/iOS#3341
Reverting while we redesign this flow for a better UX for non-technical users

Revert "Adding back warning about internal URL usage"

---

Sources/App/Settings/ActionConfigurator.swift
Sources/App/WatchCommunicatorService.swift
Sources/App/WebView/IncomingURLHandler.swift
Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
Sources/Extensions/Widgets/Scene/SceneAppIntent.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/Action.swift
Sources/Shared/Intents/CallServiceIntentHandler.swift

To leverage the features from the legacy iOS Actions, this PR adds triggerSource to all service calls in the app so users can automate based on which device (watch/phone/car) triggered that.

Add "triggerSource" to service calls

---

Sources/Extensions/Widgets/Controls/Switch/IntentSwitchEntity.swift

Include input_boolean to ControlSwitch for iOS 18+

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/WebView/IncomingURLHandler.swift
Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
Sources/Shared/API/AppTriggerSource.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/API/Models/Action.swift
Sources/Shared/MagicItem/MagicItem.swift

Move magic item execution out of API file

---

Sources/Extensions/Widgets/Controls/Switch/SwitchIntent.swift

Fix SwitchIntent to handle more domains such as input_boolean

---

Sources/App/Notifications/NotificationManager.swift
Sources/App/WebView/IncomingURLHandler.swift
Sources/App/WebView/WebViewController.swift
Sources/App/WebView/WebViewWindowController.swift
Sources/Extensions/Widgets/OpenPage/OpenPageAppIntent.swift
Sources/Shared/Environment/AppConstants.swift

A bit hacky but this PR avoids reloading lovelace when opened from OpenPageIntent (shortcuts, widgets, control center) and there is a lovelace open already, ignoring the tab.

Avoid reload lovelace when opened from OpenPageIntent

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/App/Onboarding/Screens/OnboardingServersList/OnboardingServersListView.swift
Sources/App/Onboarding/Screens/OnboardingWelcomeView.swift
Sources/App/Resources/Base.lproj/LaunchScreen.storyboard
Sources/App/Resources/en.lproj/Localizable.strings
Sources/App/Utilities/Extensions/SwiftUI+SafeArea.swift
Sources/App/WebView/Views/WebViewEmptyStateView.swift
Sources/Shared/DesignSystem/Components/HAProgressView.swift
Sources/Shared/Resources/Swiftgen/Strings.swift

https://github.com/user-attachments/assets/3c38cf4d-94dc-479e-9475-dbbae9080540

Improved welcome and server list onboarding

---

Sources/App/WebView/WebViewController.swift

This PR removed the error description from the bottom toast/notification since sometimes the error provided by iOS is misleading in the scenario that the user is facing at the moment. User can still look into more info tapping the question mark icon.
This PR also changed the design of this dialog and does not add an overlay on the "disconnected screen".
Before/After

Redesign error notification when retry over "disconnect" screen

---

Sources/App/BarcodeScanner/Camera/BarcodeScannerCamera.swift
Sources/App/BarcodeScanner/Camera/BarcodeScannerCameraView.swift
Sources/App/BarcodeScanner/Camera/BarcodeScannerView.swift
Sources/App/WebView/WebViewExternalMessageHandler.swift
Tests/App/WebView/WebViewExternalMessageHandlerTests.swift

Scan barcodes/qrcodes only inside the highlighted area

---

Sources/App/WebView/Extensions/WebViewControllerProtocol+Implementation.swift
Sources/App/WebView/WebViewController.swift
Sources/App/WebView/WebViewControllerProtocol.swift
Sources/App/WebView/WebViewExternalMessageHandler.swift
Sources/App/WebView/WebViewWindowController.swift
Tests/App/WebView/Mocks/MockWebViewController.swift

This fixes issue where navigating to a specific page (via widget when the app is coming form a cold state) was not loading the proper page.
This PR also centers some webView call to specific functions to better track navigation.

Ask to navigate through frontend while fallback to loading through webview

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
Sources/Extensions/Widgets/Common/WidgetBasicView.swift
Sources/Extensions/Widgets/Controls/Cover/CoverIntent.swift
Sources/Extensions/Widgets/Controls/Light/LightIntent.swift
Sources/Extensions/Widgets/Controls/Switch/SwitchIntent.swift
Sources/Extensions/Widgets/Custom/WidgetCustom.swift
Sources/Extensions/Widgets/Scene/SceneAppIntent.swift
Sources/Shared/API/HAAPI.swift
Sources/Shared/Domain/Service.swift
Sources/Shared/HAServices.swift
Sources/Shared/HATypedRequest+App.swift
Sources/Shared/MagicItem/MagicItem.swift
Sources/Watch/WatchCommunicatorService.swift
Tests/Shared/Service.test.swift

- Scripts were being executed using it's ID as service name, which was incorrect since if a user change this ID the service name won't be found anymore, so now it uses service "turn_on" with entity_id as the script ID.
- This PR also moves hardcoded services strings to enum

Fix scripts execution

---

Sources/App/WebView/WebViewController.swift

This PR hides the empty state when the App is sent to background and displays it again after the App returns to foreground with 4 seconds of not being connected.
This avoids users seeing the empty state when coming back from background and disconnected due to inactivity.

Hide empty state when going to background and show again if needed after returning to the app

---

HomeAssistant.xcodeproj/project.pbxproj
Sources/Extensions/Watch/ExtensionDelegate.swift
Sources/Extensions/Watch/Home/WatchHomeView.swift
Sources/Extensions/Watch/HostingController.swift
Sources/Extensions/Watch/WatchMain.swift
Sources/WatchApp/Base.lproj/Interface.storyboard

When using hosting controller on watchOS 26, none of the navigation bar buttons works, this PR moves away from using it and declared a swiftUI view as the main view for the app to start on.

Avoid using hosting controller on watch App
